### ISSUE TITLE
[FEATURE] "Apply active effects" Button

### ISSUE THREAD

**Issue by Padnon** [MangoFVTT/fvtt-ready-set-roll-5e#100]
Hello,

Not sure that is a feature request or a bug to fix. I use Midi QoL to have a "apply active effects" on selected tokens button using DAE. Unfortunately the compatibility with Midi QoL doesn't allow that today. When Midi QoL is working alone it works partially (not displaying damage in the same card), but when i use both Midi and Ready Set Roll i lose this feature. This interaction between the 2 modules worked well with an old version of Better Rolls on V9. 
I like very much the Ready Set Roll aesthetics and interface and i'd prefer to get rid of Midi than RSR.

![image](https://user-images.githubusercontent.com/101720041/195597371-8a66d948-2b7a-43d5-a6d4-207d1263bd5f.png)
With Midi Qol : displaying a "Apply Active Effects" button but doesn't display damage

![image](https://user-images.githubusercontent.com/101720041/195597599-99540692-bafe-4e4b-98fa-8ab19bb48fe7.png)
With RSR : displaying damages as i like but not "Apply Active Effect" button.

Thank you for reading and sorry for my bad english.

**Comment by MangoFVTT** [comment]
This feature is in active development at the moment. No ETA because I have to juggle this with my actual job 😅. I'm closing this ticket as a duplicate since it is being tracked in #39
