### ISSUE TITLE
[BUG] Quickrolls: multiple damage formulas break when calling damage type on formulas with variables

### ISSUE THREAD

**Issue by Oofious** [MangoFVTT/fvtt-ready-set-roll-5e#102]
**Description**
Adding damage types to rolls that call variables such as class levels when creating damage rolls on items/weapons causes the quickroll system to break and prevent rolling.

**Steps to Reproduce**
1. Create a new weapon and add two damage formulas
2. In one of the damage fields make a dice roll calling on a variable. ex. ((@classes.rogue.levels)d6[psychic])
3. In the next damage field put any formula. ex. (2d4[fire] or just 2d4)

**Versions**
 - Module: [1.3.11]
 - dnd5e: [2.0.3]
 - Foundry: [10.288]

**Comment by Oofious** [comment]
The issue doesn't seem to be the class variables but instead the addition of damages in formula such as adding [psychic], I am updating the bug report to match. I'm super sorry with how much of a mess this turned out to be on my side, I thought I had isolated the problem until I attempted to replicate.

**Comment by MangoFVTT** [comment]
Good catch! This has been fixed and will be in the next release.
