### ISSUE TITLE
[FEATURE] Flags for automatic disadvantage/advantage

### ISSUE THREAD

**Issue by baal000** [MangoFVTT/fvtt-ready-set-roll-5e#104]
One Feature that would be nice to have is the automatic application of advantage or disadvantage on saving throws,ability checks and skill checks with quick roll. For example my players and I have a hard remembering to apply disadvantage on Stealth if someone is wearing heavy armor.

A good solution in my opinion would be some kind of Flag you can add to an effect which automatically set the specific skill to roll with advantage without the need to manually trigger it on the roll.

I'm not sure if this is a niche problem but I surely would be happy to no longer worry about that.
Thanks for your hard work

**Comment by MangoFVTT** [comment]
Adding flags for permanent advantage or disadvantage is a bit outside the scope of this module, but there are already 2 ways you can get around this quite easily:

- Use the retroactive advantage/disadvantage buttons. Whenever you roll a d20 (if you have the "Enable Overlay Buttons" setting enabled) you can hover over the d20 part of the roll in the chat card, and then press the + or - buttons to add advantage and disadvantage respectively.
- Use the "Always Roll Multiple Dice" setting. This will always roll a dual roll for d20 rolls, allowing you to pick out advantage/disadvantage with ease whenever you need it.
