### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by shecrio** [MangoFVTT/fvtt-ready-set-roll-5e#105]
**Description**
With "Enable Quick Roll for Items" on items do not use up limited uses when rolled. Consumables however still work as intended.

**Steps to Reproduce**
Set a weapon or a piece of equipment to have Limited Uses, recharge does not matter. Setting Resource Consumption to using item charges of self does not effect the outcome. Enabling Alternate Roll or using Alternate Roll for items does to effect the outcome.

**Versions**
 - Module: [1.3.11]
 - dnd5e: [2.0.3]
 - Foundry: [10.288]

**Other Modules**
Only libWrapper

**Comment by MangoFVTT** [comment]
I am unable to reproduce this bug on Weapons or Equipment. Items with limited charges seem to work exactly as intended on my end. Please ensure that you are correctly setting up the Roll Configuration for the item:

![image](https://user-images.githubusercontent.com/110994627/199181594-623f961d-274a-4dcd-8f5c-178a4a686881.png)

If you want the item to directly use one of its limited uses, check the Uses box. If you instead want to set up the item with a Resource Consumption and then have it use the limited uses through that, check the Resource box instead.
