### ISSUE TITLE
[BUG]Incorrect context displays in quick rolls

### ISSUE THREAD

**Issue by Oofious** [MangoFVTT/fvtt-ready-set-roll-5e#106]
**Description**
Context gets applied incorrectly to rolls dependent on what rolls are checked or not checked for any given quick roll (normal or alt), resulting in incorrect context being displayed on the chat screen.

**Steps to Reproduce**
1. create a new item and give it two damage formulae
2. add an arbitrary formula to each roll (i.e., 1d4, 2d6), and give different contexts to each roll (i.e., Context1, Context2)
3. In the quick roll page disable the first formula (Context1) so it doesn't roll
4. When you roll the item, it will display the correct roll of 2d6 (Context2) while displaying Context1 as the context of that roll in the chat

**Versions**
 - Module: [1.3.11]
 - dnd5e: [2.0.3]
 - Foundry: [10.288]

**Comment by MangoFVTT** [comment]
This issue has been resolved and will be in the next release.
