### ISSUE TITLE
[BUG] actor.rollAbility macro does not function properly

### ISSUE THREAD

**Issue by Kailan7401** [MangoFVTT/fvtt-ready-set-roll-5e#107]
**Description**
The macro shown in the screenshot does not function properly when RSR is active. It ignores the @mod and @prof portions of the macro, instead only parsing the rollAbility portion. deactivating RSR allows the macro to function as intended.

With RSR
![image](https://user-images.githubusercontent.com/32316785/201350368-362e36c2-b347-4af2-a9d2-b877736f2b3f.png)

Without RSR
![image](https://user-images.githubusercontent.com/32316785/201352572-27417862-2aaf-4e47-b3c8-47a11574513c.png)

**Versions**
 - Module: [1.3.11]
 - dnd5e: [2.0.3]
 - Foundry: [10.287]

**Other Modules**
Problem persists with no other modules active.

**Comment by MangoFVTT** [comment]
Macro support is not yet implemented. It is a pending feature, but due to current time constraints with my actual job at the moment development is slow. Sorry for the inconvenience. You can keep an eye on future updates for when this feature is implemented in the module.
