### ISSUE TITLE
[FEATURE] Quick Roll Defaults No Description for Weapons/Attacks

### ISSUE THREAD

**Issue by hiwakaoru** [MangoFVTT/fvtt-ready-set-roll-5e#109]
![image](https://user-images.githubusercontent.com/118070296/201485494-82d9d5c8-3958-4932-b80e-45eaca6b9540.png)

![image](https://user-images.githubusercontent.com/118070296/201485858-b160aebc-b547-4d9b-9fba-75dc2eb58ff4.png)

The default roll options page in quick rolls has no module level default settings listed under its options. Anything in the Weapons category (Attacks for monsters) seem to default to no description. Spells, Equipment, and other objects seem to display the descriptions by default. First, it's inconsistent. But more importantly it means weapons with extra effects on them need to have us open the item on the sheet to reference anything that it does.

Ideally an option could be added into the module settings to enable the default display of descriptions for items, and update existing items settings accordingly. I know this was an option in the previous roll module used BetterRolls for 5e, but I'm not smart enough to poke around and figure that out myself.

Cheers on the module, it's very good.

**Comment by MangoFVTT** [comment]
The intent of this module is to keep behaviour as close to Better Rolls as possible, since that is what the majority of people want from it. The default settings for what part of the roll are shown have been kept identical to Better Rolls for that reason, including descriptions being off for weapons. You can always turn them on on an item by item basis, that's what the quick roll configuration is for 🙂

**Comment by hiwakaoru** [comment]
That's strange. I had used Better Rolls up to V10 when it became defunct. Rolls definitely displayed descriptions, and fairly sure that might have been an option at the module level and not item by item. If it wasn't just all on by default for descriptions.

I would have to pull back up my v9 save to take some shots. I haven't added any new rolling modules (just swapped in RSR) that I'm aware of.

**Comment by MangoFVTT** [comment]
Ah noted, I wasn't aware this existed since I never used it myself. I'll add it to the planned feature list 👍

**Comment by MangoFVTT** [comment]
This feature has been implemented and will be in the next release.
