### ISSUE TITLE
[BUG] Versatile option is ignored when rolling damage

### ISSUE THREAD

**Issue by Larkinabout** [MangoFVTT/fvtt-ready-set-roll-5e#11]
**Description**
Versatile option is ignored when rolling damage. Not sure if this is a bug or not implemented yet.

**Steps to Reproduce**
1. Add Battle Axe +1 to actor.
2. Tick 'Versatile' under Quick Roll tab on item.
3. Roll attack.

I couldn't find any reference to the `quickVersatile` flag being passed into the params for the `item.rollDamage` method to pick up in the `addFieldDamage` function.

**Versions**
 - Module: [1.0.1]
 - dnd5e: [2.0.2]
 - Foundry: [10.284]

**Other Modules**
None.

**Comment by MangoFVTT** [comment]
Seems like an oversight from my end. Will be fixed in the next hotfix release.

**Comment by MangoFVTT** [comment]
Fixed by PR #14.
