### ISSUE TITLE
[BUG] Rolls don't work with unlinked token

### ISSUE THREAD

**Issue by krysztalzg** [MangoFVTT/fvtt-ready-set-roll-5e#111]
**Description**
If you drop unlinked token onto a map (eg. any npc actor) and add new rollable item to sheet for that token it will fail to roll because you try to access original actor item that doesn't contain given item.

**Steps to Reproduce**
1. Set module to use manual damage rolls.
2. Create NPC actor.
3. Place it onto a map.
4. Open sheet by 2x clicking the token.
5. Add new feature/item (eg. sneak attack that just rolls `4d6`).
6. Try to roll damage from chat card.

**Versions**
 - Module: 1.3.11
 - dnd5e: 2.0.3
 - Foundry: 10.290

**Additional info**
This is first check that fails, but after that there's plenty
![image](https://user-images.githubusercontent.com/6009785/201745365-1e4b7edc-8473-4f7e-b2af-34328db343eb.png)

**Comment by MangoFVTT** [comment]
That clarifies matters! Issue should now be resolved and will be in the next release.
