### ISSUE TITLE
[FEATURE] Compatibility with Crash's Automatic Blind rolls

### ISSUE THREAD

**Issue by Dom-Odyssey** [MangoFVTT/fvtt-ready-set-roll-5e#116]
**Is your feature request related to a problem? Please describe.**
The module crash's automatic blind rolls, worked with better rolls 5e in foundry v9, the module currently still works with v10, when ready set roll setting for quick rolls is turned off for skills. When ready set roll is set to quick roll skills the ready set roll skill chat card does not show up blind.

**Describe the solution you'd like**
I would like the ability to set specific skills to roll blind automatically while still being able to use the ready set roll quick roll chat cards for skills. 

**Additional context**
on the project page for crash's automatic blind rolls, they mention that if any module devs want to have their module supported by theirs', they have released the tools necessary on the API section of their github wiki.
here is a link to their model: https://github.com/crash1115/blind-roll-skills

I have placed an issue on their project as well if that helps with communication.

**Comment by crash1115** [comment]
I'll be working on this... soon. Hopefully sometime before the end of the year once I have some time off work. 👍

**Comment by MangoFVTT** [comment]
As per #133, compatibility should be functional in the next release.
