### ISSUE TITLE
[BUG] Editing a field in an item makes the window jump back up to the top

### ISSUE THREAD

**Issue by cs96and** [MangoFVTT/fvtt-ready-set-roll-5e#131]
**Description**
When you are editing an item, and Ready Set Roll is enabled, every time you change the value of a field, the window jumps back up to the top, which is incredibly annoying!  (see screen capture below)

**Steps to Reproduce**
1. Open up an item sheet (e.g. a Longsword)
2. Scroll down to the bottom of the sheet
3. Change one of the fields near the bottom (e.g. Versatile Damage) and then press tab, or click off the field
4. Notice the window jumps back up to the top

**Versions**
 - Module: 1.3.14
 - dnd5e: 2.0.3
 - Foundry: 10.291

**Other Modules**
 - lib-wrapper

I worked out that if you comment out the call to `SheetUtility.setAutoHeightOnSheet(sheet)` on [line 53 of sheet.js](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/blob/bd968623908e46c40b25100737f45c7e0f696a74/src/utils/sheet.js#L53), then the problem goes away.  However, I'm not sure if this has any knock-on effects.

![Peek 2023-01-14 18-39](https://user-images.githubusercontent.com/898086/212490611-8180a5ce-bed8-41fa-aa27-0ad24d5555ea.gif)

**Comment by MangoFVTT** [comment]
This issue has been fixed and will be in the next release.
