### ISSUE TITLE
[FEATURE] Support options.rollMode in the actor.RollSkill override method

### ISSUE THREAD

**Issue by crash1115** [MangoFVTT/fvtt-ready-set-roll-5e#133]
**Is your feature request related to a problem? Please describe.**
The vanilla dnd5e system `actor#RollSkill` method allows you to supply `rollMode` in the `options` param, and modifies the Roll Mode dropdown in the roll dialog based on the given value. When Ready Set Roll is enabled, any macros or other code that supply a `rollMode` in this way don't respect the given value when RSR fast-forwards the roll.

You can test this functionality by using the following script macro:
```js
actor.rollSkill("prc", {rollMode: "blindroll"})
```
In vanilla dnd5e, the roll prompt will have Blind GM Roll selected and then roll as expected:
![image](https://user-images.githubusercontent.com/41387713/212581405-9339f2c4-fbf3-4e69-9872-b47a7b4f5036.png)

With RSR enabled:
![image](https://user-images.githubusercontent.com/41387713/212581460-1a563cb3-05dc-4914-bb8c-52112fcaf4f7.png)

**Describe the solution you'd like**
Add support for the `rollMode` option in your override for `actor#RollSkill`

**Describe alternatives you've considered**
N/A

**Additional context**
This fix should close out #116 as soon as I get my v10 release for Blind Rolls out.

**Comment by MangoFVTT** [comment]
Noted, should be doable. Will look into a fix asap and update this ticket when complete

**Comment by MangoFVTT** [comment]
This has been implemented and will be in the next release.
