### ISSUE TITLE
[BUG] Ammunition Traits Don't Carry Into Bow Attack & Damage Rolls

### ISSUE THREAD

**Issue by GameCrazed** [MangoFVTT/fvtt-ready-set-roll-5e#134]
**Description**
As the title suggests, I've found that with this module enabled, any bow attack (tested with short & longbow) that is configured to use magical ammunition (ie +1, +2, +3 ammo, etc) doesn't actually use those bonuses, it just decreases the remaining uses. I've tested this in a clean Foundry install, just the DND5e system, libwrapper, and Ready Set Roll installed so it's definitely not a module conflict.

I've included an image below that shows a bow attack made with a +3 arrow both with RSR disabled, and then again with it enabled. This was all done within the aforementioned test instance and using items imported from the default 5e SRD (with the small change of configuring the resource usage for the bow):
![image](https://user-images.githubusercontent.com/7393464/212733980-76f83fb4-550f-4f72-a922-8e0932d818af.png)

And here is the configured settings for that test, which went unchanged throughout reproduction:
![image](https://user-images.githubusercontent.com/7393464/212734847-740a8198-02fd-47b8-a5dc-baaf2f738dc6.png)

**Steps to Reproduce**
1. Go to any player character (not tested for NPCs but I assume it's the same).
2. Configure a bow attack to use any SRD magic ammo (i.e. +3 Arrow)
3. Make a bow attack.
4. See the bonus from the magic ammunition hasn't affected the attack roll or the damage roll

**Versions**
 - Module: [1.3.14]
 - dnd5e: [2.1.2]
 - Foundry: [10.291]

**Other Modules**
libWrapper [1.12.11.0]

**Comment by GameCrazed** [comment]
Just tested this with the recently deployed 1.4.0 version and can confirm it's still an issue (replicated in same way as posted above). It's not the end of the world obvs, but if there's any further info I can offer to help sort the issue then I'd be happy to provide it. I've attempted a fix myself but JS really isn't my forte.

**Comment by MangoFVTT** [comment]
@GameCrazed I haven't implemented a fix for this yet. I will update this ticket when I do so, should be soon(ish) 🙂

**Comment by GameCrazed** [comment]
Oh it's no problem, I just wanted to make sure it was still an issue after the release in case the changes had the side effect of fixing it. I wasn't meaning to hound you <3

**Comment by MangoFVTT** [comment]
This issue has been fixed and will be in the next release.
