### ISSUE TITLE
Always roll damage button expanded options. 

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#137]
Currently there is an option to automatically roll damage always, it would be nice if there were some extra options like to always roll damage except if a attack roll is present. If you throw a fireball you always want the damage (unless every enemy has evasion I guess, but that's unlikely) but with a weapon attack, personally, I'd only want the damage on a hit.

Keep up the good work!

**Comment by MangoFVTT** [comment]
This feature has been implemented and will be in the next release
