### ISSUE TITLE
Reroll specific dice

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#138]
Some features like the piercer feat allow you to reroll specific dice. It would be nice to have the option to reroll damage dice for example by opening the tab in the chat card that shows you the dice you rolled and then be able to right click on them or something.

Keep up the good work!

**Comment by stschoelzel** [comment]
+1
Some of my players can reroll almost every second dice if they choose too - that feature would be really nice.

**Comment by JeremyEffinger** [comment]
Aye +1 as well. I was looking at trying to implement this myself but I'll be honest no idea what I'm looking at here.

**Comment by MangoFVTT** [comment]
This feature has been implemented and will be in the next release.
