### ISSUE TITLE
Template expiration mechanics. 

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#139]
It would be nice if templates placed would remove themselves after a certain time. Midi qol has this as a feature (I believe the only module for v10 that does this) but midi qol and this module don't mash that well together (and obviously I prefer to use this one). 
It would be nice to see that feature replicated, possibly with the use of the times-up module.

Keep up the good work!

**Comment by MangoFVTT** [comment]
Automation of that level is not part of the features I plan to have in this module. Relatively low automation is generally the appeal for people using RSR, and integrating more and more functionality makes it much harder to update to new versions (this was something that killed BetterRolls originally). Hopefully at some point in the future this module will be able to work alongside MidiQOL, but until then it's not planned to add in the sort of automation that Midi provides
