### ISSUE TITLE
[Feature suggestion] "Roll groups" or alternate damage rolls

### ISSUE THREAD

**Issue by raimuhello** [MangoFVTT/fvtt-ready-set-roll-5e#144]
Would love a feature where you're able to have different damage rolls for items (in my case specifically, I have a "transforming" weapon that has an different damage roll depending on the form used).

Now, these screenshots are shamelessly using the [rollgroups ](https://github.com/krbz999/rollgroups)module which replaced the now sunset MRE, but they're just used to display the idea (I seem to remember Better Rolls having something similar too if I'm not mistaken?):

![image](https://user-images.githubusercontent.com/43730384/215092636-f8895536-f262-4a3e-a4f9-706f6bd547f4.png)

![image](https://user-images.githubusercontent.com/43730384/215092532-23751629-2256-4cf1-874e-28436f4faecb.png)

Since Ready Set Roll and rollgroups seem to be very incompatible, would something similar be possible to implement to Ready Set Roll natively? I of course prefer Ready Set Roll and all the plethora of features it brings, so it's a bit sad losing out on the other functionality :)

Thanks for everything so far though!

**Comment by MangoFVTT** [comment]
@raimuhello This feature is part of RSR already! If you enable the "Enable Alternate Roll for Items" setting, you can then configure different damage combinations for the item and roll them separately, one group for the default roll (just left click) and one for the alternate roll (alt + left click). You can set up the configuration for each item in the "Quick Roll" tab!

![image](https://user-images.githubusercontent.com/110994627/215111011-5489b059-5739-4623-bc5d-2f07b1ea8b15.png)

![image](https://user-images.githubusercontent.com/110994627/215111144-510d0cc8-3033-41ad-a331-6204873d24b6.png)

**Comment by raimuhello** [comment]
Ah I see, _that's_ how it works. I found it a bit confusing as I couldn't see any indicator on the card whether it was an alternate roll or not (players prefer to always roll damage manually only if they know it hits). But this already helps a ton.

One can still hope for a separate [Damage] button in the future so I won't have to remind my players every time when they inevitable forget to hold alt😄 

Thanks for all your work, really happy to have found a solid rolling module.
