### ISSUE TITLE
[BUG] Critical Hit Bonus Damage Is Not Rolled For Modified Crit Ranges

### ISSUE THREAD

**Issue by GameCrazed** [MangoFVTT/fvtt-ready-set-roll-5e#150]
**Description**
When a character (player or NPC) has a modified crit range (ie they crit on a 19 or 20) and this is configured in their weapon, the critical hit damage isn't rolled unless the dice roll was a 20 (see image below).  I've been able to replicate this on a bare-bones Foundry game (just this module + the 5e system module itself) and it seems to happen for all weapon types (melee weapon attack & ranged weapon attack). Any further details needed I'd be happy to provide.

![image](https://user-images.githubusercontent.com/7393464/216817017-3615f544-43dc-40cb-b360-c4c3164280dc.png)

**Steps to Reproduce**
1. Import a clean weapon from the built-in 5e item compendium.
2. Configure that weapon to crit on anything but a 20.
3. Roll attacks until you crit on something that isn't a 20 & see that the damage roll isn't rolling the extra crit dice.

**Versions**
 - Module: [1.4.1]
 - dnd5e: [2.1.4]
 - Foundry: [10.291]

**Other Modules**
None

**Comment by MangoFVTT** [comment]
Good catch! Seems this only was breaking when you have the setting to always roll 2 dice enabled. Should be fixed as of the next release 🙂
