### ISSUE TITLE
[BUG] Extra critical hit damage applied on every damage field.

### ISSUE THREAD

**Issue by Regateiro** [MangoFVTT/fvtt-ready-set-roll-5e#153]
**Description**
When setting Extra Critical Hit Damage, it is applied to every damage field instead of just once.
The screenshot shows the +7 extra critical hit damage applied on every formula on a critical when it should only appear once or on its own "extra critical damage" field.
![image](https://user-images.githubusercontent.com/5558459/217265281-818975cb-8a63-4b4e-bc87-5ceb602b3da9.png)

**Steps to Reproduce**
1. Add to any item with an attack roll an amount of extra critical hit damage.
2. Use the item until a critical hit is achieved.
3. Open the damage details in the card posted in the chat.
4. See error.

**Versions**
 - Module: [1.4.1]
 - dnd5e: [2.1.4]
 - Foundry: [10.291]

**Other Modules**
Tested with no other modules enabled.

**Comment by MangoFVTT** [comment]
Issue has been fixed and should be in next release.
