### ISSUE TITLE
[BUG] Module Shows in Other Systems

### ISSUE THREAD

**Issue by Vhostym-the-Sojourner** [MangoFVTT/fvtt-ready-set-roll-5e#158]
**Description**
The module shows for other systems outside of 5e. Can the manifest be updated to be restricted to the compatible system?

Thank you!

**Steps to Reproduce**
1. Go to Module Management in a non-5e system
2. The module displays

**Versions**
 - Module: [1.5.0]
 - Foundry: [10.291]

**Comment by MangoFVTT** [comment]
Issue is fixed and should be in next release.

**Comment by Vhostym-the-Sojourner** [comment]
Thank you!
