### ISSUE TITLE
[BUG] Equipment charges not consumed

### ISSUE THREAD

**Issue by aruguy** [MangoFVTT/fvtt-ready-set-roll-5e#162]
**Description**
Noticed some items are not automatically consuming charges upon use. Weapons and Consumable item types seem to function as expected, but Equipment types like Armor, Shields, and Trinket do not decrement charges correctly. Issue resolves when RSR is disabled.

**Steps to Reproduce**
1. Go to an actor sheet and create a new Equipment.
2. Select Equipment Type: Trinket
3. Assign 6/6 charges
4. Set Resource Consumption: Item Uses : new_item 1
5. Use new_item and observe if charges have been consumed.

**Versions**
 - Module: [1.5.1]
 - dnd5e: [2.1.4]
 - Foundry: [10.291]

**Other Modules**
A list of any other installed modules that might be related to the issue.

**Comment by MangoFVTT** [comment]
I suspect that you've not set up your item in the Roll Config to consume uses. You don't even need to set the Resource Consumption, simply set the number of charges, then inside the Quick Roll tab make sure that the "Uses" checkbox is set to true (see image below)

![image](https://user-images.githubusercontent.com/110994627/218252521-ba1be334-fea5-468e-b00d-6a5f97a69b8f.png)
![image](https://user-images.githubusercontent.com/110994627/218252533-98fa46a0-42fe-42c1-ad77-05f7ca59b902.png)
