### ISSUE TITLE
[BUG] Config and options not being passed through to item rolls

### ISSUE THREAD

**Issue by Zolmy** [MangoFVTT/fvtt-ready-set-roll-5e#163]
**Description**
Options and config passed to the item.use() or the new rsr5e.macro,rollItem() methods do not apply to the item roll. Perhaps this is me misunderstanding the current feature set of RSR or using it incorrectly. For example:

`item.use({ consumeSpellLevel: level, consumeSpellSlot: false}, {configureDialog: false})`
correctly skips the spell dialog and uses the provided value when used without RSR.

Neither the above nor 
`rsr5e.macro.rollItem(item.id, item.actor.id, { consumeSpellLevel: level, consumeSpellSlot: false, configureDialog: false})`  
seem to work when RSR is enabled.

Is there a way to correctly use these options with RSR or perhaps bypass RSR entirely for a specific roll made inside of a macro? 

**Versions**
 - Module: [1.5.1]
 - dnd5e: [2.0.3]
 - Foundry: [10.290]

**Comment by MangoFVTT** [comment]
This issue should now be fixed when using `rsr5e.macro.rollItem` and will be in the next release. Let me know if any config options aren't correctly being picked up :)
