### ISSUE TITLE
[FEATURE] active affects prioritisation

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#164]
**Is your feature request related to a problem? Please describe.**
At the moment you can only decide for active effects if they should apply to the selected token or a target. This isn't always usefull as some spells you want to apply to yourself, or let others apply to themselves, while others you want to apply to enemies. For example you want to haste yourself or slow some enemies

**Describe the solution you'd like**

**Describe alternatives you've considered**
It would be nice if the target would be prioritised, but if no target is selected then the selected token will gain the active affect. 

**Additional context**
Dfreds convenient effects has this as a feature.

**Comment by MangoFVTT** [comment]
You should be able to select the option that lets you apply effects to both selected and targeted tokens under the setting. When this is enabled, you can deselect the token to apply only to targets, and detarget tokens to apply only to selected. 

I know this isn't exactly what you asked for, but as a temporary fix it should be sufficient until I implement better decision making.

**Comment by MangoFVTT** [comment]
This feature has been implemented in the way of expanded apply options. It will be in the next release.
