### ISSUE TITLE
[BUG] Apply Effects button doesn't appear for upcast spells

### ISSUE THREAD

**Issue by KenGitsIt** [MangoFVTT/fvtt-ready-set-roll-5e#165]
**Cause of problem**
When a spell is upcast, Foundry replaces the spell item object with a clone of it.  The cloning process does not preserve the hasEffects property that had been previously added by the ItemUtility.ensurePropertiesOnItem() method.

**Solution**
There are a number of ways to deal with this, but I found this one straightforward and effective:
At the very beginning of the _addFieldEffectsButton() method in items.js, add the following line:
```ItemUtility.ensurePropertiesOnItem(item);```

**Comment by MangoFVTT** [comment]
Good catch, this has been fixed and will be in the next release.
