### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by stickas** [MangoFVTT/fvtt-ready-set-roll-5e#166]
This might not be a case of this mod but the magic items that are created/already exist through the Magic Items mod have spells or feats adjusted on them so you get them extra in your spellbook or feature page of the character sheet. Whenever I try to cast them they always cast once but appear 2 times as chat messages.
This is a created magic item
![image](https://user-images.githubusercontent.com/41856855/219955740-37f01d5d-bf9c-4437-966f-921a57ff703f.png)
and this is what happens when you click to cast the spell when someone has equipped a magic item (eg. wand of magic missiles)
![image](https://user-images.githubusercontent.com/41856855/219955694-cc3d9805-85f1-47da-891b-fd2391567a30.png)

**Versions**
 - Module: 1.4.1
 - dnd5e: 2.1.4
 - Foundry: 10.291

**Other Modules**
Magic items v3.0.0

**Comment by MangoFVTT** [comment]
Compatibility with other mods is always tricky. If Magic Items has functionality that outputs rolls to chat, then it can never be fully compatible with RSR. Combining roller modules is never a good idea.

**Comment by stickas** [comment]
I understand the compatibility. It's just that it somehow started happened after an update, which I didn't notice what was that. Also, I've used the older Better Rolls mod and it wouldn't occur there. Mostly for your info. I will try disabling one of the two and figure a workaround. Thanks anyway.
