### ISSUE TITLE
[FEATURE] Support for Convenient Effects

### ISSUE THREAD

**Issue by LuckierDodge** [MangoFVTT/fvtt-ready-set-roll-5e#167]
**Is your feature request related to a problem? Please describe.**

I really like using Ready Set Roll. The quick rolls and post-roll adjustments have really helped streamline things for my players. The one hiccup that we keep running up against is keeping track of stuff that modifies rolls, like Bardic Inspiration or True Strike. There's good plugins out there for this already, like DFreds Convenient Effects, but they rely on Midi-QOL's flags to do automatic roll modifications.

**Describe the solution you'd like**

I'd like to see RSR either add basic support for Midi flags (even just advantage/disadvantage would be a huge plus, to support stuff like exhaustion), or provide its own flag system that other developers like Convenient Effects could potentially target.

**Describe alternatives you've considered**

One obvious alternative is to go back to Midi as my defacto roller, but this has the drawback of being more complicated and less forgiving for when players make mistakes (which, in my experience, is fairly often, unless you commit to 100% automation).

**Additional context**

There's some discussion over in [Midi-QOL's repo](https://gitlab.com/tposney/midi-qol/-/issues/1098) about supporting RSR, but the devs seem less-than-enthusiastic about it, for what read to me as very fair reasons.

**Comment by krysztalzg** [comment]
+1, just supporting basic midi-qol flags for things like bonuses or adv/disadv would be great feature

**Comment by MangoFVTT** [comment]
The issue is that I don't personally use midi-qol and never have, so I have little familiarity with its features and the flags it creates. I can look into this but as with all things related to compatibility between Midi and RSR/BR, it's not a trivial thing and I expect implementing it will be complicated

**Comment by MangoFVTT** [comment]
@LuckierDodge Definitely! Anyone that wishes to implement bugfixes/features for this module can feel free to do so and I will review the PR as soon as possible. It would actually make development for me easier since I can't devote 24/7 of my time to this project 🙂
