### ISSUE TITLE
[FEATURE] Support the "Versatile" property for weapons

### ISSUE THREAD

**Issue by nivthefox** [MangoFVTT/fvtt-ready-set-roll-5e#170]
**Is your feature request related to a problem? Please describe.** I have a warlock using a Longsword, and he wants to be able to use it with two hands by taking advantage of the Versatile property.  Unfortunately, Versatile doesn't work with RSR for some reason. :(  Can you add support for this?

**Describe the solution you'd like** The weapon card should have "Damage" and "Versatile" as separate roll options, so that he can click the appropriate one.

**Describe alternatives you've considered** You could dynamically detect that they've got nothing else equipped in a hand except a Versatile weapon, and choose to use the versatile damage in that case, but that seems less flexible.

**Additional context** I love RSR. :) Thanks for the good work you do.

**Comment by MangoFVTT** [comment]
@nivthefox versatile does work! You need to enable it in the roll options for the item (see image). When the box is checked, "Damage" will roll the correct versatile dice. You can use the alt roll functionality to switch between versatile and non-versatile

![image](https://user-images.githubusercontent.com/110994627/223677088-e7a8bc4e-9e04-4e84-92d6-21a6bdb93f6c.png)
