### ISSUE TITLE
[BUG] Items with charges get destroyed even if "destroy on empty" is NOT checked

### ISSUE THREAD

**Issue by RaaviArda** [MangoFVTT/fvtt-ready-set-roll-5e#173]
**Description**
When rolling an item that has a limited number of charges the number of charges left gets decreased. When it reaches zero the item gets destroyed, regardless of setting "destroy on empty" being checked or not.
This applies to per-rest and per-day items as well.

**Steps to Reproduce**
1. Create an item with limited number of charges, make sure that "destroy on empty" is not checked
2. Give the item to PC actor
3. Roll the item until depleted
4. Item gets destroyed

**Versions**
 - Module: [1.5.1]
 - dnd5e: [2.1.5]
 - Foundry: [10.291]

**Other Modules**
Other modules disabled

**Comment by ronin-seven** [comment]
If you edit the item's Quick Roll configuration and deselect "Quantity" then the item will not be destroyed when it's depleted of charges.
![image](https://user-images.githubusercontent.com/47235915/232830982-6cb4ae79-470a-4f3b-ac4f-858818b5c3a7.png)
![image](https://user-images.githubusercontent.com/47235915/232831426-96f6f0f4-1037-4add-8c2a-1e3f4645009f.png)

**Comment by MangoFVTT** [comment]
@ronin-seven is correct. Destroy on empty has no effect in RSR since removing item quantity is handled by the quick roll config. If you set that up correctly it will work as intended.
