### ISSUE TITLE
[FEATURE] Separate the 'advantage/disadvantage' overlay toggle from 'apply damage/healing' overlay toggle

### ISSUE THREAD

**Issue by LtDerek** [MangoFVTT/fvtt-ready-set-roll-5e#174]
I really like being able to change a roll to advantage disadvantage after it's been rolled, but I don't want to have to worry about about accidently applying damage/healing if I misclick.

Could the settings menu be changed allow me to enable the damage automation separately to the advantage overlay?

**Comment by MangoFVTT** [comment]
This issue is now resolved in 3.0.0
