### ISSUE TITLE
[BUG] Not using the right image for Actors with wildcard images if set to use token image for quick rolls.

### ISSUE THREAD

**Issue by thrahistan** [MangoFVTT/fvtt-ready-set-roll-5e#175]
**Description**
If you setup the module for usage with Token images for quick rolls, you'll only get a missing image for actors with wildcard image settings instead of the set token image.

**Steps to Reproduce**
1. Setup an Actor with wildcard token.
2. In Ready Set Roll settings have set "Quick Roll Image Used" to "Token"
3. Roll any save or ability throw

**Versions**
 - Module: [1.5.1]
 - dnd5e: [2.1.5]
 - Foundry: [10.291]

**Other Modules**
None

**Comment by MangoFVTT** [comment]
This issue has been resolved and will be in the next release.
