### ISSUE TITLE
[FEATURE]: Adjust "apply damage" buttons to account for Heavy Armor Master

### ISSUE THREAD

**Issue by sapost** [MangoFVTT/fvtt-ready-set-roll-5e#177]
**Is your feature request related to a problem? Please describe.**
The buttons to automatically apply damage to selected tokens is a huge time-saver. However, it doesn't account for sources of damage reduction. Those are relatively rare in 5e, but one in particular comes up a lot for characters who have it: the Heavy Armor Master feat.

The feat Heavy Armor Master includes this benefit:
> When wearing heavy armor, bludgeoning, slashing and piercing damage you take from non-magical weapons is reduced by 3.

Currently, there's not a good way for an actor with Heavy Armor Master to apply the damage but reduce it by 3. 

**Describe the solution you'd like**
A couple ideas to consider:
- Automatically reduce damage when using the buttons (most complex)
  - Check whether the selected token has the Heavy Armor Master feat and has an equipped item classed as "heavy armor"
  - Check whether the damage source is of type bludgeoning, slashing, or piercing and is made by a non-magical weapon
  - If so, when clicking an "apply damage" button reduce the damage applied to the token by 3
    - It would also be great if the on-screen damage text indicated that the damage was reduced due to Heavy Armor Master
- Provide a modifier key when clicking an "apply damage" button (less complex, OK user experience but not very discoverable)
  - For example, hold Ctrl when clicking the button to deal "modified" damage (reduce by 3)
- Provide an optional prompt when clicking an "apply damage" button (less complex, worst user experience?)
  - Add a setting to prompt the user when clicking an "apply damage," such as `Reduce damage for Heavy Armor Master? y/n`

**Describe alternatives you've considered**
There's a workaround in the community-submitted macros list, but it's a fairly inelegant solution:
https://github.com/foundry-vtt-community/macros/blob/main/5e/heavy_armor_feat_workaround.js

It just gives you 3 HP back after taking damage, including some baseline checks to ensure that the restored HP is handled correctly when crossing max/min HP. There's no message indicating how much HP you're getting back or why. It also doesn't account for temporary HP at all, as a known deficiency.

**Additional context**
Sources of damage reduction like Heavy Armor Master are not super common in 5e, but for characters that have them, it comes up very often. Because RSR's otherwise _excellent_ auto-damage buttons don't support it, characters with Heavy Armor Master can't really use the buttons.

**Comment by sapost** [comment]
See also this extremely similar request from Better Rolls:
https://github.com/RedReign/FoundryVTT-BetterRolls5e/issues/219

**Comment by ZeroXNoxus** [comment]
@MangoFVTT I could take a look at this and implement the functionality in the '_calculateDamageResistances' function when the branch is accepted by you. Should be a fairly simple solution.

**Comment by MangoFVTT** [comment]
This feature has been implemented and will be in the next release.
