### ISSUE TITLE
[BUG] Configured Skills show a different a ability modifier than the one rolled.

### ISSUE THREAD

**Issue by 123mind123** [MangoFVTT/fvtt-ready-set-roll-5e#179]
**Description**
When you configure a skill to use a different modifier such as say Strength for Arcana it still says "Arcana (Intelligence)" when rolled.

**Steps to Reproduce**
1. Go to a normal character sheet.
2. Click on the cog next to a skill. EG: Deception or Nature
3. Set the "Ability Modifier" to something else and hit submit to save it. EG: Medicine to Intelligence
4. Then click on the skill to roll it. The modifier for the number will be right however the text will say "Medicine (Wisdom)".

**Versions**
 - Module: [1.5.1]
 - dnd5e: [2.1.5]
 - Foundry: [10.291]

This takes place with no other modules.

**Comment by CeaneC** [comment]
This one's a pretty quick fix, just need to change this line:
https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/blob/01c70f2784bab61021f9346af547498f4b40708b/src/utils/roll.js#L132
into this:
```js
    title += SettingsUtility.getSettingValue(SETTING_NAMES.SHOW_SKILL_ABILITIES) ? ` (${CONFIG.DND5E.abilities[actor.system.skills[skillId].ability]})` : "";
```

**Comment by MangoFVTT** [comment]
This has been fixed (thanks @CeaneC) and will be in the next release.
