### ISSUE TITLE
[FEATURE] Versatile roll on Ammunition item types

### ISSUE THREAD

**Issue by xXBulletJusticeXx** [MangoFVTT/fvtt-ready-set-roll-5e#183]
**Is your feature request related to a problem? Please describe.**
Normal Weapon items on character sheets are able to have 'Versatile' damage type selected (ticked box) in order to allow the OPTION to throw dice as versatile but Ammunition is not able to have this feature, even though there is a 'Versatile' Formula entry box with the item cards. There needs to be an option for RSR to enable Versatile roll type for Ammunition, as the Ammunition is what determines the damage when using an ammunition type weapon, not the weapon itself.

**Describe the solution you'd like**
Allow Ammunition (or anything rather) to be used with Versatile formula data field, without requiring 'Versatile' weapon type check box. 

**Describe alternatives you've considered**
Remove the pre-condition of an item being flagged as 'versatile' in order to roll the Versatile data field values.

**Additional context**
Can't get any pictures at the moment, but I can update with some tomorrow if need.

**Comment by MangoFVTT** [comment]
This feature has been implemented and will be in the next release.
