### ISSUE TITLE
v11 compatibility

### ISSUE THREAD

**Issue by dczwardCZAR** [MangoFVTT/fvtt-ready-set-roll-5e#190]
I'd love to see v11 compatibility for RSR.

**Comment by GonxGo** [comment]
Please my lord

**Comment by MangoFVTT** [comment]
It's in progress, waiting for other crucial parts to update first before it can be deployed properly 👍

**Comment by MangoFVTT** [comment]
Compatibility is in theory done and will be in the next release. I intend to implement some requested new features into this release as well (and simultaneously test for any other incompatibilities), so the updated release may be a few days longer still.

**Comment by MangoFVTT** [comment]
Compatibility with V11 has now been released with 2.0.0 🎉
