### ISSUE TITLE
[BUG] - Cannot click cards in chat to roll saves or checks

### ISSUE THREAD

**Issue by bradleyquinn** [MangoFVTT/fvtt-ready-set-roll-5e#191]
**Description**
When clicking a save or check from the chat using DnD5e 2.2 it throws an error

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/19616811/a986ba5c-e452-4d89-9aa7-700a6028776f)

commons.js:2158 Uncaught (in promise) TypeError: undefined. key.split is not a function or its return value is not iterable
[Detected 2 packages: ready-set-roll-5e, system:dnd5e]
    at Object.getProperty (commons.js:2158:24)
    at Localization.localize (foundry.js:6824:27)
    at CoreUtility.localize (core.js:28:26)
    at RollUtility.rollAbilitySave (roll.js:178:38)
    at Actor5e._actorRollAbilitySave (patching.js:96:40)
    at async Item5e._onChatCardAction (item.mjs:1682:11)

getProperty | @ | commons.js:2158
-- | -- | --
  | localize | @ | foundry.js:6824
  | localize | @ | core.js:28
  | rollAbilitySave | @ | roll.js:178
  | _actorRollAbilitySave | @ | patching.js:96
  | await in _actorRollAbilitySave (async) |   |  
  | dispatch | @ | jquery.min.js:2
  | y.handle | @ | jquery.min.js:2

**Versions**
 - Module: [1.5.2]
 - dnd5e: [2.2.0]
 - Foundry: [10.169]

**Other Modules**
A list of any other installed modules that might be related to the issue.

**Comment by DiceAndEasy** [comment]
I'm having this same issue.

**Comment by thejoester** [comment]
I am getting an error when trying to do any ability check or save from the character sheet as well. 
```
Uncaught (in promise) TypeError: key.split is not a function
[Detected 1 package: ready-set-roll-5e]
    getProperty http://<MYSERVER>/scripts/commons.js:2158
    localize http://<MYSERVER>/scripts/foundry.js:6824
    localize http://<MYSERVER>/modules/ready-set-roll-5e/src/utils/core.js:28
    rollAbilitySave http://<MYSERVER>/modules/ready-set-roll-5e/src/utils/roll.js:178
    _actorRollAbilitySave http://<MYSERVER>/modules/ready-set-roll-5e/src/utils/patching.js:96
```

**Comment by MangoFVTT** [comment]
This issue has been fixed and will be in the next release
