### ISSUE TITLE
Quick Roll Repeat Button does not reroll spells that are upcasted properly [BUG]

### ISSUE THREAD

**Issue by OxTailSafu** [MangoFVTT/fvtt-ready-set-roll-5e#194]
**Description**
Hello, thanks a lot for adding the reroll button! It's been a sorely missed feature for me so I'm glad to see it brought back. I noticed an issue with leveled spells where if you attempt to repeat the roll of an upcasted spell, it does not maintain the damage and instead casts it at base level.

**Steps to Reproduce**
1. On a spellcasters sheet, cast a spell that deals damage and has its damage increase on upcast (for instance, Fireball) and upcast it to a higher level.
2. Click on the repeat roll button outputted onto the chat to quickly cast it again.
3. Note that the damage returns back to its base level, and is not recasted using the upcasted value you did previously.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/123988485/304c8c75-0440-42aa-b7ee-8d0ba1214137)

In our games fireball does 7d6, but here at 7th level it deals 11d6 damage.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/123988485/02b01459-8ee8-451f-8efe-304ab7f1dbf3)

Here's fireball recasted using the reroll button, note how it's cast at 3rd level again instead of 7th level as intended.

**Versions**
 - Module: [1.5.3]
 - dnd5e: [2.1.5]
 - Foundry: [10.291]

**Comment by MangoFVTT** [comment]
Good catch, making a hotfix patch for this soon
