### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by ArcangeloD** [MangoFVTT/fvtt-ready-set-roll-5e#2]
Hello,

I actually cannot install the module for now, here's the error in the console  : 

[ready-set-roll-5e] Metadata validation failed for module "ready-set-roll-5e": The file "lib/libwrapper/shim.js" included by module ready-set-roll-5e does not exist

**Comment by MangoFVTT** [comment]
Closing this as a duplicate of [#3](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/issues/3)
