### ISSUE TITLE
[BUG] - Error on rolling to hit with weapons

### ISSUE THREAD

**Issue by bradleyquinn** [MangoFVTT/fvtt-ready-set-roll-5e#200]
**Description**
Rolling to hit with any melee weapon

**Steps to Reproduce**
1. Go to items
2. Click on roll
3. See error

foundry.js:11730 Uncaught (in promise) Error: undefined. Unresolved StringTerm 1. requested for evaluation
[Detected 2 packages: system:dnd5e, ready-set-roll-5e]
    at StringTerm.evaluate (foundry.js:11730:11)
    at DamageRoll._evaluate (foundry.js:9292:42)
    at async damageRoll (dice.mjs:186:3)
    at async Item5e.rollDamage (item.mjs:1370:18)
    at async _addFieldDamage (item.js:495:22)
    at async ItemUtility.getFieldsFromItem (item.js:75:13)
    at async _getItemRoll (roll.js:418:24)
    at async RollUtility.rollItem (roll.js:198:16)

**Versions**
 - Module: [1.5.4]
 - dnd5e: [2.2.1]
 - Foundry: [10.169]

**Comment by MangoFVTT** [comment]
@bradleyquinn I am unable to reproduce this error on my end, but it seems you are using a very old version of Foundry which is below the minimum supported version for RSR (10.274). I would advise updating Foundry first as it is likely dnd5e 2.2.1 will not work with older versions. If you wish to continue using that version, I would recommend downgrading dnd or RSR, or both.

Can you provide more details and screenshots of the specific item that is causing this error for you so I can make sure it does not happen on more modern versions of Foundry?

**Comment by bradleyquinn** [comment]
I apologize, we are running Foundry v10.291, I had forgotten we updated.  
Thank you for taking a look at this.  The strange thing is, this is only happening for 1 of the characters in our campaign.  When I made the bug, I thought it was for all of them, but it appears it is just 1.  I am wondering if maybe it was a bad DnD Beyond import or something.  
It does happen on every weapon that character has, I even added a few new random items and it fails for them too.  Not sure how I can dig in further to help.  I will keep poking around.

evaluate | @ | foundry.js:11730
-- | -- | --
  | _evaluate | @ | foundry.js:9292
  | await in _evaluate (async) |   |  
  | (anonymous) | @ | hooks.js:100
  | #call | @ | foundry.js:724
  | callAll | @ | foundry.js:681
  | use | @ | item.mjs:882
  | await in use (async) |   |  
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | rollItemWrapper | @ | roll.js:105
  | _itemProcessWrapper | @ | patching.js:149
  | _itemUse | @ | patching.js:111
  | 🎁call_wrapper | @ | libWrapper-wrapper.js:616
  | 🎁CONFIG.Item.documentClass.prototype.use#0 | @ | libWrapper-wrapper.js:189
  | _onItemUse | @ | base-sheet.mjs:1178
  | (anonymous) | @ | base-sheet.mjs:663
  | dispatch | @ | jquery.min.js:2
  | y.handle | @ | jquery.min.js:2

**Comment by MangoFVTT** [comment]
If it's just one character, then I would check specifically what's different about that character sheet. Check if there is any random string in the character's special traits that shouldn't be there, or an effect that shouldn't be there, or whatever else might be different from other characters that do not have the problem.

The worst case scenario if you cannot find a solution would be to recreate the actor from scratch. If there is corruption in the character sheet this would unfortunately be the only solution

**Comment by bradleyquinn** [comment]
Thank you for the idea, I just went full software engineer and stepped through your code until I was able to find exactly where the strange string was coming from.  A custom effect that I had built added an errant char into the int field for some reason.  Feel free to close this out, I appreciate it.

**Comment by MangoFVTT** [comment]
Glad to help! You can open a new issue if the problem (or anything like it) arises again.
