### ISSUE TITLE
[BUG] Ammunition Error

### ISSUE THREAD

**Issue by UGTem** [MangoFVTT/fvtt-ready-set-roll-5e#209]
**Description**
Using the ammunition property causes an error, resulting in no roll being made, ammunition being consumed and an error being thrown in the console.
The error in question being: 
item.js:158 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'quickVersatile')
[Detected 1 package: ready-set-roll-5e]
    at ItemUtility.getFlagValueFromItem (item.js:158:38)
    at _addFieldDamage (item.js:499:39)
    at ItemUtility.getFieldsFromItem (item.js:74:19)
    at async _getItemRoll (roll.js:530:24)
    at async RollUtility.rollItem (roll.js:305:16)

As noted in Steps to reproduce, this oddly only happens in one of my two worlds in which I was trying to reproduce it, while the module works fine in the other.

**Steps to Reproduce**
1. Open problem world
2. Go to any player or NPC with a weapon using ammunition (Given quick rolls are active)
3. Click weapon, ammo consumed, no roll is made

**Versions**
 - Module: [2.0.0]
 - dnd5e: [2.2.1]
 - Foundry: [11.299]

**Other Modules**
Tested with no other active modules, problem persists

**Comment by MangoFVTT** [comment]
This issue is fixed and will be in the next release.
