### ISSUE TITLE
[BUG] Regular damage is shown as "Bonus" when using Roll Damage Manually = Attacks Only

### ISSUE THREAD

**Issue by nschoenwald** [MangoFVTT/fvtt-ready-set-roll-5e#218]
**Description**
After switching to Roll Damage Manually = Attacks Only, all damage is marked as "Bonus" damage.

<img width="290" alt="image" src="https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/72390280/1b87af4a-ae19-42c8-ae9b-9ab2f1d099d9">

**Comment by MangoFVTT** [comment]
@nschoenwald I haven't been able to reproduce this on my end (see gif). Can you provide more details on the items this is happening for and exact steps you take to reproduce?

![test](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/e7ea4f48-a24a-40b1-aaa7-75881d695982)

**Comment by nschoenwald** [comment]
Okay, it does not occur every time, even for the same item. To illustrate that, I made a screen capture that you can view here : https://www.youtube.com/watch?v=4SZoaYe-guU

I only have Ready Set Roll, Socketlib and libwrapper active. The actor was originally imported via DDB Importer, but the same happens for other actors as well.

**Comment by MangoFVTT** [comment]
Ah, I suspect I know what is happening. It appears to be a weird interaction for items that have just been imported and never previously opened up with RSR, which causes them to be missing context flags, which in turn mistakenly use "Bonus" as the default context. I believe I should be able to fix this. 

Thanks for the info, it was very helpful to narrow down the culprit 👍

**Comment by nschoenwald** [comment]
You're welcome, I'm very happy to help! Keep up the awesome work!

**Comment by MangoFVTT** [comment]
Issue fixed and will be in the next release 🙂
