### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by raeschh** [MangoFVTT/fvtt-ready-set-roll-5e#220]
In the Settings there is a "Always Roll Damage manually" Option but even if I checked this, it only works for the account that is the GM and not for my Players.

**Comment by MangoFVTT** [comment]
@raeschh manual damage rolling is a CLIENT setting, not a WORLD setting. This means players set their preferences individually. The GM changing this setting will only change it for the GM's account. Players can do so the same way as the GM would, by logging into their account, going to settings -> Ready Set Roll, and changing the setting accordingly.

**Comment by nschoenwald** [comment]
You can use the Force Client Settings module to force this setting for all users.
