### ISSUE TITLE
[BUG] apply active effect button niche incompatibility with Concentration notifier

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#221]
**Description**
When using both this module and [Concentration Notifier](https://github.com/krbz999/concentrationnotifier) there can be some issues. for example when using the guidance cantrip (which has an active effect as well as require concentration). Concentration Notifier will apply an effect on the caster to indicate that the caster is concentrating on a spell, if the player then uses the apply active effect button to give the caster the benefit of the guidance active effect, it will delete the concentration effect, even when both effects have a different name.

**Steps to Reproduce**
1. get a new test world in foundry with just ready set roll and concentration notifier
2. get a character with a concentration spell that also applies a active effect like guidance or bless
3. (optionalL in concentration notifier settings check the box for Prepend Effect Labels, to give prepend concentration effects with 'Concentration' to distinguish them from other effects.
4. cast the spell, which gives you the concentration effect
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/defe98d8-271c-4a09-9af5-e9185d54eaf6)
5. apply the active effect from the spell using the apply active effect button in chat
6. result in losing the concentration effect.
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/43f46733-f825-430a-95bb-64757ba1d06b)

(the example images where done with a imported actor from the world i play in, but was a test world)

**Versions**
 - Module: [2.1.0]
 - dnd5e: [2.2.1]
 - Foundry: [11.302]

**Other Modules**
 - Concentration Notifier [11.0.3]

**Comment by OxTailSafu** [comment]
Ooph, yeah I just ran into this issue here and it really does make the active effects feature from RSR pretty hard to use properly for several buffs. I would love for this to be fixed as Concentrator (which really should be in the base system itself) is a must have module for automation.

**Comment by OxTailSafu** [comment]
@MangoFVTT Just curious should this issue be posted in the concentrator GitHub as well? I'm unsure if this is something that would be fixable on either end, but I just wanted to ask since there hasn't been any comments on this issue since.

**Comment by MangoFVTT** [comment]
@OxTailSafu I expect this is more an RSR issue, I just haven't gotten round to fixing it yet because I'm busy atm with resolving dnd5e 2.4.0 problems. I will look into this when things have settled on that front. You could feel free to post it on the Concentrator GitHub though in case an easier solution is possible from that end.

**Comment by MangoFVTT** [comment]
As of version 3.0.0 (which works with dnd5e 3.0), RSR no longer handles effect application and instead allows the system to do so internally. As such, this ticket is no longer related to RSR and can be considered resolved from the standpoint of this module.
