### ISSUE TITLE
[BUG] Damage type added via active effect not displayed

### ISSUE THREAD

**Issue by ZeroXNoxus** [MangoFVTT/fvtt-ready-set-roll-5e#225]
**Description**
When adding damage types via active effects to item damage rolls the added damage type is not seperately displayed in the generated chat card. This impedes the future feature of damage calculation based on damage types and can lead to confusion.

**Steps to Reproduce**
1. Add an active effect via 'Effects'
2. Set a damage type to a bonus die to weapon damage with the suffix [(damage type)]:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/29397572/d75c4c73-b729-43e8-bbe1-683aca389fa2)

Expected behaviour:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/29397572/74a9c923-463a-4b44-a504-fb41128036e9)

Current behaviour:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/29397572/a23ebe1b-db9e-4995-b6b0-d5545b0a4896)

**Versions**
 - Module: 1.5.4
 - dnd5e: 2.2.1
 - Foundry: 10.303

**Comment by MangoFVTT** [comment]
This isn't a bug, just a limitation of the dnd5e system. The [damage-type] tags don't actually do anything as far as the system is concerned, so adding that damage by an active effect simply adds it to the first damage type for the item. Short of rewriting the damage roller for dnd5e itself, or hacking in some interpreter for damage type tags, there isn't much I can do to fix this problem.
