### ISSUE TITLE
[BUG] "Automate damage modifiers" setting prevents healing for characters with Heavy Armor Master

### ISSUE THREAD

**Issue by sapost** [MangoFVTT/fvtt-ready-set-roll-5e#230]
**Description**
After release 2.1.1 introduced support for reducing damage via the Heavy Armor Master feat, healing no longer applies for characters with Heavy Armor Master. I suspect this is related to #216 because it only occurs when the **Automate damage modifiers** setting is enabled and only for characters with the Heavy Armor Master feat. Damage applies normally -- it's healing actions like Healing Word or Cure Wounds that don't function.

**Steps to Reproduce**
1. As the GM, enable the **Automate damage modifiers** setting for the game
2. For a character, add the Heavy Armor Master feat (i.e., from the #216 commit, have an item of type = "feat" and name includes "heavy armor master")
3. Use an ability with healing, such as Healing Word
4. Click the "apply healing to selected tokens" card button

Expected result: the character regains that number of hit points
Actual result: no effect, including no feedback in the UI

You can confirm this either by disabling **Automate damage modifiers** or by removing the Heavy Armor Master feat from the character. If you do either, healing applies as expected.

**Versions**
 - Module: 2.1.1
 - dnd5e: 2.2.2
 - Foundry: 11.305

**Other Modules**
n/a, no other conflicts observed

**Comment by MangoFVTT** [comment]
Issue has been resolved and will be in the next release.
