### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AlanDNelson** [MangoFVTT/fvtt-ready-set-roll-5e#233]
**Description**
A clear and concise description of what the bug is, along with any other context or screenshots about the problem.

**Steps to Reproduce**
1. Create an item with an alternate Quick-Roll set up.  In the example... I have a sword which does extra damage if a special ability is used.  When I use the default quick roll... everything works as expected.  When I use the alternate roll, it does show the Wisdom save, but the damage button does not work.
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/36895037/026d7b92-78ae-4bef-be37-c49fe6645aee)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/36895037/43a9049d-81d0-49ac-ba60-024d88672a88)

I get the following error message in the console:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/36895037/45a05416-1950-4475-b87c-8abbc27cd64c)

foundry.js:10353 Uncaught (in promise) Error: undefined. Roll.safeEval produced a non-numeric result from expression ""
[Detected 1 package: ready-set-roll-5e]
    at DamageRoll.safeEval (foundry.js:10353:13)
    at DamageRoll._evaluateTotal (foundry.js:10258:36)
    at DamageRoll._evaluateSync (foundry.js:10245:24)
    at DamageRoll.evaluate (foundry.js:10166:64)
    at item.js:535:88
    at Array.forEach (<anonymous>)
    at _addFieldDamage (item.js:533:21)
    at async ItemUtility.getSpecificFieldsFromItem (item.js:111:21)
    at async QuickRoll.upgradeToDamageRoll (quickroll.js:332:21)
    at async QuickCard._processDamageButtonEvent (quickcard.js:236:17)
    at async HTMLButtonElement.<anonymous> (quickcard.js:128:17)

**Versions**
 - Module: [2.1.2]
 - dnd5e: [2.2.2]
 - Foundry: [11.306]

**Other Modules**
I turned all of them off except lib wrapper.

**Comment by Krigsmaskine** [comment]
It seems like the item defaults to trying to roll versatile with Quick Rolls, but it's empty to it doesn't eval. If you add something in the versatile damage field, and uncheck it from the roll(s) you use, you can circumvent this for now.

**Comment by MangoFVTT** [comment]
This issue has been resolved and will be in the next release.
