### ISSUE TITLE
[BUG/Feature Request] ActiveEffect self-application with quick rolls

### ISSUE THREAD

**Issue by Krigsmaskine** [MangoFVTT/fvtt-ready-set-roll-5e#234]
**Description**
Truthfully I have a hard time distinguishing if this is supposed to work, and therefore is a bug, or if this is added solely by DAE and not implemented. 😄 

I'd like to have one of the quick rolls of items with effects (primarily spells) be automatically applied to themselves. Looking in the config window of the effect, there's these two checkboxes, but checking either of them with RSR stops the apply active effect button from working, no errors in console. This is for instances like Mage Armor, where 99% of the time the caster want to apply it to themselves, but for those time they don't, I want there to be an alternate roll, or vice versa.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/39592771/30062b32-344c-4a59-92ad-1188a187be17)

**Steps to Reproduce**
1. Create an item with an ActiveEffect.
2. Have two+ effects on the item.
3. Make one an alternate roll with one of the checkboxes above selected.
4. Apply Active Effect button stops working.

**Versions**
 - Module: 2.1.2
 - dnd5e: 2.2.2
 - Foundry: 11.305

**Comment by MangoFVTT** [comment]
Other forms of automation rarely interact well with RSR's own automation features. The best option is to use the Apply Active Effects button from the RSR chat card to apply the effects to yourself since I doubt DAE is picking up the RSR roll  object correctly in order to do its own automation.
