### ISSUE TITLE
[FEATURE] Support for Star Wars 5e

### ISSUE THREAD

**Issue by fastjimmy01** [MangoFVTT/fvtt-ready-set-roll-5e#237]
**Is your feature request related to a problem? Please describe.**
The request is tied to an inability to use the module with the Star Wars 5e System in Foundry. 

**Describe the solution you'd like**
The Star Wars 5e system is a hack of the standard D&D 5e system, but uses the same basic logic behind it.

Below is the link to the GitHub project page:

https://github.com/sw5e-foundry/sw5e

**Describe alternatives you've considered**
Attempted to use modules that are more system agnostic, like Midi QOL, but none of these modules have the same level of polish and functionality that Ready, Set, Dice does

**Additional context**
None - unsure what level of work it would take to make this compatible, but in the hope that it is an easy lift, I would love to see this in the future.

**Comment by MangoFVTT** [comment]
RSR is tightly coupled with the DND5e system unfortunately, so making it compatible with another system would constitute a likely complete rewrite of the module, which is not within the scope of this project.

That being said, the code for RSR is open source, and I would be happy to advise anyone that wanted to take a shot at making it compatible for other systems, I just don't have the time or inclination to do so myself.
