### ISSUE TITLE
[FEATURE] Flags for active effects on damage bonusses changes

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#238]
**Is your feature request related to a problem? Please describe.**
At the moment if you were to have an active effect that adds for example an extra 1d4[fire] damage, it will add this to the inline roll, but it wont calculate it properly with the newer improved apply damage  buttons. it would be nice if you could make it roll that extra damage correctly.
This for example doesnt work that well with the newer improved apply damage buttons:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/2eb8122e-4719-4536-873b-00ee6f619ac6)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/9b2e3c37-6bea-42f1-a0df-68e05571223a)

**Describe the solution you'd like**
If an active effect adds extra damage to a roll that it would read the damage type from the argument and if its one of the standard damage types, add a extra damage box that has the correct roll and output. if it does have something to describe the damage but isnt one of the standard damage types, have it add it to the context menu. Regarding the context menu, maybe also put in the name of the effect that gives the extra damage.
It would be nice if it looked something like this:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/9c94c6f7-cf17-4289-956b-e65362f70e1b)

**Describe alternatives you've considered**
I mean Midi probably has something for it, but that shit doesn't look nearly as good as this module, doesn't have the alternate rolls feature which is a great feature and overall is too automated

**Additional context**
tested the active effect and inline roll stuff with [Radiant] as well, so capitalisation doesn't matter right now.

**Comment by MangoFVTT** [comment]
As explained in #225 before, this is a limitation of the dnd5e system. The [damage-type] tags don't actually do anything as far as the system is concerned, so adding that damage by an active effect simply adds it to the first damage type for the item. Short of rewriting the damage roller for dnd5e itself, or hacking in some interpreter for damage type tags, there isn't much I can do to fix this problem.
