### ISSUE TITLE
[BUG] Quick rolling ability test results in error

### ISSUE THREAD

**Issue by rthill91** [MangoFVTT/fvtt-ready-set-roll-5e#241]
**Description**
Clicking an ability check or save modifier to roll that stat results in the following error. There is no alert or other obvious result of the action.
```
Ready Set Roll | Quick rolling ability test from Actor 'Bandit'.
commons.js:2158 Uncaught (in promise) TypeError: key.split is not a function or its return value is not iterable
    at Object.getProperty (commons.js:2158:24)
    at Localization.localize (foundry.js:6824:27)
    at CoreUtility.localize (core.js:28:26)
    at RollUtility.rollAbilityTest (roll.js:154:38)
    at Actor5e._actorRollAbilityTest (patching.js:81:40)
```

**Steps to Reproduce**
1. Open a character sheet
2. Click an ability modifier (str for example)
3. See described failure

**Versions**
 - Module: [1.5.4]
 - dnd5e: [2.2.2]
 - Foundry: [10.303]

**Other Modules**
Issue is observed with only RSR enabled

**Comment by rthill91** [comment]
Idk what to make of this, but I backed everything up, upgraded my foundry server to v11 had other unrelated issues and restored my backup and this issue is resolved.

At this point I don't think I have anything reproducible so I'm just gonna close this.

**Comment by bobby-driggs** [comment]
In case anyone else land here, I saw the same error on an ability check and for me I was stuck on Ready Set Roll version 1.5.1.

I couldnt upgrade to 1.5.4 automatically, (the latest before v11), so I had to manually do it from the module.json from the 1.5.4 release.

Upgrading to 1.5.4 fixed my issue!
