### ISSUE TITLE
[BUG] Reliable Talent doesn't work correctly with advantage or disadvantage

### ISSUE THREAD

**Issue by Aldarana** [MangoFVTT/fvtt-ready-set-roll-5e#243]
**Description**
When rolling with advantage or disadvantage the rogue feature Reliable Talent adds 10 to the larger die, applies bonuses and then gives that as the result of the roll instead of setting the value of the die to 10. 

**Steps to Reproduce**
1. Go to any character sheet.
2. Toggle on the Special Trait "Reliable Talent"
3. Roll any skill that the character has proficiency in with advantage/disadvantage
4. Wait to get a dice roll below 10
5. See error

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/37982657/11a34ba8-2f93-43d7-8be4-86744ad640e1)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/37982657/d09033d3-7109-49b8-813e-a48f2554fc28)

**Versions**
 - Module: [2.1.2]
 - dnd5e: [2.2.2]
 - Foundry: [11.306]

**Other Modules**
None. The issue happens with only Ready Set Roll and it's dependencies enabled.

**Comment by Aldarana** [comment]
I had some free time so I tired finding a fix for this. I think this should be a fix but I'm not _that_ familiar with js and the Foundry API so this might break something else. I didn't find anything broken when testing but ¯\_(ツ)_/¯

In `src/utils/render.js` the while loop on line 207 would iterate out of bounds on the `d20Rolls.results` object when a reliable talent roll happened and throw an error. I replaced it with the below for loop and if statement to prevent going out of bounds.
```js
for (let j = i; j < d20Rolls.results.length; j++) {
	if (d20Rolls.results[j].rerolled) {
		tmpResults.push(d20Rolls.results[j]);
	}
};
```

On line 229 storing the `tmpResults` object when it was contains more than result into the `baseTerm` objects seems to cause the `Roll.fromTerms()` function to evaluate the roll incorrectly. This seems to have been where the +10 was getting added. Rather than storing `tmpResults` I changed it to just store the `d20Rolls.results[i]`, this seems to fix most of the problems.
```js
const baseTerm = new Die({
	number: 1,
	faces: 20,
	results: [d20Rolls.results[i]],
	modifiers: d20Rolls.modifiers
});
```

From what I can tell with these changes everything function correctly. There's still a minor visual bug when rolling where the winning "result" isn't always highlighted correctly.
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/37982657/cf41bda2-2ca2-4780-8239-ea6621954902)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/37982657/f5f4d790-8fd9-417c-9ea9-454e6af73b24)
I think this only happens when the 2nd of the two rolls triggers reliable talent.

**Comment by oestred** [comment]
The new in my game noticed the same reliable talent error last night. Adding 10 to the roll itself so the outcome is much higher.
Would love to see a fix in a coming update of the module.

Thank you

**Comment by MangoFVTT** [comment]
Investigating this in conjunction with #250 which seems to be related

**Comment by MangoFVTT** [comment]
This issue has been resolved and will be in the next release.
