### ISSUE TITLE
[BUG] RSR doesnt work properly for module Harvester (Better Harvesting and Looting)

### ISSUE THREAD

**Issue by Hranolky1** [MangoFVTT/fvtt-ready-set-roll-5e#245]
**Description**
When using Harvester module with RSR, sometimes it wont loot the corpse (goblin), and the action must be used multiple times, before it works and gives the player the looted money. Harvesting for body parts doesnt work at all, it will roll for the needed check, but the harvested part isnt rolled on the roll table and then given to the player. When RSR is turned off, Harvester works as it should.

Harvester Module: https://github.com/OhhLoz/Harvester

**Steps to Reproduce**
For Loot
1. Target the corpse of Goblin (must be set to 0hp and marked as dead).
2. Click on Loot action Feature. (sometimes works sometimes it doesnt)
3. See error, when it doesnt loot for money
![obrazek](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/142675243/18e04bf3-f920-4c67-8a88-88b6f78e23fe)

For Harvesting
1. Target the corpse of Goblin (must be set to 0hp and marked as dead).
2. Click on Harvest action Feature.
3. There is no Error and it looks like it should work properly. The check is rolled too, but there is no random harvesting done.

**Versions**
 - Module: [2.1.2]
 - dnd5e: [2.3.0]
 - Foundry: [11.307]

**Comment by MangoFVTT** [comment]
As of version 3.0.0 (which works with dnd5e 3.0), RSR no longer overrides the dnd5e.useItem function (instead using hooks), and should therefore not cause any interference with Harvester.
