### ISSUE TITLE
[FEATURE] Call alternate rolls from rsr5e.macro.rollItem

### ISSUE THREAD

**Issue by Krigsmaskine** [MangoFVTT/fvtt-ready-set-roll-5e#246]
**Is your feature request related to a problem? Please describe.**
For features that are technically two features (in coding terms), such as Hunter's Mark, where you first use you have Concentration and you use a spell slot, until you're done with the spell slot, you just want to roll the damage without any of the usage/resource consumption. 

**Describe the solution you'd like**
It would be nice to either be able to call Item5e#use with the regular config or the rsr5e macro to trigger alternate roll(s) immediately, so you can make one not consume resources. 

**Describe alternatives you've considered**
So far, my players just alt+click, but I'd like to remove that alt contingency by coding a one-click macro for them. :p

**Comment by MangoFVTT** [comment]
@Krigsmaskine This is already possible :) You can simply add `isAltRoll: true` as part of the options object of the macro call. For example: `rsr5e.macro.rollItem('meXv1Ph5xKDaVjvy', 'oQjlf962sBl4Jwir', { isAltRoll: true })`
