### ISSUE TITLE
[BUG] Rerolling individual dice from chat card causes unwanted expansion

### ISSUE THREAD

**Issue by crash1115** [MangoFVTT/fvtt-ready-set-roll-5e#247]
**Description**
Rerolling individual dice from a chat card causes all rolls in that chat card to expand. This is true for attack rolls and damage rolls for weapons and spells. It happens before or after applying retroactive adv/disadvantage/crits via the -/+ buttons.

**Steps to Reproduce**
1. Roll a weapon from a character sheet (this is the Flame Tongue Greatsword right out of the SRD items compendium)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/41387713/2d97c930-948e-439b-843e-aa9af3a028e0)

2. Expand damage roll
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/41387713/27eb0801-5559-4755-aae0-0b172a73a168)

3. Click a die to reroll
4. Observe that reroll has been made, but now attack roll and other damage rolls have been expanded
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/41387713/51c14220-383c-4b27-8ad3-b80fda7fd82c)

**Versions**
 - Module: 2.1.2
 - dnd5e: 2.3.1
 - Foundry: 11 build 306

**Other Modules**
Only other active mod is libwrapper.

**Comment by MangoFVTT** [comment]
This is unfortunately behaviour from core foundry's chat card system and cannot be overridden.
