### ISSUE TITLE
[BUG] Unable to load valid manifest data, cannot read properties of undefined

### ISSUE THREAD

**Issue by Perogy** [MangoFVTT/fvtt-ready-set-roll-5e#249]
**Description**
Upon installation attempt of ready set roll I get the error "Unable to load valid manifest data, cannot read properties of undefined". Is this a versioning issue? I tried prior versions as well.

![Screenshot 2023-10-11 235419](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/11309041/660e54ec-662c-4e11-826c-cba129811730)

**Steps to Reproduce**
1. Open foundry config
2. Install Ready Set Roll from the module list

**Versions**
 - Module: 2.1.2
 - dnd5e: 2.3.1
 - Foundry: 11.313

**Comment by MangoFVTT** [comment]
@Perogy I'm not able to reproduce this issue on my end. Installation works as expected both via the module list and via manual installation. Are you still having this issue?

**Comment by Sevaarcen** [comment]
Just jumping in here -- I had the same issue across different versions of the module (installing from the module list, directly from URL, and via a local file), dnd5e system, foundry, and nodejs.

I was able to fix the issue by completely removing the foundry installation directory (not the data directory, just the program data itself) and re-installing. It appears there must be some conflicting file left over from a foundry update-in-place that causes this issue. No idea why this module seems particularly effected by whatever bug is causing this.

**Comment by Perogy** [comment]
> Just jumping in here -- I had the same issue across different versions of the module (installing from the module list, directly from URL, and via a local file), dnd5e system, foundry, and nodejs.
> 
> I was able to fix the issue by completely removing the foundry installation directory (not the data directory, just the program data itself) and re-installing. It appears there must be some conflicting file left over from a foundry update-in-place that causes this issue. No idea why this module seems particularly effected by whatever bug is causing this.

Wow THANKS! I just deleted the whole installation directory and reinstalled and now it works. You're a lifesaver.

**Comment by MangoFVTT** [comment]
@Sevaarcen Good to know, will keep that in mind for anyone with the same issue in future 👍
