### ISSUE TITLE
[BUG] RSR5e throws exception with Reliable Talent Feature 

### ISSUE THREAD

**Issue by baerchen91** [MangoFVTT/fvtt-ready-set-roll-5e#250]
**Description**
When Reliable Talent is active and min condition is fulfilled, an exception is thrown. (1d20min10)

Uncaught (in promise) TypeError: d20Rolls.results[i] is undefined
[Detected 4 packages: ready-set-roll-5e, lib-wrapper, token-action-hud-dnd5e, token-action-hud-core]
    _renderMultiRoll render.js:207
    renderFromField render.js:55
    _render quickroll.js:425
    toMessage quickroll.js:173
    _getActorRoll roll.js:536
    rollSkill roll.js:188
    _actorRollSkill patching.js:71
    call_wrapper libWrapper-wrapper.js:616
    rollSkill#0 libWrapper-wrapper.js:189
    #Z token-action-hud-dnd5e.min.js:1
    #Q token-action-hud-dnd5e.min.js:1
    doHandleActionEvent token-action-hud-dnd5e.min.js:1
    handleActionEvent roll-handler.js:50
    handleAction token-action-hud.js:364
    ut token-action-hud.js:445
    jQuery 2
        dispatch
        handle

**Versions**
 - Module: 2.1.2
 - dnd5e: 2.3.1
 - Foundry: 11.309

**Comment by MangoFVTT** [comment]
This issue has been resolved and will be in the next release.
