### ISSUE TITLE
Reliable Talent not working with tools [BUG]

### ISSUE THREAD

**Issue by OxTailSafu** [MangoFVTT/fvtt-ready-set-roll-5e#257]
**Description**
Reliable Talent allows any character with this feature to treat a skill/tool check that is 9 or lower as a 10 as long as you're proficient. This doesn't appear to work on tools for some reason. As you can see in the image, it doesn't appear to sport the same 1d20min10 part versus the skills. There does not appear to be any error message as far as I can see.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/123988485/931f950e-96de-4c26-9db1-918b718b6e86)

**Steps to Reproduce**
1. Go to your sheet and make a roll with a tool.

**Versions**
 - Module: [2.1.3]
 - dnd5e: [2.3.1]
 - Foundry: [11.313]

**Comment by MangoFVTT** [comment]
@OxTailSafu this is actually a bug with the core dnd5e system. As you can see in this screenshot, the default foundry roll for tools also ignores Reliable Talent. RSR picks up the formula from the default roll, so if that roll doesn't add the min10, RSR won't have it either. You should report this as an issue on the dnd5e system repository and RSR should handle it accordingly.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/25b9ded3-8a1a-4ceb-a37c-43eaffd61672)
