### ISSUE TITLE
[FEATURE] Only visual option/Midi-QOL compatibility?

### ISSUE THREAD

**Issue by ryanfp** [MangoFVTT/fvtt-ready-set-roll-5e#258]
I don't want to harp on this, but an option for Midi-QOL compatibility would be amazing. Allowing us to use this mod with the better chat message aesthetics with the automation of Midi-QOL would be perfect. Or simply an option to disable all but visual aspects of the module. 

Thanks!

**Comment by MangoFVTT** [comment]
Closing this as a duplicate of #244.
