### ISSUE TITLE
[FEATURE] Reliable Talent-like flags

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#259]
**Is your feature request related to a problem? Please describe.**
Some features allow you to treat rolls of 9 or 7 etc and lower as a 10 or 8 etc (see Inquisitive Rogue's Ear for Deceit, College of Eloquence Bard's Silver Tongue and Clockwork Soul Sorcerer's Trance of Order) and some allow you to reroll on a certain roll, but keep the newer result like Halfling's Lucky.

**Describe the solution you'd like**
A set of flags for each skill, saving throw as well as for attacks to either have a minimum that can be rolled or/and allows for a reroll as well as a value tied to those that can be adjusted on a per skill/saving throw/attack type basis (to either set up the features above or allow for custom ones)

**Describe alternatives you've considered**
Either use the reliable talent flag or roll normally and keep track of it manually.

**Additional context**
Just that i love the work so far.

**Comment by MangoFVTT** [comment]
The functionality for adding additional generic flags to rolls is outside the scope of RSR, and should instead be brought up with the system developers as a feature request on their own github issues page: https://github.com/foundryvtt/dnd5e/issues
