### ISSUE TITLE
Retrieving and Initialising Quick Card Action Buttons causes lag

### ISSUE THREAD

**Issue by schnoodly** [MangoFVTT/fvtt-ready-set-roll-5e#260]
### **Description:**
Selecting a token causes lag as RSR acquires quick card data. On the player end, this is a minor annoyance, but as a GM this really slows down gameplay with controlling multiple tokens.

I expect this is an extremely necessary step, but I ask regardless: is this something that can be addressed?

### **Steps to Reproduce**
When selecting a token, there is ~1-2 second lag that freezes the whole canvas momentarily. Checking through the console, it lines up exactly when this debug message occurs:

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/20142693/29930456-501a-4ae7-bc07-7bb9d372ceed)

Deleting the chat and trying to select tokens "fixes" the issue, experiencing no lag.

### **Versions**
- Module: [2.1.3]
- dnd5e: [2.3.1]
- Foundry: [11.315]

**Comment by MangoFVTT** [comment]
@schnoodly Not sure how you're experiencing this when selecting tokens. RSR content for chat messages is only initialised at 2 points:

1. For a **single** RSR chat message when it is created during play.
2. When Foundry is first opened, for all existing RSR chat messages.

The reason for this is exactly to avoid this spike of lag that you are experiencing. That debug message specifically has nothing to do with tokens, so if you really are getting it exactly at the lag spike then it is a strange case. My first instinct is that you have some other module that does things to chat messages? Or perhaps causes the chat log to redraw/draw later than it should?

**Comment by schnoodly** [comment]
Very possibly something like DF Chat Enhanced (or whatever it's called). I'll try to check on it tomorrow and let you know.

**Comment by schnoodly** [comment]
Well, I returned to test things earlier today, and despite changing nothing (except updating modules), the issue seems to have fixed itself on that end. There seems to be a new issue that causes hang when selecting tokens as GM now, but I don't think it's this module, this time.
