### ISSUE TITLE
[BUG] Package manifest error with Foundry version 11 build 315

### ISSUE THREAD

**Issue by akerfoot** [MangoFVTT/fvtt-ready-set-roll-5e#261]
**Description**
Attempting to install Ready Set Roll 5e with version 11 build 315 of foundry yields the following error:
`Error: Unable to load valid module manifest data from "https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/releases/download/release-2.1.3/module.json" Cannot read properties of undefined (reading '0')`

**Steps to Reproduce**
1. Install latest stable version of Foundry (Version 11 Build 315)
2. Run Foundry
3. Click Add-on Modules
4. Click Install Module
5. Search for Ready Set Roll
6. Click Install

**Versions**
 - Module: [2.1.3]
 - dnd5e: [2.3.1]
 - Foundry: [11.315]

**Comment by MangoFVTT** [comment]
@akerfoot this appears to be the same issue as described here: https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/issues/249 

Please attempt the solution mentioned in the comments there first, and close the ticket if that resolves your problem
