### ISSUE TITLE
[BUG] Extra critical dice are actually maxed out when using the system's Critical Damage Maximize Dice

### ISSUE THREAD

**Issue by kaelad02** [MangoFVTT/fvtt-ready-set-roll-5e#262]
**Description**
_I'm filing this on behalf of a Discord user who initially reported it. I'm also leaving the strength modifier out of my examples to make it simpler._

The dnd5e system has a setting called Critical Damage Maximize Dice. According to the hint, it'll maximize the value of the base damage dice. For example, a crit with a Longsword would change from `2d8` to `1d8 + 8`. The `1d8` part is the critcal damage die and the `+ 8` is the maximized base damage.

There's also something in the Special Traits on the character sheet called Melee Critical Damage Dice. It's used for the Half-Orc's Savage Attacks feature and Barbarian's Brutal Critical. It adds extra weapon dice when you critically hit. For example, a crit with a Longsword and 1 bonus die would roll `3d8` damage.

Now with both of those enabled, a Longsword should do `2d8 + 8`. The `2d8` is the critical damage dice, one for a normal crit and a second die for the bonus die. The `+ 8` part is the maximized base damage. That's what happens without RSR enabled, but with RSR enabled, it's maximizing the critical damage dice, not the base dice.

Here's what happens with just the Critical Damage Maximize Dice system setting enabled. You can see one die is rolled and the other is maxed out.
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/19502084/50bb5764-1896-4551-a11e-75d37d8a89b8)

Here's what happens when you add one bonus critical die. You can see two d12s maxed out. It appears that it's maxing out the critical damage dice, not the base dice.
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/19502084/f1e229f1-c5fe-4720-8aae-2b23aecf38e6)

**Versions**
Sorry, I forgot to ask what versions they were using.

**Comment by MangoFVTT** [comment]
This issue has been resolved and will be in the next release.
