### ISSUE TITLE
[FEATURE] Integrate with Dice So Nice

### ISSUE THREAD

**Issue by bklick** [MangoFVTT/fvtt-ready-set-roll-5e#27]
I would like this module to function with Dice so Nice, so that clicking an item, skill, etc, will cause the 3D dice to roll. Right now, some dice roll, but D20s do not. I am unsure if it is a bug that some dice roll, or a bug that some dice do not roll - but it is not consistent.

I love the direction of this module so far! Thank you for taking up such a big project.

**Comment by MangoFVTT** [comment]
This issue is resolved by PR #26 and will be in the next feature release, keep an eye out for the update 🙂

**Comment by MangoFVTT** [comment]
@bklick Dice So Nice compatibility is now fixed with Release 1.2.0 and D20 rolls should roll 3D dice correctly.
