### ISSUE TITLE
[BUG] Spells without attack roll but only damage rolls have wrong damage formula and cant be casted on higher level

### ISSUE THREAD

**Issue by vkinco** [MangoFVTT/fvtt-ready-set-roll-5e#271]
**Steps to Reproduce**
1. Go to any spell without attack roll, which consume spell slot and which has higher level effect (healing word, fireball, etc.)
2. Try to use it with any spell level slot
3. It always use damage formula of base level +1 (healing word do 2d4 healing on both 1st and 9th level spell slots, fireball do 9d6 damage, ...)

**Versions**
 - dnd5e: 2.4.0
 - Foundry: 11.315

**Only libwrapper and ready-set-roll-5e are active, no any other module**

**Comment by MangoFVTT** [comment]
This issue has been resolved and will be in the next release.
