### ISSUE TITLE
[BUG] Pact Magic not working

### ISSUE THREAD

**Issue by Brynhold** [MangoFVTT/fvtt-ready-set-roll-5e#277]
**Description**
When casting spells using Pact Magic, a slot is consumed, templates can be placed, but no message appear in chat that displays the magic being used, no rolls etc, as if you didn't use it at all. Other spells function normally. 
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/89525943/b0abfcd8-7fa4-437b-8be4-ba4ae4023003)

**Versions**
 - Module: [2.1.5]
 - dnd5e: [2.4.0]
 - Foundry: [11.315]

**Other Modules**
Lib wrapper

**Comment by MangoFVTT** [comment]
Issue has been resolved and will be in the next release.
