### ISSUE TITLE
[BUG] Some items will not roll and error out in the console 

### ISSUE THREAD

**Issue by Mistajaymes** [MangoFVTT/fvtt-ready-set-roll-5e#281]
**Description**
Specific items do not roll hit or damage, while most items have no issue at all

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/126446885/991ae052-cb42-4a37-8de0-9a776809b887)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/126446885/8aa62820-4bba-49b3-9cd5-c92599855775)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/126446885/98efc1ad-481d-4d3a-9c47-d700d4a321d9)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/126446885/1c3d9dda-715e-4449-b97d-f0c44cbdcfbd)

**Steps to Reproduce**
1. Add longsword or other problem item to character inventory.
2. Click to roll the attack and it performs as expected the first time.
3. subsequent rolls error out

**Versions**
 - Module: [2.1.5]
 - dnd5e: [2.4.0]
 - Foundry: [11.315]

**Other Modules**
A list of any other installed modules that might be related to the issue.

**Comment by MangoFVTT** [comment]
@Mistajaymes I need more information on the specific items throwing errors in this case, such as a look of their item details, or even better a full export file of the items so I can look through their data.

**Comment by Mistajaymes** [comment]
[fvtt-Item-longsword-Woi5kp3l7bn2YpWO.json](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/files/13574791/fvtt-Item-longsword-Woi5kp3l7bn2YpWO.json)

here's the longsword item export

**Comment by MangoFVTT** [comment]
@Mistajaymes I wasn't able to reproduce your errors with the item you gave me, which leads me to suspect it may be an item specific issue.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/bc1ce314-9a57-44dc-a274-ea4814c42d7b)

As a potential fix: first try updating RSR to the latest version, and then try recreating or exporting & re-importing the items that cause problems for you. If that still fails, please provide more items that are failing so I can compare the JSON data.
