### ISSUE TITLE
[BUG] Apply Damage buttons do not appear for rolls made via Damage Enrichers

### ISSUE THREAD

**Issue by CeaneC** [MangoFVTT/fvtt-ready-set-roll-5e#282]
**Description**
When making use of the new [Damage Enrichers](https://github.com/foundryvtt/dnd5e/wiki/Enrichers#damage-enrichers) feature from dnd5e 2.4.0, the rolls do not show the buttons to apply damage when hovering over the roll result.

**Steps to Reproduce**
1. Type `[[/damage 1d6 fire]]` in chat (or a journal, item description, rolltable description, etc)
2. Click on the dice result
3. Hover over the roll result
4. See that the apply damage buttons are not present

**Versions**
 - Module: [2.1.6]
 - dnd5e: [2.4.0]
 - Foundry: [11.315]

**Screenshot**
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/43473593/c906bc54-dcf5-4b45-ba46-2b586efbbf2e)

**Comment by MangoFVTT** [comment]
Damage enrichers are basically direct chat rolls. They cannot be intercept by RSR, and therefore the chat card is not an RSR chat card, so no damage overlay can be added,
