### ISSUE TITLE
[BUG] Ranged weapons error out & double use resources

### ISSUE THREAD

**Issue by Its-Scottih** [MangoFVTT/fvtt-ready-set-roll-5e#284]
**Description**
Whilst using RSR I have noticed that many of my ranges weapons (Crossbows and Bows) seem to use 2 arrows/bolts instead of 1 and on top of this do not roll into the chat box. I have imported via SRD & DNDBeyond but it makes no difference.

**Steps to Reproduce**
1. Import a Short bow/Longbow/Crossbow
2. Equip the item and use it
3. 2 Ammunition vanish, no roll in chat log

Here is my console log
![Screenshot 2023-12-17 014634](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/128651034/8b988c21-a9ea-4913-aa2a-0bfa5496c050)

I turned off RSR and was able to roll the bows and damage. It only used 1 ammunition

**Versions**
 - Module: [4.1.6]
 - dnd5e: [2.4.0]
 - Foundry: [11.315]

**Other Modules**
In a fresh new world there was no issue with the error out but it still used double resources with only RSR Active
![Screenshot 2023-12-17 014634](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/128651034/9af8b7f1-daff-4d5d-bcc4-b844b54a2b24)

As such I cant say about any other modules that may be conflicting

**Comment by bluewarbler** [comment]
Seconding this issue. I did some investigation, and if you uncheck the "Resource" box in the ranged weapon's Quick Roll section, it only consumes one resource. 

If the "resource" box is checked, it will always consume one more use of ammunition than the number in the "Resource Consumption" box, unless the number is zero, in which case it will consume two. It will seemingly consume whatever quantity of resource is given in the "resource consumption" box when you click the item, and then consume one resource when the item is rolled. It is possible to set it to consume no resources (i.e. for the [firearm reload macro](https://www.reddit.com/r/FoundryVTT/comments/s00u44/macro_to_handle_reloading_guns/)), but only by setting its resource consumption to -1, in which case it will add one resource when clicked and then promptly consume one resource when it rolls.

**Comment by Its-Scottih** [comment]
> Seconding this issue. I did some investigation, and if you uncheck the "Resource" box in the ranged weapon's Quick Roll section, it only consumes one resource.
> 
> If the "resource" box is checked, it will always consume one more use of ammunition than the number in the "Resource Consumption" box, unless the number is zero, in which case it will consume two. It will seemingly consume whatever quantity of resource is given in the "resource consumption" box when you click the item, and then consume one resource when the item is rolled. It is possible to set it to consume no resources (i.e. for the [firearm reload macro](https://www.reddit.com/r/FoundryVTT/comments/s00u44/macro_to_handle_reloading_guns/)), but only by setting its resource consumption to -1, in which case it will add one resource when clicked and then promptly consume one resource when it rolls.

Do you also have the issue where rolls from these weapons do not post?

**Comment by bluewarbler** [comment]
> > Seconding this issue. I did some investigation, and if you uncheck the "Resource" box in the ranged weapon's Quick Roll section, it only consumes one resource.
> > If the "resource" box is checked, it will always consume one more use of ammunition than the number in the "Resource Consumption" box, unless the number is zero, in which case it will consume two. It will seemingly consume whatever quantity of resource is given in the "resource consumption" box when you click the item, and then consume one resource when the item is rolled. It is possible to set it to consume no resources (i.e. for the [firearm reload macro](https://www.reddit.com/r/FoundryVTT/comments/s00u44/macro_to_handle_reloading_guns/)), but only by setting its resource consumption to -1, in which case it will add one resource when clicked and then promptly consume one resource when it rolls.
> 
> Do you also have the issue where rolls from these weapons do not post?

I did, at first, but I have since resolved this, I believe by recreating the items, though I don't remember exactly. The extra consumption issue still remains.

**Comment by Its-Scottih** [comment]
> > > Seconding this issue. I did some investigation, and if you uncheck the "Resource" box in the ranged weapon's Quick Roll section, it only consumes one resource.
> > > If the "resource" box is checked, it will always consume one more use of ammunition than the number in the "Resource Consumption" box, unless the number is zero, in which case it will consume two. It will seemingly consume whatever quantity of resource is given in the "resource consumption" box when you click the item, and then consume one resource when the item is rolled. It is possible to set it to consume no resources (i.e. for the [firearm reload macro](https://www.reddit.com/r/FoundryVTT/comments/s00u44/macro_to_handle_reloading_guns/)), but only by setting its resource consumption to -1, in which case it will add one resource when clicked and then promptly consume one resource when it rolls.
> > 
> > 
> > Do you also have the issue where rolls from these weapons do not post?
> 
> I did, at first, but I have since resolved this, I believe by recreating the items, though I don't remember exactly. The extra consumption issue still remains.

I too had to recreate the item!
I think there might be another module to blame though as a fresh world with just RSR would allow them to roll but I cant find what it would be.

**Comment by MangoFVTT** [comment]
The double use animation was due to #268, which is now resolved in dnd5e 2.4.1 The likely cause of all other issues is the changes to resource consumption made in 2.4.0, which can be resolved by updating both RSR and dnd5e to the latest version, and if that fails recreating the item (as you discovered).
