### ISSUE TITLE
[BUG] Item options lost and params overridden

### ISSUE THREAD

**Issue by chrisgms** [MangoFVTT/fvtt-ready-set-roll-5e#285]
**Description**
When trying to use items inside of macros with specific configs and options, the options are being lost and params are being overridden when defaults get merged. All tests were done with item quick roll enabled.

For example, when trying `await someItem.use({a: "b"}. {c: "d"})` will cut off `{c: "d"}` in the libWrapper call because the wrapper for `item.use` is only receiving one object, options, which is actually the config object being passed to `item.use`. This is particularly an issue when you're trying to disable chat output by doing something like `await someItem.use({chatMessage: false}. {c: "d"})` in which case the original wrapper is called and the second object is lost. 

I was able to fix this locally by just accepting the missing object in the libWrapper setup
```
// the new baseOptions is the vanilla options object while options is the vanilla config
async function _itemUse(wrapper, options, baseOptions) { 
    ...
    return await _itemProcessWrapper(this, wrapper, options, baseOptions); // pass the object along
}

async function _itemProcessWrapper(caller, wrapper, options, baseOptions) { 
    if (options?.chatMessage === false || options?.vanilla) {
		return wrapper.call(caller, options, baseOptions); // pass the expected object to original item.use 
	}
    ...
}
```

I can submit a pull request with this change, but in testing this I found a related issue that I was not able solve causing params to be overridden. 

Because item quick roll is enabled, the `USE_ITEM` hook is triggering the RSR workflow. If you run something like 
```
// RSR expects chatMessage in the first object but vanilla use expects it in the second
await someItem.use({createMessage: false, chatMessage: false}, {createMessage: false, chatMessage: false})
```
You will get two chat cards, one generated by the vanilla use() from libwrapper and an RSR card from the hook listener. Using the libwrapper fix from above will cut down the chat output to just the RSR card (the vanilla use still runs without chat output, perhaps this is intended behavior), but the RSR card should also not be output given the input options. It seems that these are somehow being overridden in `ensureQuickRollParams`. Tested with these logs setup:
```
static ensureQuickRollParams(params) {
        console.log("DEBUG - RSR - Params pre merge", params, "defaults")
        console.log("DEBUG - RSR - Expected result",  foundry.utils.mergeObject(foundry.utils.duplicate(CONFIG[MODULE_SHORT].defaultQuickRollParams), params || {}))
        params = foundry.utils.mergeObject(foundry.utils.duplicate(CONFIG[MODULE_SHORT].defaultQuickRollParams), params || {});
        console.log("DEBUG - RSR - Params after merge", params)
        ...
    }
```
The first two logs are as expected

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/76073614/4b0557bf-20d8-475c-aed5-1f08cf3b66be)

Somehow by the third log many properties got added and createMessage got overridden to true

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/76073614/6c28f709-89b9-49a6-86bc-d6d9a14e1263)

I was not able to trace down where the object was getting mutated from but my own attempt to override the return result of the function with `return {...params, createMessage: false}` also did not fix the issue. 

So far the only way I've been able to achieve "silent rolls" with use is to pass in the ignore option that is read in the `USE_ITEM` hook like this: `someItem.use({chatMessage: false}, {ignore: true, createMessage: false})`

**Steps to Reproduce**
1. Enable quick roll for items
2. Run `item.use()` with varying configs and options

**Versions**
 - Module: [2.1.6]
 - dnd5e: [2.4.1]
 - Foundry: [11.315]

**Other Modules**
Tested in new world with only RSR and libWrapper

**Comment by MangoFVTT** [comment]
@chrisgms since your goal is to use items via macros and utilise RSR chat cards, why not use the RSR version of the item use macro? Reference here: https://github.com/MangoFVTT/fvtt-ready-set-roll-5e?tab=readme-ov-file#macro-support

**Comment by chrisgms** [comment]
@MangoFVTT Using the RSR macro version has similar configuration issues

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/76073614/1ac7922f-e11c-4ec3-abb3-76b934eefc23)

**Comment by MangoFVTT** [comment]
Ahh I see the issue yes, the dnd5e system recently split the parameters of the item.use into config AND options, whereas they used to be one object. I'll look into a clean solution for that 👍

**Comment by MangoFVTT** [comment]
@chrisgms As of the merge of #297, I've fixed almost all the issues listed here by reworking a little bit how config and options are passed through the RSR pipeline. If you want a macro to print out only a default message it's important to pass `vanilla: true` to the `options` parameter, otherwise the RSR hook will still pick it up as an object usage due to how the patching works (tl;dr calling via macro bypasses the magic that RSR does to ignore the default chat message when called via the charsheet).

Please feel free to give all this a test once the newest version of RSR is released. I would recommend you use the RSR macro whenever possible to ensure correct behaviour. If you notice any options or config not behaving correctly when used in macros, create a separate bug ticket for those specific errors.
