### ISSUE TITLE
[BUG] Active effects not applied to tokens

### ISSUE THREAD

**Issue by tmchapin** [MangoFVTT/fvtt-ready-set-roll-5e#289]
**Description**
Cannot apply active effects to tokens using item rolls, either by applying directly via the roll or by clicking the button that appears in the card in the chat log. This is something that was functional locally in the past but at some point during or after an upgrade to foundry v11 has stopped working abruptly for some mysterious reason.

**Steps to Reproduce**
1. Roll any item with an active effect set (such as a barbarian rage).
2. Click on the "Apply Active Effects" button.
3. Nothing happens and nothing shows up in logs.
4. Tear hair out and repeat.

**Versions**
 - Module: [2.1.6]
 - dnd5e: [2.4.1]
 - Foundry: [11.315]

**Other Modules**
 - DAE [11.1.7]
 - libWrapper [1.12.13.0]
 - socketlib [1.0.13]

**Comment by bluewarbler** [comment]
I've found a workaround. You have to deactivate the DAE options for applying effects in the effect menu; otherwise it'll interfere and accidentally remove every way to apply the effect except manually.

**Comment by tmchapin** [comment]
Wow yup that does get the card button working -- would be nice to have application straight from the roll back eventually too but this fixes most of the headache, thanks for posting!

**Comment by MangoFVTT** [comment]
As of version 3.0.0 (which works with dnd5e 3.0), RSR no longer handles effect application and instead allows the system to do so internally. As such, this ticket is no longer related to RSR and can be considered resolved from the standpoint of this module.
