### ISSUE TITLE
[BUG] Item Resource Consumption and Resource Scaling not working for some spells

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#290]
**Description**
When a spell for example is set to consume a charge/usage of an item or feature then it wont ask to consume the usage even when Resource Scaling is turned on. It works if there is a template attached to it and Template Prompt is turned on, but without it the extra window is not shown. 

**Steps to Reproduce**
1. Make a new world with only ready set roll and lib active
2. give character a feature that has a number of uses per long rest
3. give that character a spell like guiding bolt as an innate spell that consumes a usage of the feature in step 2
4. on the spell also turn on resource scaling and in quick roll make sure it consumes the resource
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/f4f812ee-fc13-4231-811a-983e19f9b6a0)

5. use the spell and watch it roll without prompting usage consumption/scaling (image is to show what should show up but doesn't, which happens without any modules active)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/841fe1f7-43b1-45be-9806-7486a88cadd3)

6. do the same with a spell that has a measurement template like burning hands 
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/f070c8c5-7ae6-4356-ab38-ea0e0301b620)

7. see that then you do get the option to upscale the spell by consuming more of the resource. 
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/9bb41895-ed78-453e-8f6d-7bf6f9d81492)

**Versions**
 - Module: [2.1.6]
 - dnd5e: [2.4.1]
 - Foundry: [11.315]

**Other Modules**
A list of any other installed modules that might be related to the issue.

**Comment by Brynhold** [comment]
I have the same bug.

**Comment by MangoFVTT** [comment]
As of version 3.0.0 (which works with dnd5e 3.0), RSR no longer handles consumption and instead allows the system to do so via it's configure dialogs. As such, this ticket is no longer related to RSR and can be considered resolved from the standpoint of this module.
