### ISSUE TITLE
[BUG] Max dice on critical not applying

### ISSUE THREAD

**Issue by chrisgms** [MangoFVTT/fvtt-ready-set-roll-5e#291]
**Description**
Using the option to maximize critical dice does not work when augmenting an existing roll to be a crit. This seems to be because the natural crit flow is turning the base portion into the crit damage while the critical portion is the normal damage.  

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/76073614/2e70c532-30f2-416d-9a1c-98378920981a)

**Steps to Reproduce**
1. Enable maximize critical dice
2. Use the overlay crit button
3. Crit dice are not maximized

**Versions**
- Module: [2.1.6]
- dnd5e: [2.4.1]
- Foundry: [11.315]

**Other Modules**
libWrapper

**Comment by MangoFVTT** [comment]
This issue has been resolved and will be in the next release.
