### ISSUE TITLE
[BUG] RSR using +1 ammunitions when firing

### ISSUE THREAD

**Issue by Swaro3** [MangoFVTT/fvtt-ready-set-roll-5e#299]
**Description**
Using an ability/item with Resource Consumption active (Consumption Category = Ammunition, Consumption Target = Not Empty, Consumption Amount = Any) make the sistem use one addition ammo than normal (with value 0, it still uses 2 ammo). Tried even in a new word with only  RSR and libs installed and the bug was still there.

**Steps to Reproduce**
1. Click on the ability/item with Consumtion Ammunition on
2. See the number of the ammunitions decrease in the wrong amount

**Versions**
 - Module: [2.1.6]
 - dnd5e: [2.4.0]
 - Foundry: [11.315]

**Other Modules**
LibWrapper [1.12.13.0]

**Comment by MangoFVTT** [comment]
@Swaro3 This is a known issue with dnd5e 2.4.0, kindly update your system to 2.4.1 and RSR to the latest version to fix the issue.
