### ISSUE TITLE
Metadata validation failed for module "ready-set-roll-5e"

### ISSUE THREAD

**Issue by 742617000027** [MangoFVTT/fvtt-ready-set-roll-5e#3]
Very happy to see a promising successor of Better Rolls! When trying to install your module via the "Install Module" menu in the Foundry settings, I encountered the following error:

```
ready-set-roll-5e] Metadata validation failed for module "ready-set-roll-5e": The file "lib/libwrapper/shim.js" included by module ready-set-roll-5e does not exist
```

Or as screenshot:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/15521878/188688904-d093bf08-a40d-4238-8225-0f78546e67a2.png">

**Comment by MangoFVTT** [comment]
I have identified the root cause of this issue and will be releasing a hotfix shortly

**Comment by MangoFVTT** [comment]
@742617000027 Did this happen when installing via the search feature, or when installing via a manual manifest link?

**Comment by rtakehara** [comment]
for me it happened in both cases, I tried removing the ready-set-roll-5e folder before trying the manifest

btw, glad to see an effort to bring such convenient module, thank you, i hope it works soon

**Comment by BushTrocity** [comment]
Same I just tried installing it for the first time and same error. I tired both the mod install screen and the manual link.

**Comment by ArcangeloD** [comment]
Same problem on both methods too

**Comment by MangoFVTT** [comment]
@rtakehara @BushTrocity @ArcangeloD I've released a hotfix version 1.0.1, please check if this release fixes your issue 👍

**Comment by BushTrocity** [comment]
Worked for me

**Comment by ArcangeloD** [comment]
Working too
