### ISSUE TITLE
[FEATURE] Consider removing the requirement of external modules for effect transfer functionality

### ISSUE THREAD

**Issue by krbz999** [MangoFVTT/fvtt-ready-set-roll-5e#300]
In my module, `Concentration Notifier` (CN), I have been at the brunt end of a single module's issues repeatedly due to how it is implemented. Most recently, the module (1) randomly deleted concentration effects and now (2) disallows users from picking the correct Active Effect mode when using a flag that my module provides.

For this reason, I have decided to strongly advise users to remove said module if they wish to continue to use CN.

Please consider implementing a native feature for the functionality that the module is currently providing such that RSR and CN can remain compatible and feature complete at the same time.

**Comment by MangoFVTT** [comment]
As of version 3.0.0 (which works with dnd5e 3.0), RSR no longer handles effect application and instead allows the system to do so internally. As such,  DAE is no longer a dependency 👍
