### ISSUE TITLE
[BUG] RtR not reading flags from Concentration Notifier

### ISSUE THREAD

**Issue by DrWiFi** [MangoFVTT/fvtt-ready-set-roll-5e#301]
**Description**
The Concentration Notifier Mod: https://github.com/krbz999/concentrationnotifier allows for bonuses to be added to Concentration Checks. When Ready Set Roll is enabled, those bonuses are ignored. 

**Steps to Reproduce**
1. Install Concentration Monitor & Ready Set Roll 5e
2. In a Character sheet, under Special Traits, add a bonus to Concentration rolls (or any of the other options in that section)
3. Cast a Concentration Spell, then Apply damage to the token
4. Looking at what is rolled, any bonus from Concentration Notifier is ignored.

**Versions**
 - Module: [2.1.7]
 - dnd5e: [2.4.1]
 - Foundry: [11.315]

**Other Modules**
Concentration Notifier

Thank you

**Comment by DrWiFi** [comment]
There also seems to be an issue between Ready Set Roll and Roll Groups. https://github.com/krbz999/rollgroups
Roll groups adds additional buttons as damage options to an attack which lets you have a multitude of different options for your attacks.
When Ready Set Roll is enabled, those options do not appear.
Both Concentration Monitor And Roll Groups work if the Quick Rolling options are disabled.

**Comment by MangoFVTT** [comment]
As of version 3.0.0 (which works with dnd5e 3.0), RSR no longer creates its own rolls or overrides system roll hooks. This means bonuses applying to concentration should behave as expected before RSR even becomes involved.
