### ISSUE TITLE
[FEATURE] DnD5e system Enrichers Support

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#303]
**Is your feature request related to a problem? Please describe.**
The dnd5e System has build in [text enrichers](https://github.com/foundryvtt/dnd5e/wiki/Enrichers#damage-enrichers), some of which can be used for damage rolls of specific types. clicking such an enricher prompts you to roll whatever the enricher is set up to roll, like [[/damage 2d6 fire]]. However the roll is not fast forwarded and when hovered over the result the damage buttons are not there. Even if you apply the damage, resistances, immunities and vulnerabilities are not taken into consideration. It would be nice if those can be supported so that they automatically work

**Describe the solution you'd like**
That the damage rolls of these enrichers (preferably all inline rolls that mention a damage type like /roll 2d6[slashing]) to be recognised by this module and having the apply damage buttons with calculations based on resistances, immunities and vulnerabilities.

**Describe alternatives you've considered**
Manually making macros and dragging links to them onto text to do it that way.

**Additional context**
Keep up the good work so far

**Comment by MangoFVTT** [comment]
@maxobremer as of version 3.0.0 enrichers for saves, checks, and skills should be largely functional with RSR. Other enrichers such as damage are trickier, but will be worked on in the future.

**Comment by MangoFVTT** [comment]
Damage enricher support has been implemented and will be in the next release.

**Comment by maxobremer** [comment]
Hey Mango, 

if you mean version 3.0.12 of RSR, I just checked and it isn't working on that version if Enable Content on Vanilla Rolls is checked.
