### ISSUE TITLE
[BUG] Not compatible with newly released "Official" 5e system.

### ISSUE THREAD

**Issue by thepting** [MangoFVTT/fvtt-ready-set-roll-5e#304]
**Description**
Quick rolls are not working with the new "official" DnD5e game system.

**Steps to Reproduce**
1. Update the Dnd5e system 3.0.0 to the latest, on the latest Foundry_VTT 11 b315  (Stable)
2. Click on anything to roll, and it won't roll or display any dialogue.
3. Alt-click on something to roll and it will bypass the module and roll w/ the default 5e system dialog.

**Versions**
 - Module: [2.1.7]
 - dnd5e: [3.0.0]
 - Foundry: [11.315]

**Other Modules**
A list of any other installed modules that might be related to the issue.

**Comment by MangoFVTT** [comment]
This is completely expected since the new dnd 5e system changes basically everything. A major rewrite of RSR will need to happen, that can be tracked here: https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/issues/305
