### ISSUE TITLE
[FEATURE] DnD 5e Compatibility for 3.0 Release

### ISSUE THREAD

**Issue by MangoFVTT** [MangoFVTT/fvtt-ready-set-roll-5e#305]
This ticket is to track a major rewrite of RSR to work with the new DnD5e 3.0 release. This is an almost complete refactor of most of RSR's systems due to significant changes in the DnD5e system. Compatibility should be expected to take some time, as we had no forewarning of this release from the Foundry team and therefore no chance to prepare.

NOTE: I have yet to investigate all changes made for the 3.0 release. It is entirely possible that many of RSR's features are now redundant and no long necessary, and major changes to how RSR behaves should be expected regardless to fit with the new paradigm of how the DnD5e system behaves now.

**Comment by evan-rash** [comment]
Just wanted to chime in that I love RSR an Inat least think its functionality is still helpful. Especially being able to roll attack and damage immediately without having to click on the buttons in chat!

**Comment by MangoFVTT** [comment]
Can confirm that quick roll functionality will still exist largely unchanged, however quick rolls will now integrate into the default chat cards (with some additions e.g. for multi-rolls) instead of creating their own.

**Comment by MangoFVTT** [comment]
SMALL UPDATE:
- Basic quick Rolls for Actor rolls (skills, abilities, saves, and death saves) are now functioning as expected
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/8a94a003-44ae-42dc-a9f4-b067fccdfaf1)
- Item quick rolls are still in progress, but the bulk of the setup for placing component rolls into the original card is now complete. Attack rolls already work as expected
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/3a7b72a3-f525-423c-a2fd-6b6fed9c40ca)

Still to do:
- Everything else

**Comment by avportia** [comment]
Fantastic. Thank you for all of your work. I'm still holding off on updating to 3.0 but once this is ready I'm going to update all the things.

**Comment by ErebusAres** [comment]
is there a way to get a 'beta' version of the module in the mean time? or is it even worth doing a 'beta'

**Comment by thepting** [comment]
> is there a way to get a 'beta' version of the module in the mean time? or is it even worth doing a 'beta'

A lot of times trying to do a "beta" release when you know you're not finished just adds more work and makes it take longer to get the finished product.  Especially because there's a lot of people who will install it thinking it'll run fine and try things you already know are broken.  Chews up a lot of time in support, which isn't fun for someone doing this as a hobby.

I'm impatient too - running the new PBTSO module on Tuesday so I need to use the latest 5e.  First session or two may have to use the normal rolling.

**Comment by ErebusAres** [comment]
Ok no problem, just curious. Hopefully everything becomes a smooth
transition for you 😊

**Comment by roguedevjake** [comment]
> > is there a way to get a 'beta' version of the module in the mean time? or is it even worth doing a 'beta'
> 
> A lot of times trying to do a "beta" release when you know you're not finished just adds more work and makes it take longer to get the finished product. Especially because there's a lot of people who will install it thinking it'll run fine and try things you already know are broken. Chews up a lot of time in support, which isn't fun for someone doing this as a hobby.
> 
> I'm impatient too - running the new PBTSO module on Tuesday so I need to use the latest 5e. First session or two may have to use the normal rolling.

remember to use token health, because boy howdy is damage application a pain and a bunch of clicks otherwise :P. I hope the 5e team just follows the example set by pf2e and many other systems of having buttons in the future.

**Comment by MangoFVTT** [comment]
Version 3.0.0 has now been released, bringing compatibility for the dnd5e 3.0: https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/releases/tag/release-3.0.0

For new issues related to RSR in 3.0, please create new tickets in the issues page.

**Comment by rthill91** [comment]
one of my favorite foundry modules and one that was keeping me from jumping to the new version. Thanks so much for the quick turnaround on this
