### ISSUE TITLE
[BUG] Critical Damage Application With Disadvantage Rolls

### ISSUE THREAD

**Issue by Djovis** [MangoFVTT/fvtt-ready-set-roll-5e#306]
**Description**
When make attack roll with disadvantage (only using retroactive disadv button on chat cards, not ctrl roll), even one of die's not crit, rolling crit damage. It doesn’t matter whether the first or second die is critical, the bug always works.
![изображение](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/67070895/d273d29b-959a-4d63-af42-693156e5e096)
![изображение](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/67070895/13720a3c-e586-45d6-a4b8-716149fca0f5)

**Steps to Reproduce**
1. Roll attack rolls, wthen use retroactive disadv button until you get one crit and one noncrit roll. Then roll damage.

**Versions**
 - Module: [2.1.7]
 - dnd5e: [2.4.1]
 - Foundry: [11.315]

**Other Modules**
I disabled all other modules, the bug persisted.

**Comment by MangoFVTT** [comment]
This issue should now be resolved in version 3.0.0

**Comment by Djovis** [comment]
Mmm, great... Is there no way to fix the bug for those who do not plan to switch to dnd5e 3.0.0?

**Comment by Djovis** [comment]
> This issue should now be resolved in version 3.0.0

Mmm, great... Is there no way to fix the bug for those who do not plan to switch to dnd5e 3.0.0?

**Comment by MangoFVTT** [comment]
Ongoing maintenance of previous versions of RSR (or backwards compatibility) is not particularly feasible, as they are now effectively two entirely different modules and would therefore require completely separate development, which I simply don't have the time for.
