### ISSUE TITLE
Post-roll + - buttons to add advantage or disadvantage to an existing single roll

### ISSUE THREAD

**Issue by apoapostolov** [MangoFVTT/fvtt-ready-set-roll-5e#31]
This is the last thing I am greatly missing from Better Rolls for 5E my players and myself are very used to, is adding advantage or disafvantage after the roll, especially if I as a DM remind them, or they figure it out they missed to use the right keybinding. 

What Better Rolls for 5E does is show [+] and [-] buttons on each side of the check/save/attack roll on hover only, andif pressed, the roll gets added advantage or disadvantage.

Similarly, a {+] button is available for damage rolls on hover, to turn a normal damage roll into a critical damage roll by adding another die rolls and add to the existing normal damage.

**Comment by MangoFVTT** [comment]
This is already a planned feature for this module, no worries. You can keep track of planned features and their general status of development by the order of the list on the main page: https://github.com/MangoFVTT/fvtt-ready-set-roll-5e#planned-features

**Comment by Chromie192** [comment]
> This is already a planned feature for this module, no worries. You can keep track of planned features and their general status of development by the order of the list on the main page: https://github.com/MangoFVTT/fvtt-ready-set-roll-5e#planned-features

Would this still have that nice merge window of the Attack & Damage roll? Currently, only enabling quick rolls allows for that and my group (myself included) just prefer not having it on.

**Comment by MangoFVTT** [comment]
> Would this still have that nice merge window of the Attack & Damage roll? Currently, only enabling quick rolls allows for that and my group (myself included) just prefer not having it on.

I'm afraid I'm not sure what you mean by merge window. Default behaviour for quick rolls is to include both Attack & Damage immediately together into one card. If you want to not have one or the either you can switch them off via the roll configuration tab per item. Could you provide an example of the functionality you'd like?

**Comment by Chromie192** [comment]
> 

With Better Rolls 5e, I could roll and the attack and damage rolls would be merge onto a chat card. In the picture, you can see how **_Ready Set Roll_** merges the attack and damage roll with quick rolls turned on in the red in the top portion. If I turn off quick rolls it stops merging them in the bottom portion.

![1111](https://user-images.githubusercontent.com/79137233/189465287-a61e6753-b842-4be7-931f-b183835f2d50.png)

**Comment by MangoFVTT** [comment]
Ah so I presume you're talking about Better Roll's feature to update the same chat card once you roll Attack/Damage manually. This is not an existing feature in RSR yet, but is on the planned features list. It will likely be implemented at the same time as retroactive advantage/disadvantage since it requires the same tech. You can keep an eye on [this](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/issues/33) ticket to see when the feature is implemented.

**Comment by Chromie192** [comment]
> Ah so I presume you're talking about Better Roll's feature to update the same chat card once you roll Attack/Damage manually. This is not an existing feature in RSR yet, but is on the planned features list. It will likely be implemented at the same time as retroactive advantage/disadvantage since it requires the same tech. You can keep an eye on [this](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/issues/33) ticket to see when the feature is implemented.

Yes! Appreciate the response.

**Comment by MangoFVTT** [comment]
This feature is now implemented by #42 and will be in the next feature release.

**Comment by MangoFVTT** [comment]
This issue is now fixed on Release 1.3.0
