### ISSUE TITLE
[BUG] Directory issue

### ISSUE THREAD

**Issue by roguedevjake** [MangoFVTT/fvtt-ready-set-roll-5e#312]
**Description**
There are parts of the module pointing to 

`foundry.js:7678 Uncaught (in promise) Error: ENOENT: no such file or directory, open 'D:\FoundryVTT\Data\modules\ready-set-roll-5e-v3\templates\rsr-multiroll.html'`
 
The issue being "-v3\" :P

**Comment by MangoFVTT** [comment]
Issue should be fixed with 3.0.1
