### ISSUE TITLE
[BUG] No Hit or Miss Indicator In Chat Card

### ISSUE THREAD

**Issue by christhedm** [MangoFVTT/fvtt-ready-set-roll-5e#316]
Doesnt include whether you hit, or miss in the chat card like the v.3.0 chat cards natively supported 

Without mod: 
![v1](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/159794999/3c776383-c4ec-4a11-a936-2b2136bb9c88)

With Mod: 
![v2](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/159794999/6cfb7758-54c5-4d8d-8e48-111b8aa2ebb2)

**Comment by MangoFVTT** [comment]
Issue is fixed and should be in the next release.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/44e91f94-bdd2-41b8-9ca4-cbfa92c8fa94)
