### ISSUE TITLE
Compatibility with Die Hard

### ISSUE THREAD

**Issue by apoapostolov** [MangoFVTT/fvtt-ready-set-roll-5e#32]
Die Hard is a dice fudging/cheating* module and a Karma Dice system for DMs developed by UranusBytes on commission from me. Link at: https://github.com/UranusBytes/foundry-die-hard  This mod allows sensible mindful DM to provide newbies with a great time, to save their campaigns from extremely bad series of bad dice or one critical roll that the whole plot hangs on. What it does is capture dice rolls, reroll them secretly until the value is within set reusable rules (one time or persistent) and then only show the dice roll message if the value fits expected ranges. 

Die Hard works great on other systems like PF2 but never worked with complete dice message overhauls like Better Roll for 5E, and getting its developer to allow API that let Die Hard pass the acceptable fudged value to Better Rolls so it displays the message was never realized. We were even thinking about forking Better Roll to allow compatibility, but suddenly this mod filled the void of the now abandoned Better Rolls. 

If you would be interested, and it could be a feature commission if this is on the fringe of the mod's scope, a compatibility API for Die Hard to work with the dice values before Ready Set Roll fires up would allow for both mods to coexist on 5E.

**Comment by MangoFVTT** [comment]
Compatibility with other modules that modify/hook into the actual dice rolling part of the dnd5e system is difficult and might not be 100% possible in its current state, but I'm open to attempting it. I will be moving onto module compatibility at a later date once I have achieved feature parity with Better Rolls 5e at minimum. At that time I will look into this module to see if it is at all possible to have it function with Ready Set Roll 🙂

**Comment by UranusBytes** [comment]
Initial review implies that the DND5e specific wrappers for items such as Actor rollAbilitySave, rollSkill, rollAbilityTest, etc... are incompatible with Ready Set Roll for 5e, but the basic "Total Roll" and "Raw Roll", as well as Karma, are compatible and execute without issue.

Further testing is needed.

An alpha release of the module manifest has been posted to 

https://github.com/UranusBytes/foundry-die-hard/releases/download/0.1.1-alpha/module.json

This disables all the DND5e specific wrappers if the Ready Set Roll for 5e is installed...

Tracking through https://github.com/UranusBytes/foundry-die-hard/issues/34

**Comment by MangoFVTT** [comment]
Closing this issue as stale since Die Hard hasn't been updated since August.
