### ISSUE TITLE
[FEATURE] Improve access to apply damage x1 

### ISSUE THREAD

**Issue by apoapostolov** [MangoFVTT/fvtt-ready-set-roll-5e#323]
Expose the Apply Damage 1 times into the damage block.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/4083812/6a07d9c0-932e-4307-98c9-a072cd14b583)

 Improve the size and legibility of the other options x2, x1/2, x1/4 as they are barely seen. Put Healing at the right end, maybe take a look at how PF2 Target Damage buttons are color coded and using nice readable icons.

**Comment by roguedevjake** [comment]
My personal preferred style would be always visible buttons as an option (rather than hover and drop down.

The top layer would apply all the damage (sequential application), and then expanding the damage would have all the sub damage application buttons. 

On the PF2e target damage topic, boy howdy do I hope 5e (and pf2e propper) adopts it's way of handling multi target saving throws.

**Comment by lipehique** [comment]
The hidden options add a few extra clicks to the action. If it can all be visible and clickable directly from the card, it would speed up the process a lot.

**Comment by MangoFVTT** [comment]
Partially implemented this feature request with a setting to always show the apply damage buttons instead of only on hover. Will later add apply buttons to the total damage box.

Personally I disagree with the icons being unclear, as there's nothing clearer to me than essentially writing "Damage x1" or "Damage x2", using the system's own indicator icon for damage. Whatever icons I use will always be clearer to some than to others, that's just unavoidable. Adding more details and text and such will make the cards far too bloated for my taste, bearing in mind that RSR is supposed to be relatively lightweight and not hijack the entire UI with its own additions.

**Comment by apoapostolov** [comment]
Hello @MangoFVTT 

First let me preface that I really appreciate and respect all the great work integrating RSR for 5E 3.0. You have done great job integrating in the new visual language for the attack and damage cards.

With the damage buttons, the issues are not that they are unclear but their legibility being this tiny is not great. Also, there's need for damage buttons (also always-visible) for the total damage to avoid the need to open the box with the separate damages (even if just one damage there) and then hovering to get the buttons. So this could be greatly improved if it was like this

- Buttons remain as is for separate damages within the roll but with option to have them always visible. Maybe also slightly increasing their size as I notice that there's a tiny padding on the right side that can be used. 
- Buttons are added to the total damage, no longer requiring the damage card to be expanded to get to the smaller buttons. These buttons can be implemented smarly, to avoid the need to have so many buttons. For example, on the damage value box there can be a buttons for x1 and Heal damage, that can be right clicked for menu for all other options. This would avoid the need for another line of buttons under the total damage value box, and would give access to the most important options in a fast and concise way.

**Comment by thepting** [comment]
I just used RSR for the first time tonight, and I agree the button labels are clear and easy to understand, if a bit small.  That's pretty minor though - the main feedback I have is that it would be quicker in game if they were visible without having to unfold the damage roll.  The only time I wasn't unfolding the roll was on a miss, so I think the convenience of not having to click to expand the damage outweighs the extra space consumed on the card.

BTW, everyone loved the mod and felt like it really sped up combat.

**Comment by MangoFVTT** [comment]
@thepting In latest versions of RSR there is now a setting option to keep the buttons permanently unfolded, feel free to enable that to help with your particular issue.

**Comment by thepting** [comment]
@MangoFVTT   Ahhh, I mean the damage tooltip itself not unfolding automatically to show the apply damage buttons.  Is there a way for you to put them outside of the fold so they always show up in the card?

**Comment by apoapostolov** [comment]
I want to give example with another mod (unfortunately afaik not compatible with RSR 3.0) that has exactly what we are asking. 

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/4083812/97572ef4-c2e0-4ee4-a133-a8b30731a041)

Video demonstration here: https://foundryvtt.com/packages/damage-application

I think using Targeted Token and this approach would be perfect, and you can style it to fit the new 3.0 chat card CSS.

**Comment by MangoFVTT** [comment]
UPDATE: Functionality to apply total damage from outside the tooltips is in progress, will look like this:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/3012f088-af36-42aa-bcbf-e4304c59a9b5)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/637845ae-950b-42ec-a106-ef5475fa7c5a)

**Comment by apoapostolov** [comment]
This looks amazing! Thank you very much, exactly what we need!

**Comment by christhedm** [comment]
Yay! Looking forward to the next release! Thanks Mango <3

**Comment by MangoFVTT** [comment]
Feature has been implemented and will be in the next release.
