### ISSUE TITLE
[BUG] "Loot" Category Items Not Outputting

### ISSUE THREAD

**Issue by Ancient-Gazebo** [MangoFVTT/fvtt-ready-set-roll-5e#324]
**Description**
Anything in the "Loot" Category doesn't output to chat at all. 

**Steps to Reproduce**
1. Go to anything in "Loot" and attempt to output it. Turn the module off, and it will appear and output after.

**Versions**
 - Module: 3.0.2
 - dnd5e: 3.0.1
 - Foundry: Version 11 Stable Build 315

**Other Modules**
No other modules installed when testing. I am on Forge, however.

**Comment by MangoFVTT** [comment]
Issue is resolved and should be in the next release.
