### ISSUE TITLE
[BUG] Chat does not scroll to latest message

### ISSUE THREAD

**Issue by nschoenwald** [MangoFVTT/fvtt-ready-set-roll-5e#327]
**Description**
Whenever a new chat card is created, the chat does not automatically scroll down to the latest chat card. You have to manually scroll down to see the roll results.
**Steps to Reproduce**
1. Fill chat log.
2. Roll again.

**Versions**
 - Module: 3.0.2
 - dnd5e: 3.0.1
 - Foundry: 11.315

**Other Modules**
This bug occurs with all other modules disabled.

**Comment by MangoFVTT** [comment]
Issue is resolved and will be in the next release.
