### ISSUE TITLE
[FEATURE] Quick Roll to attack, but manually clicking on the "damage" button roll?

### ISSUE THREAD

**Issue by Cempres** [MangoFVTT/fvtt-ready-set-roll-5e#33]
Better rolls had an option to auto-roll the "Attack" for a weapon/spell/whatever, but had the option to have the "Damage" button be manually clickable and rollable, as players prefer that "half automation".

**Comment by MangoFVTT** [comment]
This feature is on the table and will be worked on (if possible) while introducing retroactive advantage/disadvantage to chat cards since it requires the same capability of modifying an existing message. Keep an eye on this issue for updates on the feature's progress 🙂

**Comment by Cempres** [comment]
I can't really play without that feature, hence waiting for it to go off my backup into the v10! Can't wait, and thanks so much for doing it in the 1s place!

**Comment by jeffuntalan** [comment]
> Better rolls had an option to auto-roll the "Attack" for a weapon/spell/whatever, but had the option to have the "Damage" button be manually clickable and rollable, as players prefer that "half automation".

+1 to this! This is the only feature I used in BR; specifically I disable automatic rolling and just allow players to "query for adv/disadv" all while using their pretty chat cards.

I'm really excited for your work! Taking on BR is a monumental task in itself. I hope you don't get burnt out by this. Thank you for your efforts!

**Comment by MangoFVTT** [comment]
This feature has been implemented and will be in the next release.

**Comment by MangoFVTT** [comment]
This feature is now implemented in Release 1.3.6
