### ISSUE TITLE
[FEATURE] More Compact Chat Message

### ISSUE THREAD

**Issue by Vengrath97** [MangoFVTT/fvtt-ready-set-roll-5e#334]
**Is your feature request related to a problem? Please describe.**
Since the update to D&D5e 3.0 and above, the chat messages are extremelly bulky, and each message with a roll takes up a lot of space, which is not necessary, as it was much more compact before 3.0

**Describe the solution you'd like**
Make the chat message more compact, by using smaller font size, remove unnecesary frames and/or make them smaller.

**Describe alternatives you've considered**
Provide a separate roll mode as a default (in module settings), wherethere is no description if the roll is for attack or damage, as advanced users can intuit it from the type and amount of dice rolled.

**Additional context**
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/95933584/44c485c6-6bae-4289-8f6b-afbd4a0908f5)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/95933584/86b73791-bd69-45cd-8606-a89385e86a53)

Here is a very rough example of the current, and desired look.

**Comment by MangoFVTT** [comment]
@Vengrath97 This is really a matter of styling in the new dnd5e system more than an RSR issue. For me to fix this I would need to override essentially all the styling introduced by dnd5e 3.0, which would not only be a huge chore but also completely unmaintainable in the long run. 

There are some things I can potentially do to reduce message size, but I would definitely recommend bringing this up as an issue on the dnd5e github instead, where they can take a look at the system styling at large and perhaps introduce some more compact versions.

**Comment by MangoFVTT** [comment]
I've taken a pass at compacting all RSR content as much as possible, but the bulk of the chat message size is dnd 5e styling and should be taken up with the dnd5e github. Will be closing this ticket since there's nothing else I can do from my end.
