### ISSUE TITLE
[BUG] Dice so Nice rolls d20 again when manually rolling damage

### ISSUE THREAD

**Issue by nschoenwald** [MangoFVTT/fvtt-ready-set-roll-5e#342]
**Description**
See video:
[https://youtu.be/CVg-Lo7M0uY](https://youtu.be/CVg-Lo7M0uY)

**Versions**
 - Module: 3.0.5
 - dnd5e: 3.0.2
 - Foundry: 11.315

**Comment by Vengrath97** [comment]
I have also encountered this bug. I believe that it also appeared in older versions of the module, with D&D5e versions before the 3.0 update

**Comment by MangoFVTT** [comment]
Issue is resolved and will be in the next release.
