### ISSUE TITLE
[BUG] Critical damage wrong sum

### ISSUE THREAD

**Issue by Vengrath97** [MangoFVTT/fvtt-ready-set-roll-5e#351]
**Description**
After rolling critical damage, the new damage sum doesn't match the sum of the dice and modifiers.
**Steps to Reproduce**
1. Open a character sheet
2. Click on a weapon
3. Scroll down to weapon attack roll from RSR
4. Hover over damage number
5. Click on damage number to show the dice rolled
6. Click dice icon to roll critical damage
7. Notice that the new sum doesn't add up from the numbers of the roll

**Versions**
 - Module: [3.0.5] (also [3.0.6])
 - dnd5e: [3.0.2]
 - Foundry: [11.315]

**Other Modules**
A list of any other installed modules that might be related to the issue.
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/95933584/b4759358-bb6c-4fce-8643-e01b477711db)

**Comment by Vengrath97** [comment]
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/95933584/0efdbe67-c0d9-4af1-ac18-707a90f80eb4)
I have confirmed that the bug does appear on 3.0.6 too

**Comment by MangoFVTT** [comment]
Issue has been resolved and will be in the next release.
