### ISSUE TITLE
[BUG] Upcasted spells do not roll the correct amount of dice when quick rolling damage

### ISSUE THREAD

**Issue by ScoflWorks** [MangoFVTT/fvtt-ready-set-roll-5e#352]
**Description**
When "Roll Damage Manually" is set to "Never", and a spell that adds damage dice at higher levels is upcasted, the additional dice are not rolled. The same occurs when "Roll Damage Manually" is set to "Attack Rolls Only" with upcasted attack roll spells. This does not occur when rolling damage manually. The card still displays the correct level.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/160209186/e4c16ba9-1905-4806-93b5-74ca978f0875)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/160209186/3bab726b-b4bf-4117-b792-9510f6e2c93c)

**Steps to Reproduce**
1. Set the "Roll Damage Manually" setting to "Never"
2. Open a character sheet with at least 2nd-level spell losts
3. Use a spell which adds dice at higher levels (e.g. Cure Wounds)
4. Set "Cast at Level" to "2nd Level" and Cast the Spell
5. See that the card displays "2nd Level" but only the base number of dice have been rolled (e.g. 1d8 instead of 2d8)

**Versions**
 - Module: [3.0.6]
 - dnd5e: [3.0.2]
 - Foundry: [11.315]

**Other Modules**
- None

**Likely Cause**
I did a little bit of digging and noticed that the base DND5e system changes `item.system.level` from its base level to the level the spell is being upcasted to in `item.use()`, then retrieves the base item from the actor when the roll damage button is pressed afterward. When RSR calls `item.rollDamage()` in `ItemUtility.getDamageFromCard()`, after the item's level has changed, the system treats it as though the upcast level *is* its base level. Presumably this is why only quick-rolled damage is affected.
Forcing `item = await _ensureItemFromCard(card)` to get an unmodified version of the base item in `ItemUtility.getDamageFromCard()` seemed to work for me, but I am unsure if this is the best solution.

**Comment by MangoFVTT** [comment]
Issue has been resolved and will be in the next release. Thanks for the investigation, it makes my job a lot easier! ❤️
