### ISSUE TITLE
[FEATURE] Misclicking issues with critical damage

### ISSUE THREAD

**Issue by nschoenwald** [MangoFVTT/fvtt-ready-set-roll-5e#355]
Maybe I'm just a clumsy idiot, but I have been having some misclicking issues with the critical damage button in my sessions. The button is very close to the damage sum and only shows on hover. So when trying to expand the damage for the buttons, my players or I sometimes misclick.

Some ideas that could help me:

1. Always showing the crit damage button, not just on hover.
2. Moving the button the left side.
3. Asking for confirmation before actually rolling the crit damage after clicking the button.

**Comment by Vengrath97** [comment]
Please: big no for asking for confirmation. The user experience is best when no additional messages, pop-ups and so on show up. In fact, this is the main advanate of RSR for me and my players that we do not need to click through 2-3 dialogues to know if an attack hits and if so, how hard.

**Comment by nschoenwald** [comment]
Oh yeah, I forgot to mention: This should definitely not be the default. But it would be great to have as an option. The use case of having to manually roll critical damage is very rare for me, as it is mostly only neccessary when someone has a status conditions that causes all hits to be crits.

**Comment by MangoFVTT** [comment]
Rest assured that no additional dialogs will ever be added by RSR without at minimum a setting to skip them if wished. As you say, that's the whole point of the module, which is to roll fast and easily. 

That being said a dialog to avoid accidentally clicking the crit overlay for those that want it is a good idea, and quite easy to add, so I will definitely look into it asap

**Comment by MangoFVTT** [comment]
Issue is resolved and will be in the next release.
