### ISSUE TITLE
[BUG] Elven Accuracy makes Disadvantage more severe than intended

### ISSUE THREAD

**Issue by Vengrath97** [MangoFVTT/fvtt-ready-set-roll-5e#356]
**Description**
Elven Accuracy should not apply to Disadvantage. Currently, it does, and what's worse, it picks the lowest of 3 dice.

**Steps to Reproduce**
1. Create a character with Elven Accuracy
2. Roll with a weapon or ability that would apply Elven Accuracy if it had advantage
3. Click disadvantage on the roll
4. Observe, that 3 dice are rolled (should be only 2, as Elven Accuracy shouldn't affect disadvantage). What's worse, all 3 dice are taken into account, and the lowest of the 3 is picked.
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/95933584/de75a252-f86a-4432-916a-7198df6251f3)

**Versions**
 - Module: [3.0.6]
 - dnd5e: [3.0.2]
 - Foundry: [10.315]

**Other Modules**
None

**Comment by MangoFVTT** [comment]
Issue has been resolved and will be in the next release.
