### ISSUE TITLE
The extra damage dice for upcast spells are not being added when using certain settings.

### ISSUE THREAD

**Issue by ShannonMcG** [MangoFVTT/fvtt-ready-set-roll-5e#357]
**Description**
Extra damage dice for upcast spells, like _fireball_, are not being rolled when the setting ROLL DAMAGE MANUALLY is set to NEVER or ATTACK ROLLS ONLY.

**Steps to Reproduce**
1. With RSR setting, ROLL DAMAGE MANUALLY, set to to NEVER or ATTACK ROLLS ONLY...
2. Go to a spell, like _fireball_, that scales the damage with spell level.
3. Cast the spell at a higher level, like 5th. For _fireball_ the damage should be 10d6.
4. See screenshot of the chat card that shows only 8d6 were rolled for damage.
5. The same issue happens with other spells, like _burning hands_ and _thunderwave_, that scale damage with spell level.

<img width="268" alt="Screen Shot 2024-02-16 at 1 11 43 PM" src="https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/9142815/2296e524-e3d4-4c00-8558-8e2f83614bdf">

The damage dice are correct if rolled manually from the chat card or if the RSR module is disabled.

Hope that helps!

**Versions**
 - Module: 3.0.6
 - dnd5e: 3.0.2
 - Foundry: v11 - Patch 13 (build 315)

**Comment by Vengrath97** [comment]
This has been mentioned before and fixed:
https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/issues/352

We're just waiting for the new release.

**Comment by ShannonMcG** [comment]
Perfect. Thanks! :)

**Comment by MangoFVTT** [comment]
As mentioned, issue is a duplicate and will be fixed with next release.
