### ISSUE TITLE
[BUG] RSR doesn't work properly for characters owned by multiple users.

### ISSUE THREAD

**Issue by Vengrath97** [MangoFVTT/fvtt-ready-set-roll-5e#363]
**Description**
When there is a character that is owned by multiple users (which includes the scenarion when it is one player and Admin) and one of them rolls something, the other user will not see roll results on the chat, but rather a prompt. Example:

Example 1: 
1.1 The Admin user rolls from player sheet. What Admin sees:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/95933584/9188a326-31e0-416c-a952-62f49666c655)
1.2 What user that owns this character sees:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/95933584/46a4b77d-732f-494a-a73e-f6f94d2fc63b)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/95933584/b0cd0c2d-4b8f-4e30-a373-fedaddc9d019)

Example 2:
2.1 The user that owns this character rolls form his sheet. What Admin sees:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/95933584/1c412146-e27d-4c49-91b8-08473c372f60)
2.2 What the user that made the roll sees:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/95933584/bb7b97e3-528e-471e-896c-609003e941f8)

**Versions**
 - Module: [3.0.7]
 - dnd5e: [3.0.2]
 - Foundry: [10.315]

**Other Modules**
None

This problem might be related to this issue: https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/issues/362 as the "User lacks permission to update chat message" 
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/95933584/46a4b77d-732f-494a-a73e-f6f94d2fc63b) 
seems to me to be sign of an underlying common issue.

**Comment by MangoFVTT** [comment]
@Vengrath97 can you confirm if this issue was also fixed by the server restart as discussed in #362?

**Comment by Vengrath97** [comment]
Yes, it has. The error no longer appears too. Weird

**Comment by MangoFVTT** [comment]
We can safely assume these two issues are rooted in the same cause then. Closing this as a duplicate 👍
