### ISSUE TITLE
[BUG] roll results of GM are visible for all players

### ISSUE THREAD

**Issue by lordZwiebel** [MangoFVTT/fvtt-ready-set-roll-5e#364]
**Description**
The dice roll results of ability checks and saving throws made by the GM are visible to all players even when made as Self Rolls.
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/100702670/a19ba1e5-1437-48b4-adc2-fc37208ac927)

The roles in the sceenshot are made as Private GM Roll, Self Roll and Blind GM Roll respectively and taken as a player.

**Steps to Reproduce**
1. Set roll mode to a GM Roll or Self Roll as GM
2. Use an ability check or thaving throw

**Versions**
 - Module: [3.0.7]
 - dnd5e: [3.0.2]
 - Foundry: [11.315]

**Other Modules**
None

**Comment by MangoFVTT** [comment]
@lordZwiebel I'm not able to reproduce this issue in RSR 3.0.7 (see image below, left is GM view and right is player view). This was an issue in versions 3.0.5 and earlier, but was fixed in 3.0.6. Can you confirm if the module is actually updated to the latest version for you?

**Comment by MangoFVTT** [comment]
@lordZwiebel I'm not able to reproduce this issue on the latest version of RSR (see image below, left is GM view and right is Player view). However this was a known issue in previous versions of RSR, so could you make sure that your module is actually updated to the latest version? Perhaps even re-install the latest version of the module if needed.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/c261976c-eb85-403c-8514-0f022c117beb)

**Comment by lordZwiebel** [comment]
I'm sorry, had to do a rollback of my server a few days ago and had the module on 3.0.1 due to that. You are correct with the latest version this isn't a problem anymore.
