### ISSUE TITLE
[BUG] Saving Throw Chat Cards Colored Results Displaying Incorrect Colors 

### ISSUE THREAD

**Issue by lipehique** [MangoFVTT/fvtt-ready-set-roll-5e#366]
**Description**
When rolling a saving throw using quick roll, you can pass the saving throw and still receive a red chat card if your initial roll is below the save DC. With the module off, the same card is green. Maybe it happens with ability checks and enrichers too, but cannot try at the moment.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/159858551/a11438c6-dca5-4ba8-aa3c-0075960216e7)

**Steps to Reproduce**
1. Turn on Ready Set Roll
2. Use item with saving throw, like spell or monster ability
3. Roll the saving throw until your initial roll is below save DC, but the result is higher. 
4. Chat card colors should be green, but it is red.

**Versions**
 - Module: Ready Set Roll 3.0.7
 - dnd5e: 3.0.2 (but also reproduced on 3.0.1)
 - Foundry: [[11.315]

**Other Modules**
No other modules active.

**Comment by MangoFVTT** [comment]
Issue is resolved and will be in the next release.
