### ISSUE TITLE
[BUG] Cannot create working attack on NPC sheet

### ISSUE THREAD

**Issue by denis-kralj** [MangoFVTT/fvtt-ready-set-roll-5e#369]
**Description**
When creating a fresh NPC, defining an attack manually doesn't allow a roll to happen with the module enabled

**Steps to Reproduce**
1. in a scene create an NPC actor
2. In the "features" tab add a new attack
3. edit the attack details to be a melee weapon attack with any dice for damage formula
4. exit the edit window and click on the dice icon that appears on hover for the attack in order to roll it
5.
    a. expected - roll shows up in chat
    b. actual - nothing shows up in chat and there is an error in the js console in the browser

The error in the console is this:

```
Uncaught (in promise) TypeError: item is undefined          item.js:146:9
    getAttackFromCard item.js:146
    runItemActions item.js:89
    registerRollHooks hooks.js:120
    #call foundry.js:730
    callAll foundry.js:687
    displayCard item.mjs:1356
    use item.mjs:1009
    _onAction inventory.mjs:377
    connectedCallback inventory.mjs:35
    connectedCallback inventory.mjs:34
    jQuery 3
    _injectHTML foundry.js:6012
    _render foundry.js:5835
    _render foundry.js:6532
    render foundry.js:5769
    render foundry.js:7111
    _onClickLeft2 foundry.js:56272
    callback foundry.js:31766
    #handleClickLeft2 foundry.js:31971
    #handleMouseDown foundry.js:31938
    notifyListeners earcut.js:128
    notifyTarget earcut.js:128
    propagate earcut.js:128
    dispatchEvent earcut.js:128
    mapPointerDown earcut.js:128
    mapEvent earcut.js:128
    onPointerDown earcut.js:128
    addEvents earcut.js:128
    setTargetElement earcut.js:128
    init earcut.js:128
    emit index.mjs:5
    run index.js:89
    un index.js:126
    wa index.js:89
    xn earcut.js:128
    #createApplication foundry.js:26327
    initialize foundry.js:26223
    initializeCanvas foundry.js:8894
    setupGame foundry.js:8724
    _initializeGameView foundry.js:9990
    _initializeView foundry.js:9966
    initialize foundry.js:8650
    async* foundry.js:91833
    async* foundry.js:91809
```

When disabling the addon, the expected window shows up in the chat with the ability to click the attack and damage rolls properly

This **does not** happen with the PC actor type
**Versions**
 - Module: 3.0.8
 - dnd5e: 3.0.2
 - Foundry: 11.315

**Other Modules**
none

**Comment by TremendoDude** [comment]
I was running into this issue as well, at first believing it may have been a module compatibility issue. After experimenting with it for a bit, I realized that this only seems to happen when the monster feature in question is unique to a specific unlinked Token. If the ability is added to the main prototype Actor sheet, it works as it should.

**Comment by MangoFVTT** [comment]
Issue is resolved and will be in the next release.
