### ISSUE TITLE
[BUG] Unrecognized Crits on Dual Rolls

### ISSUE THREAD

**Issue by pj-squirrel** [MangoFVTT/fvtt-ready-set-roll-5e#37]
**Description**
When using the option to always Dual Roll, a Critical Hit on the first roll will correctly trigger a Critical Damage roll (double dice), but a Crit on the second roll will not. See screenshots:

![grafik](https://user-images.githubusercontent.com/96775491/189527788-5d2086dc-8a81-4a79-9a94-4df12fe11369.png)

![grafik](https://user-images.githubusercontent.com/96775491/189527642-e35e697c-bb70-4274-a4cd-498478ee03e4.png)

The expected behavior would be, that Crit Damage is rolled whenever any one of the two rolls is a Critical Hit.

**Versions**
 - Module: 1.2.0
 - dnd5e: 2.0.2
 - Foundry: v10 Build 285

**Other Modules**
No other modules active, that modify rolls in any way.

**Comment by MangoFVTT** [comment]
Good catch! This has been fixed and will be in the next release.

**Comment by MangoFVTT** [comment]
This issue is now fixed on Release 1.3.0
