### ISSUE TITLE
[BUG] Compatibility bug: Dice sounds do not play when Dice So Nice! module is active

### ISSUE THREAD

**Issue by noreaga** [MangoFVTT/fvtt-ready-set-roll-5e#378]
**Description**
It seems when you are running both Ready Set Roll and Dice So Nice! modules that the dice sounds do not work during combat. I've only tested this with Dice So Nice! functionality being disabled for combat, so there's no physical dice being rolled from the Dice So Nice! module. There's no sound at all coming from Ready Set Roll.

**Steps to Reproduce**
1. Having both modules enabled.
2. In combat, using a skill or spell will roll but no dice sounds are made.

**Versions**
 - Module: 3.0.9 
 - dnd5e: 3.0.3
 - Foundry: [11.315]

**Other Modules**
Dice So Nice!: 4.6.10

**Comment by MangoFVTT** [comment]
Issue is resolved and will be in the next release.
