### ISSUE TITLE
[FEATURE] Add Setting To Disable Auto-Resistance/Immunity Calculation

### ISSUE THREAD

**Issue by GameCrazed** [MangoFVTT/fvtt-ready-set-roll-5e#379]
**Is your feature request related to a problem? Please describe.**
I am weak, automation scares me. Also currently there's no way to account for if a creature can bypass resistance/immunity? Which leads to having to do it manually which somewhat defeats the purpose of the module. Also in the case of resistances, if the damage doesn't cleanly 1/2 then the creature/player would lose out on 1 damage each time due to rounding losses.

**Describe the solution you'd like**
Would it be possible to add an option to the module's settings that disables the automated damage resistance/immunity calculations and splits the damages back up into their separate rolls (ie for a flametongue sword there'd be a separate box for fire damage and slashing)?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MangoFVTT** [comment]
Automated damage resistance/immunity calculations are handled entirely by the dnd5e system, and not by RSR. Any feature requests related to that should be made as a request on the system github. Do note that RSR is currently hooking into calculation functions in the dnd5e that are not officially released yet, so any feature requests there should be framed as "when released".

As for separate damage application by damage type, this is already implemented. Simply expand the damage tooltip to access the individual damage types 

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/fb6c8611-a834-4d1d-9bf3-76be101384d3)
