### ISSUE TITLE
[BUG] Error message caused by Always Roll Multiple Dice option

### ISSUE THREAD

**Issue by SurrenStarr** [MangoFVTT/fvtt-ready-set-roll-5e#380]
**Description**
When we all have the ''Always Roll Multiple Dice' option enabled, if the DM rolls an action on an actor, such as a stealth check or attack roll, my players see a red error message pop up on on their screens which tells them they don't have permission to update ChatMessage.

A similar thing occurs when one of the players rolls an action on their actor's sheet, while the player who rolled doesn't get the error, the other players still see the message.

If everyone are making rolls at the same time, all the player's screens will become flooded with similar error messages for each actor that has made a roll.

The rolls are still processed and displayed in chat, but the messages can become a little distracting if lots of rolls are happening.

This is an example of what comes up:
"User Ash lacks permission to update ChatMessage [1Yz0I9T4oZoKATSP]"

**Steps to Reproduce**
1. Enable 'Always Roll Multiple Dice' on both the player's and DM's browsers.
2. Roll a skill (e.g. Stealth) or attack from the DM's browser.
3. See error on player's browser window.

**Versions**
 - Module: [3.0.9]
 - dnd5e: [3.0.3]
 - Foundry: [11.315]

**Other Modules**
No other modules installed or enabled.

![ReadySetRollError](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/161175498/1fd71175-3a7a-4250-85bd-f03dd573530d)

**Comment by maxobremer** [comment]
was about to make an issue for the same thing, so yeah got the same thing

**Comment by MangoFVTT** [comment]
Issue has been resolved and will be in the next release.
