### ISSUE TITLE
[BUG] Incompatibility with Automated Conditions 5E for some rolls/hooks

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#384]
**Description**
When using both RSR and [Automated Conditions 5e](https://github.com/thatlonelybugbear/automated-conditions-5e) some of the rolls are not affected by advantage and disadvantage. Attack Rolls seem to function as intended but skill checks, saving throws and ability checks seem to be unaffected by advantage/ disadvantage. Strangely conditions like paralyzed that auto fail dex or str saves still get the -99 penalty from Automated Conditions. Due to the -99 penalty still working I dont think the issue lies with any _preRollXXX hooks or the like

**Steps to Reproduce**
1. Enable both modules
2. Apply a condition like poisoned
3. roll an attack to check (should roll with disadvantage)
4. roll a skill check (should roll with disadvantage)
5. notice that only the attack roll was with disadvantage
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/86924581/a72c196c-0a28-4c5e-a6f0-6c815af95fc2)
(Small note did also check without RSR and then it all works as expected hence why I think the issue lies with RSR and not Automated Conditions 5e)

**Versions**
 - Module: [3.0.10]
 - Automated Conditions 5e: [11.11.2]
 - dnd5e: [3.0.3]
 - Foundry: [11.315]

**Comment by MangoFVTT** [comment]
Issue has been resolved and will be in the next release.
