### ISSUE TITLE
[BUG] Physical damage from spells does not counter Resistance to non-magical physical

### ISSUE THREAD

**Issue by asherett** [MangoFVTT/fvtt-ready-set-roll-5e#387]
**Description**
Piercing/Slashing/Bludgeoning damage done by spells is halved by resistance to non-magical physical attacks.

**Steps to Reproduce**
1. Create or load in an NPC with resistance to physical attacks, countered by "magical":
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/76103282/b2ca2275-71b5-41a4-8f79-a6042e5e83ac)
2. Do damage with a spell that does physical damage to this actor (example: Blade Barrier)
4. Observe that RSR (incorrectly) halves the damage

**Versions**
 - Module: [3.0.9]
 - dnd5e: [3.0.3]
 - Foundry: [11.315]

**Other Modules**
Tested with no other modules running.

**Note/context:** Do note that the Resistances sheet that I screenshoted above (core dnd5e v3.0.3) is a simplification. It only calls out _weapon properties_ that will bypass damage resistance. Creatures in 5e don't have simply "resistance to slashing damage" - the wording most commonly used in the Monster Manual is "Bludgeoning, Piercing, and Slashing _from Nonmagical Attacks_" - so clearly they have no resistance to bludgeoning, piercing or slashing damage caused by non-attacks (such as falling, or spells with saving throws), regardless or them being magical or not. And a spell with an attack roll is clearly also a "magical" attack, even if it's not a weapon attack..

**Comment by MangoFVTT** [comment]
This is an issue with the base dnd5e system, and not with RSR, since RSR does not do any apply damage calculations itself any longer. I suspect that, since the automated damage calculations in the dnd5e system have not been officially finished yet, this was merely overlooked. I would still file this as a bug on their github however. Once it is fixed there, RSR should automatically be fixed as well.

**Comment by asherett** [comment]
Huh. Zhell on the dnd5e channel of the FVTT Discord server said this had to be a RSR bug, since dnd5e 3.0.3 does not calculate **anything** with resistances yet. He said the whole "resistances" sheet (that i screenshoted) was just "for show" currently. So that's the information I based my report on.

**Comment by MangoFVTT** [comment]
Zhell is correct! As I said, the automated damage calculations in the dnd5e system have not been officially finished yet and as such haven't been released per se. But the functionality already exists in the system, which is what RSR is hooking into. Any bugs regarding resistance/immunity in that functionality are independent of RSR and likely a result of the functionality not being fully done yet
