### ISSUE TITLE
[BUG] Apply damage buttons are always shown even if the setting is disabled

### ISSUE THREAD

**Issue by pbasov** [MangoFVTT/fvtt-ready-set-roll-5e#389]
**Description**
Apply damage buttons are always shown even if the setting is to have them only on hover.
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/5103674/b88ffe19-17ab-4db4-bbdc-9bf7baca0a41)

**Steps to Reproduce**
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/5103674/d0e66e45-70eb-43e1-a088-ec0e784fdf4d)

**Versions**
 - Module: 3.0.10
 - dnd5e: 3.0.3
 - Foundry: 11.315

Would also be nice to have an option to hide them for players, showing only to GM.

**Comment by MangoFVTT** [comment]
Issue has been resolved and will be in the next release.
