### ISSUE TITLE
[BUG] DnD5e v3 Damage Enricher Issue with RSR content on Vanilla Rolls

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#394]
**Description**
When you have the Enable Content on Vanilla rolls setting enabled, there is an issue with rolling damage from Enrichers. The roll goes through, but as long as that setting is enabled they are invisible in chat. Unchecking that setting and reloading shows the rolls in chat once more.

**Steps to Reproduce**
1. Enable Content on Vanilla rolls
2. have an enricher like [[/damage 2d6 fire average=true]] in a journal entry or item description
3. roll the damage using the enricher
4. see nothing new in chat despite hearing the sound and getting the little new message notification

**Versions**
 - Module: [3.0.11]
 - dnd5e: [3.0.3]
 - Foundry: [11.315]

**Other Modules**
None

**Comment by maxobremer** [comment]
One final note, the messages are also invisible for players, not just the gm who rolled the damage (in my testing at least)

**Comment by MangoFVTT** [comment]
@maxobremer Post 3.0.13, can you confirm if this issue still arises for you? I suspect this may be related to the missing clause that I mentioned in #303.

**Comment by maxobremer** [comment]
On my end it seems to work fine. good job
