### ISSUE TITLE
[FEATURE] Automated Animations compatibility

### ISSUE THREAD

**Issue by shecrio** [MangoFVTT/fvtt-ready-set-roll-5e#40]
Admittedly I don't know if this has to happen on Automated Animations end or here, but it would be a very nice compatibility to have.

**Comment by MangoFVTT** [comment]
Compatibility with other modules is pending and will be looked into when I have most of the previous Better Rolls features implemented and stable 🙂

**Comment by shecrio** [comment]
I appreciate your effort and your transparency

**Comment by MangoFVTT** [comment]
@shecrio Quick update: from speaking with the author of Automated Animations, this module should largely be compatible with the upcoming release of version 4 (of Automated Animations). I will be confirming compatibility on my end once that version is released 🙂

**Comment by MangoFVTT** [comment]
As of [Automated Animations V4](https://github.com/otigon/automated-jb2a-animations/releases/tag/4.0.0) release, these modules should now be properly compatible. Enjoy!
