### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kylarfi** [MangoFVTT/fvtt-ready-set-roll-5e#406]
**Description**
You can no longer apply each  damage seperately to a token. It now lumps then all in one sum where as before you were able to do each one. It made it very easy if certain damage rolls were not used with every attack.

**Comment by MangoFVTT** [comment]
@Kylarfi you are still able to do this. The separate damage types are inside the card tooltip, simply open that and apply the damage type you wish individually

![damageoverlay](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/f610f9be-9578-435a-abb5-bac082abe06f)
