### ISSUE TITLE
[BUG] Can no longer separately apply multiple damage rolls of the same damage type

### ISSUE THREAD

**Issue by bluewarbler** [MangoFVTT/fvtt-ready-set-roll-5e#407]
**Description**
As the title suggests, when I set up multiple contextual damage rolls in an item's Quick Rolls using the same damage type, it just lumps them together instead of rolling them separately. This is deeply problematic when I am using abilities like Green Flame Blade, which applies different fire damage rolls to the primary target and a secondary target. 

**Steps to Reproduce**
1. Create a spell or item with multiple damage rolls.
2. Make them deal the same damage type.
3. Quick roll them and view the result.

**Versions**
 - Module: 3.0.13
 - dnd5e: 3.0.4
 - Foundry: 11.315

**Comment by MangoFVTT** [comment]
@bluewarbler this is a dnd5e issue and not an RSR issue. There is an open ticket on the dnd5e repo to have it changed: https://github.com/foundryvtt/dnd5e/issues/3199
