### ISSUE TITLE
Attack rolls not showing in the chat [BUG]

### ISSUE THREAD

**Issue by Simon-Scoltock** [MangoFVTT/fvtt-ready-set-roll-5e#408]
**Description**
When I click on an item or spell that has an attack roll I see that "Dice So Nices" creates the dices and roll them but nothing shows up in the chat

**Versions**
 - Module: [3.0.13]
 - dnd5e: [3.0.4]
 - Foundry: [11 build 315]

![Screenshot 2024-03-15 135230](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/102241759/a56ed6c5-ec25-433d-8c6c-931c25e00fc6)
![Screenshot 2024-03-15 135156](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/102241759/dc3248e0-3d95-4f97-8029-0ba6e7f866c8)

**Comment by noreaga** [comment]
Looks like it's a compatibility issue with Dice So Nice!

**Comment by MangoFVTT** [comment]
Potentially related to #404, please check there if any of the "fixes" discussed in that ticket help you out

**Comment by MangoFVTT** [comment]
@Simon-Scoltock I am not able to reproduce this bug on my end, can you confirm that you have no other modules enabled aside from RSR and Dice So Nice?

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/a14f95fd-5063-4701-84b3-00c2ac62b4fe)
