### ISSUE TITLE
"Always Roll Multiple Dice" only rolls critical damage if the FIRST roll is a natural 20

### ISSUE THREAD

**Issue by dlankton** [MangoFVTT/fvtt-ready-set-roll-5e#41]
When the "Always Roll Multiple Dice" configuration is turned on, if I roll:

20 and 18, it will show critical damage properly (for example, 6 + 3 crit)

But if I roll:

18 and 20, it will not show critical damage (for example it will only show 6)

When "Always Roll Multiple Dice" is on, it should show critical damage regardless of which attack roll scores the natural 20.

**Comment by MangoFVTT** [comment]
This issue has been reported and fixed (see ticket #38) and will be resolved in the next feature release 🙂

**Comment by MangoFVTT** [comment]
This issue is now fixed on Release 1.3.0
