### ISSUE TITLE
[BUG] Respect challenge visibility settings in RSR save requests

### ISSUE THREAD

**Issue by psmith150** [MangoFVTT/fvtt-ready-set-roll-5e#420]
**Is your feature request related to a problem? Please describe.**
When a player rolls a saving throw using the button on an item card, the result is highlighted green if it succeeds or red if it fails. This affects abilities that have wording like "after you roll a saving throw but before you know the result, you may add...".

**Describe the solution you'd like**
An option in the settings to disable this highlight. Ideally it would work like the default 5e behavior and still highlight for the GM, just not the players.

**Describe alternatives you've considered**
I'm not aware of a workaround besides not using RSR.

**Additional context**
D&D 53 v3.1.1
Foundry V11.315
RSR 3.0.14

Sample screenshot of highlight for player:
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/23547305/b38fd345-7e33-44bb-b466-4a5553c143f2)

**Comment by MangoFVTT** [comment]
@psmith150 this feature is actually from the base dnd5e system, and not from RSR (see screenshot with base system saves). You should make a feature request to the base system to have an option to hide the red/green highlighting on saves. RSR would automatically work in the same way once implemented.

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/110994627/a10095f8-062a-44ec-8c69-8da30319b972)

**Comment by psmith150** [comment]
@MangoFVTT The base system has a setting for Challenge Visibility that allows you to hide the highlight from the players, but RSR doesn't seem to follow that setting. Here's a screenshot of what the player sees when making a saving throw with no modules enabled and the Challenge Visibility set to "Show only from other players". Keeping this setting the same but enabling RSR results in the screenshot above.
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/23547305/65dbcc38-bbaa-463c-8569-39d2a2d56c69)

**Comment by MangoFVTT** [comment]
Ahh, in that case this is actually a bug request and not a feature request. I'll reopen the ticket

**Comment by MangoFVTT** [comment]
Issue has been resolved and will be in the next release.
