### ISSUE TITLE
[BUG] Enable Content on Vanilla Rolls and targeting

### ISSUE THREAD

**Issue by roguedevjake** [MangoFVTT/fvtt-ready-set-roll-5e#421]
**Description**
Doesn't check targets for AC or damage application via item attack or damage.

**Steps to Reproduce**
1. Enable "Enable content on vanilla rolls"
2. Disable "Enable Alternate Roll for Items"
3. Alt Roll an item with attack and damage elements.
4. No AC validation or targeted damage option will be shown.

**Versions**
 - Module: [3.0.14]
 - dnd5e: [3.1.1]
 - Foundry: [11.315]

**Comment by MangoFVTT** [comment]
Issue is resolved and will be in the next release.
