### ISSUE TITLE
[BUG] Roll Damage Manually and Damage Options

### ISSUE THREAD

**Issue by roguedevjake** [MangoFVTT/fvtt-ready-set-roll-5e#422]
**Description**
When roll damage manually is enabled it will only output "damage" on a quick roll. When the same roll is Alt rolled and "enable content on vanilla rolls" is enabled it shows versatile and other as expected. 

**Steps to Reproduce**
1. Set Roll Damage Manually to always or attack rolls only
2. Roll an attack with a quarterstaff
3. It will show the attack roll and the Damage button, rather than the attack roll, and both the damage and versatile damage buttons. 

_**Image:** top chat card is how it is functioning, bottom is how it functions with an alt roll and should function with a quick roll_

![Screenshot 2024-04-01 152842](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/95041155/f4fa1981-4ab2-4822-aa83-97d478bdc7e0)

**Versions**
 - Module: [3.0.14]
 - dnd5e: [3.1.1]
 - Foundry: [11.315]

**Comment by MangoFVTT** [comment]
This is related to #430. Manual rolling versatile is currently bugged. Will close this as a duplicate
