### ISSUE TITLE
[BUG] Module incompatibility - Libwrapper warn with "Lock & Key"

### ISSUE THREAD

**Issue by Gensokian** [MangoFVTT/fvtt-ready-set-roll-5e#425]
# Description
Whenever a player logs into the VTT they get the error, that LocknKey modify the same functionality.

# Console warn:
```
libWrapper: module Ready Set Roll for D&D5e and module Lock & Key modify the same FoundryVTT functionality and are more likely to conflict.
Detected non-libWrapper wrapping of 'ItemSheet.prototype._onChangeTab' by module ready-set-roll-5e. This will potentially lead to conflicts.
```

# Versions
 - RSR Module: 3.0.14
 - L&K Module 2.7.6
 - dnd5e: 3.1.1
 - Foundry: [11.315]

# Other Modules
Lock & Key
Libwrapper

L&K Issue: https://github.com/Saibot393/LocknKey/issues/86

**Comment by Saibot393** [comment]
I looked into it and the problem seems to be, that Ready set Roll uses manual monkey patching (in hooks.js), replacing the `ItemSheet.prototype._onChangeTab` with the libwrapper equivalent if the module is active should solve it (if possible with as "WRAPPER")

**Comment by MangoFVTT** [comment]
Issue should be resolved and will be in the next release
