### ISSUE TITLE
[BUG] Dice sounds not playing correctly

### ISSUE THREAD

**Issue by psmith150** [MangoFVTT/fvtt-ready-set-roll-5e#427]
**Description**
This is actually 3 separate issues, but they're all related to dice sounds. I can break this up into multiple issues if you'd prefer.

1. Using the Alt key to output a normal roll from an item causes the dice sound to play. Normal system behavior is that the item card doesn't play the dice sound; only the actual rolls (attack, damage, etc) do.
2. When performing a quick roll on an item, the dice sound only plays for that user; it is not sent to any other users. Normal system behavior is that all connected users hear any public rolls.
3. When using the option to roll damage manually, the damage roll does not cause the dice sound to play. Normal system behavior is to play the dice sound on a damage roll.

**Steps to Reproduce**
#### Issue 1
1. Use the Alt key to roll an item (such as a weapon) that does not have an alt roll configured.
2. The card with Attack and Damage buttons appears, but no dice sound plays.
#### Issue 2
1. Have another user connect to the world.
2. Have the user perform a quick roll of an item, such as a weapon.
3. The user who rolled hears the dice, but no one else does.
#### Issue 3
1. Set the setting "Roll damage manually" to "Always".
2. Perform a quick roll of an item that rolls damage, such as a weapon. The attack is rolled and the dice sound can be heard.
3. Click the Damage button to roll damage. The damage is rolled, but no sound is heard.

**Versions**
 - Module: [3.0.14]
 - dnd5e: [3.1.1]
 - Foundry: [11.315]

**Other Modules**
Tested with all other modules disabled.

**Comment by psmith150** [comment]
I was able to figure out fixes for these, if you'd like me to either post them here or make a pull request. I'm still pretty new to Foundry development, so they're probably not the best, but seem to work for now.

**Comment by MangoFVTT** [comment]
@psmith150 Making PRs would be fine (and honestly very helpful as I dont always have time to work on this module), I can review and improve them if need me

**Comment by psmith150** [comment]
Awesome, will do! Do you want to add me as a contributor, or should I fork the repo and submit a PR from there?

**Comment by MangoFVTT** [comment]
Forking and submitting is fine, I can integrate any fork PRs as normal branches quite easily

**Comment by psmith150** [comment]
Sorry for the delay on this; just created a PR.

**Comment by MangoFVTT** [comment]
Issue should be resolved and will be in the next release.
