### ISSUE TITLE
[FEATURE] Auto expanded damage cards on roll

### ISSUE THREAD

**Issue by Its-Scottih** [MangoFVTT/fvtt-ready-set-roll-5e#429]
**Is your feature request related to a problem? Please describe.**
Given the disrespect that was this [ticket](https://github.com/foundryvtt/dnd5e/issues/3199) and the fact that unlike the majority of the people who use foundry, I prefer as close to pen and paper as possible (very little to no automation). I am yet to update to V3. Whilst the developers say "We can look into this" for a flag to remove that god awful feature, they may as well be saying no.

**Describe the solution you'd like**
At the moment, the only other thing that could be done is going full auto 🤮. Would it be possible to include an option in RSR where the card is automatically expanded? All the damage types are there and we can see the individual rolls. Not ideal (or pretty), but a compromise for now.

**Describe alternatives you've considered**
I looked into MidiQOL again since V9. It didnt have that option and also caused issues with other modules. Everything was more compact - but it had nothing else going for it.

**Additional context**
These screenshots are using Midi (Apologies about that)
![Screenshot 2024-05-03 233928](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/128651034/4bc21c88-5aa8-4e57-965d-c7a5ec80291c)
When you attack the card comes out looking like this. And when you click the numbers (19 & 16), it looks more like this:
![Screenshot 2024-05-03 233905](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/128651034/a646cb1e-52e9-465f-8d45-b2c33cda62a6)

Essentially an option to make the rolls always come out looking like the second image, but in RSR style - and only the damage.

Would this be a possibility?

**Comment by MangoFVTT** [comment]
Unfortunately, expansion in cards is handled entirely by the base system and cannot easily be modified. This would be nigh impossible to implement in any reasonable manner without completely rewriting major parts of the style files for dnd5e (which would make maintenance a nightmare).

Fortunately however, there is some good news. The separate damage ticket has been recreated and is being considered for the DND5e 3.3.0 release: https://github.com/foundryvtt/dnd5e/issues/3652
