### ISSUE TITLE
[BUG] Roll Damage Manually and Alternate Rolls for Items

### ISSUE THREAD

**Issue by VotiveEcho** [MangoFVTT/fvtt-ready-set-roll-5e#430]
**Description**
When using Roll Damage manually to always, alt clicking damage won't change the dice being used. For example instead of using a d10 a long sword will still use a d8 when being alt clicked.

**Steps to Reproduce**
1. Set Roll Damage Manually to always 
2. Enable alternate Roll for Items
3. Try using longsword or any item with alternative dice

**Versions**
 - dnd5e: [3.1.2]
 - Foundry: [11.315]

**Comment by maxobremer** [comment]
Did double check this and does appear to be the case. temp work around would be to instead of using versatile just add another damage roll thats the same as the versatile damage formula and in the quick rolls tab on the item set one to normal and 1 to alternate roll

**Comment by MangoFVTT** [comment]
Issue should be resolved and will be in the next release.
