### ISSUE TITLE
[FEATURE] Ignore damage immunity/resistance/vulnerability keys/flags

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#431]
**Is your feature request related to a problem? Please describe.**
Some features and abilities allow you to ignore immunity/resistance/vulnerability, think elemental adept for example. at the moment you have to keep this in mind and manually adjust how much damage you apply to a token. would be nice if this was automated

**Describe the solution you'd like**
DAE added some active effect keys that midi (when bugs are fixed) can use to ignore damage immunity/resistance/vulnerability. It would be cool if RSR damage cards can also look if the actor that made the damage has such active effect keys/flags so that damage is properly applied.

**Describe alternatives you've considered**
If the bugs are fixed it would be to use midi though i like how RSR looks and feels a lot.

**Additional context**

**Comment by MangoFVTT** [comment]
Damage application is handled entirely via the base system nowadays. I would recommend making this a feature request to the dnd5e github so they can add means to ignore certain resistances/immunities, etc. RSR will simply work with that if it is added.
