### ISSUE TITLE
[BUG] Always Roll Multiple Dice Option not working

### ISSUE THREAD

**Issue by Diamondara** [MangoFVTT/fvtt-ready-set-roll-5e#435]
**Description**
The option to automatically rolle 2 dice doesn't change the amount of dice rolled in chat and you can still click on the arrows for adv./disadv. even when it's supposed to be active.

**Steps to Reproduce**
1. Enable the "Always Roll Multiple Dice" option
2. Roll any attack
3. Only one dice to hit is rolled, with the option to add the second one for adv./disadv. when hovering over the roll

**Versions**
 - Module: [3.0.14]
 - dnd5e: [3.1.2]
 - Foundry: [11.315]

Image after rolling an attack with the option enabled
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/29049368/2274bd87-abc9-4a74-955c-93873660df61)

**Comment by MangoFVTT** [comment]
@Diamondara I am unable to reproduce this issue on my end. Can you please provide more details on this bug? Is it only happening for one item, or all? Does it work for skills/saves/abilities? etc. Any details you can give me would be helpful.

**Comment by Diamondara** [comment]
I was part of the game as a player and tested it more together with the DM. Turns out if the DM enables the option it works for the player, but if he has it disabled it is disabled for everybody else. 

Hope that helps

**Comment by MangoFVTT** [comment]
Issue should have been resolved tangentially by a different fix for double-rolling. At least I am no longer able to reproduce this after that fix.
