### ISSUE TITLE
[BUG] Result of attack roll not showing. 

### ISSUE THREAD

**Issue by milesduff** [MangoFVTT/fvtt-ready-set-roll-5e#436]
**Description**
The results of the attack roll are not showing in the card and for some reason it is rolling two dice when that feature is not activated. 

**Steps to Reproduce**
1. Started after I updated foundry to stable 12

**Versions**
 - Module: [latest]
 - dnd5e: [latest]
 - Foundry: [12]

**Other Modules**
No other rolling modules on my foundry.

**Comment by Rommel-holmes** [comment]
just out of curiosity, is there a way to test the module before updating fully? i ran into 2 or 3 times of rolling not showing attack issue, 1 time is conflict with simple calendar module, i don't remember another time, this time is this foundry update.

**Comment by MangoFVTT** [comment]
Issue is resolved and will be in the next release.

**Comment by Rommel-holmes** [comment]
@MangoFVTT thanks for the fix, as it turned out this time it rolls 3 d20, even though on the chat it shows 2 results. maybe a bug?
