### ISSUE TITLE
[FEATURE] instead applying the damage to selected tokens take target tokens

### ISSUE THREAD

**Issue by vt-tom** [MangoFVTT/fvtt-ready-set-roll-5e#45]
**Is your feature request related to a problem? Please describe.**
I come from the DSA/TDE System where i can apply the damage to target tokens. Since i use the Module "Attack Roll Check DnD5e" in DnD5e it would be really cool to have an option, where i can switch the apply damage from selected to target tokens.

**Comment by MangoFVTT** [comment]
This feature is now implemented in Release 1.3.5.

You can select the desired behaviour via this setting:
![image](https://user-images.githubusercontent.com/110994627/190866918-53053cd2-8ce1-4e3b-83df-7fccff9d1522.png)

**Comment by vt-tom** [comment]
This is awesome, thank you
