### ISSUE TITLE
[BUG] "Targets" is shown twice, with the top one being empty

### ISSUE THREAD

**Issue by nschoenwald** [MangoFVTT/fvtt-ready-set-roll-5e#459]
**Description**
![image](https://github.com/user-attachments/assets/10710d99-b06f-48e2-92b9-be99b5302240)

**Versions**
 - current versions of V12, dnd5e 3.3.1 and RSR 3.1.1

**Comment by MangoFVTT** [comment]
Issue should be resolved in next release.
