### ISSUE TITLE
[BUG] Double Roll with 3d dice on Attack Rolls

### ISSUE THREAD

**Issue by Kriosplayz** [MangoFVTT/fvtt-ready-set-roll-5e#460]
**Description**
If a player rolls a weapon/spell attack, the attack roll as well as the damage roll are shown twice with 3d dice, but only one roll is shown in chat.

**Versions**
 - Module: [3.1.1]
 - dnd5e: [3.2.1]
 - Foundry: [12.327]

**Other Modules**
Dice so Nice

**Comment by Kriosplayz** [comment]
Seems like it is the same problem mentioned in the last closed issue. The fix didn't seem to work.

**Comment by MangoFVTT** [comment]
Different to the previous issue as it only seems to be happening for Players, not the GM

**Comment by MangoFVTT** [comment]
Issue should be resolved and will be in the next release

**Comment by Kriosplayz** [comment]
Thanks a lot!
