### ISSUE TITLE
[BUG] Players can see success of attacks and checkmarks / crosses are wrong

### ISSUE THREAD

**Issue by nschoenwald** [MangoFVTT/fvtt-ready-set-roll-5e#465]
**Description**
![image](https://github.com/user-attachments/assets/afbfa2d3-493d-4f52-a470-dce6c67534ad)
![image](https://github.com/user-attachments/assets/11928703-5b24-4805-bce8-fab913e8d6ff)

**Versions**
- current versions of all modules

**Comment by MangoFVTT** [comment]
My bad, an oversight from a changes I made to support the check/x-marks when requesting challenges. Should be fixed with the hotfix release just now

**Comment by nschoenwald** [comment]
Thanks for the quick fix! Really appreciate your work on this module.
