### ISSUE TITLE
[BUG] A strange display of hidden master throws from players

### ISSUE THREAD

**Issue by DoomKiller8328** [MangoFVTT/fvtt-ready-set-roll-5e#468]
When the master's dice are rolled in any way other than the public one, it is displayed to the players as this player's dice roll 0d0

Faundry v12

It's the same throw
![image](https://github.com/user-attachments/assets/5bba68fb-7ae8-4665-bdc8-47af36c5645d)
![image](https://github.com/user-attachments/assets/57ba29e9-4045-4e7e-8306-013f7f64dda5)

**Comment by MangoFVTT** [comment]
Issue is fixed and should be in next release.
