### ISSUE TITLE
[BUG] switch break not reachable in _injectContent() method

### ISSUE THREAD

**Issue by crlgn** [MangoFVTT/fvtt-ready-set-roll-5e#481]
**Description**
The `switch(type)` inside `_injectContent` method on [line 254](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/blob/master/src/utils/chat.js#L254) of chat.js has a few issues with `break;` calls, especially in `case ROLL_TYPE.ATTACK` and `case ROLL_TYPE.DAMAGE`. Ideally, all `case` clauses should break even if empty.

I am using DDB Gamelog and its rolls almost work with your module except for this issue, because if the condition is not met, the compiler does not break and continues until `case ROLL_TYPE.DEATH_SAVE` where there is a proper break. When I manually change the js file to put the break outsde of the conditional clauses, rolls from DnD Beyond work with your module.

Otherwise, thank you for your work, the module is clean and works well.

**Versions**
 - Module: 3.2.0
 - dnd5e: 3.3.1
 - Foundry: 12.330

**Other Modules**
DDB Gamelog v 2.2.0 or 2.3.0-beta

**Comment by MangoFVTT** [comment]
This should be resolved in RSR 3.3.0+
