### ISSUE TITLE
[BUG] Chat card disappearing for a second when rolling damage with DSN (Dice so Nice)

### ISSUE THREAD

**Issue by lipehique** [MangoFVTT/fvtt-ready-set-roll-5e#482]
**Description**
When rolling for damage on a chat card, the chat card disappears for a second then reappears after the roll is resolved when DSN is enabled.

**Steps to Reproduce**
1. Turn on RST and DSN
2. Use an item that outputs chat card with a damage roll
3. Roll damage

**Versions**
 - Module: [3.2.0]
 - Dice so Nice Version 5.0.5
 - dnd5e: [3.3.1]
 - Foundry: [Version 12 Stable, 12.331]
 - Active Modules: 2

**Other Modules**
Dice so Nice

**Comment by MangoFVTT** [comment]
This is intentional and due to how DSN hides roll cards while performing the 3D roll if that setting is enabled. Otherwise the result of the damage would be immediately visible

**Comment by lipehique** [comment]
Thanks for the answer. Very sorry for bothering and adding to it, but I've seen this phenomena before and it was subsequently fixed on a previous patch for RSR. Both videos below demonstrate. One is using an older version of both DSN (4.6.10) and RSR (3.0.14) - DND5e 3.1.1. There is a delay to the damage appearing, sure, but the chat card remains visible.

The second video shows how it is now, version stated in description of issue. No other modules. Chat card disappears for a few seconds, which can be very distracting. If this was indeed intentional I can understand.

https://github.com/user-attachments/assets/c5938ba6-c23d-4c13-95c2-59c3e7ba8077
