### ISSUE TITLE
[BUG] Breaking Bug with Enable Content on Vanilla Rolls is broken

### ISSUE THREAD

**Issue by Zanderaf** [MangoFVTT/fvtt-ready-set-roll-5e#485]
**Description**
Foundry VTT: 12.330
D&D: 3.2.1
RSR: 3.2.0

Enable Content on Vanilla Rolls, and log in through a browser. Works fine and displays fine for a gm, but browsers get this error:
![image](https://github.com/user-attachments/assets/723792be-bf93-4f61-9c0f-251400dff00a)

**Other Modules**
Just RSR installed.

**Comment by MangoFVTT** [comment]
You are on an outdated version of dnd5e and should update to 3.3.1 as that will fix this issue
