### ISSUE TITLE
[BUG] Player-side: Using attacks on a summoned creature does not function

### ISSUE THREAD

**Issue by john-martinez-729** [MangoFVTT/fvtt-ready-set-roll-5e#486]
**Description**
Using an attack on a summoned creature (when running as a player) does not work. It instead causes this error to occur.
![Screenshot 2024-09-07 133354](https://github.com/user-attachments/assets/fdf30a50-4d8c-4957-9313-8934b9599be0)

Note: The attacks seem to work fine when attempted by the GM. This only seems to affect players.

**Steps to Reproduce**
1. Log in as a player
2. Summon a creature through the normal summoning method
3. Click the attack

**Versions**
 - Module: [3.1.0]
 - dnd5e: [3.3.1]
 - Foundry: [11 build 315]

**Comment by john-martinez-729** [comment]
Received a different error today.

![Screenshot 2024-09-09 230141](https://github.com/user-attachments/assets/13061e06-45dc-4aa2-98c8-4ed6e6b2511a)

**Comment by MangoFVTT** [comment]
This issue appears to be resolved in RSR 3.3.0 with dnd5e 4.0.0+

If it reappears on these latest versions, please make a separate issue with the relevant version information
