### ISSUE TITLE
[BUG] Initiative roll displaying combined value of 2d20 instead of 1d20 when Always Roll Multiple Dice is set

### ISSUE THREAD

**Issue by john-martinez-729** [MangoFVTT/fvtt-ready-set-roll-5e#487]
**Description**
When the Always Roll Multiple Dice option is set, and an initiative roll is made, the value displayed shows the result of 2d20 + initiative modifiers.

The correct initiative roll (the first of the 2 d20s rolled, + initiative modifiers) is counted and tracked in the combat tracker.
![Screenshot 2024-09-08 153247](https://github.com/user-attachments/assets/52f588ca-06e3-48b7-8168-19a236ce341e)

Rolling initiative through the Roll All and Roll NPCs buttons on the combat tracker rolls just a single d20, bypassing the Always Roll Multiple Dice option entirely.

**Steps to Reproduce**
1. Toggle a creature's combat state (add it to the combat tracker)
2. Perform an initiative check for that creature, either through the combat tracker or the character sheet.
3. See error

**Versions**
 - Module: [3.1.0]
 - dnd5e: [3.3.1]
 - Foundry: [11 build 315]

**Comment by MangoFVTT** [comment]
@john-martinez-729 you are on old versions of all three of RSR, dnd, and foundry, which I simply can no longer support with development because it would require downgrading basically everything. I would advise updating at your earliest convenience as latest versions do not have this issue.
