### ISSUE TITLE
[BUG] No damage card appearing after damage roll when using manual option.

### ISSUE THREAD

**Issue by rob-sanderson** [MangoFVTT/fvtt-ready-set-roll-5e#490]
**Description**
When using either 'Manual' or 'Attack Rolls Only' options for the 'Roll Damage Manually' setting, an attack roll correctly does not auto roll for damage and displays the 'Damage' button. However when that damage button is used, the roll is made, but no damage card is displayed. If you retrospectively roll an advantage/disadvantage on the original attack roll the full card refreshes and displays the damage roll (including the sum of multiple damage rolls if the 'Damage' button was clicked multiple times).

**Steps to Reproduce**
1. Set Damage to roll manually
2. Roll an attack
3. View attack card in chat
4. Click 'Damage'
5. See that no damage card appears

Optional:
6. Click 'Damage' a few more times
7. Retro roll advantage or disadvantage
8. Cue damage card appearing

**Versions**
 - Module: [3.1.3]
 - dnd5e: [3.3.1]
 - Foundry: [11.315]

**Other Modules**
All others disabled

**Comment by MangoFVTT** [comment]
@rob-sanderson you are on old versions of all three of RSR, dnd, and foundry, which I simply can no longer support with development because it would require downgrading basically everything. I would advise updating at your earliest convenience as latest versions do not have this issue.
