### ISSUE TITLE
[BUG] Versatile damage not showing as an option

### ISSUE THREAD

**Issue by teo-chan** [MangoFVTT/fvtt-ready-set-roll-5e#493]
**Description**
I don't see a way to roll **versatile** damage with out having to always hold ALT and doing it the classic way. Funny enough, the "other formula" damage tipe is showing up as a button in the chat. Only the versatile damage doesn't have a button (and/or its not rolled automaticly).

![image](https://github.com/user-attachments/assets/eb9e04ef-aaf8-42bf-8b21-22b87eb6fa60)

Could it be because im using an older version of this module? I don't use the latest one because when I do a roll, the dice (from Dice So Nice mod) are not showing up/rolling on the screen. But if I use the 3.0.14 version of this mod they are. Please fix this bug aswell if possible.

**Versions**
 - Module: [3.0.14]
 - dnd5e: [3.2.0]
 - Foundry: [11.315]

**Comment by MangoFVTT** [comment]
@teo-chan In this version of dnd/RSR you should be able to simply go to the Quick Roll tab and check the "Versatile" flag. That will roll the versatile damage field instead of the base damage field.

![image](https://github.com/user-attachments/assets/09e6a210-c06b-45cf-a1b8-45184f53a538)

**Comment by nschoenwald** [comment]
@MangoFVTT I'm having this issue while testing the new dnd v4 version. I have a trident with versatile damage setup and I can't figure out how to roll the versatile damage.

**Comment by MangoFVTT** [comment]
@nschoenwald This is a known issue that is system related. Right now the core system only allows switching to versatile in the drop down when rolling an attack manually, which is (imo) really obfuscated and weird. You have two options:

1. Simply make "versatile" a separate activity with a different damage field and roll that when needed (this is what I'm doing atm)
2. Petition the core system developers to have a way to checkmark versatile as a configuration dialog option when rolling the activity, or wait until I get annoyed enough to add it myself 😅
