### ISSUE TITLE
[BUG] dnd v4: Mastery is shown twice

### ISSUE THREAD

**Issue by nschoenwald** [MangoFVTT/fvtt-ready-set-roll-5e#496]
<img width="283" alt="image" src="https://github.com/user-attachments/assets/58baf159-9b83-496a-bd8b-d8d81bc65dd8">

**Versions**
 - Module: 3.3
 - dnd5e: 4.0.4
 - Foundry: 12.331

**Comment by MangoFVTT** [comment]
Issue is resolved and should be in the next release
