### ISSUE TITLE
[BUG] 4.x Damage sometimes not appearing in chat card

### ISSUE THREAD

**Issue by crash1115** [MangoFVTT/fvtt-ready-set-roll-5e#497]
**Description**
When Enable Content on Vanilla rolls is turned ON, and Enable Quick Roll for Activities is OFF, rolling damage from the RSR-ified chat card doesn't show the damage after the roll. No errors in the console, but it does display a log message that indicates it's trying to put *something* in the card.

In the screenshot below,..
- the first message was when I clicked the item on the actor sheet
- the next 2 messages were when clicking the attack button in the chat card
- the last 2 messages were when clicking the damage button in the chat card
![image](https://github.com/user-attachments/assets/15ed2257-56f9-4903-80cd-b66efe762e52)

**Steps to Reproduce**
1. Go to module settings
2. Uncheck Enable Quick Roll for Activities
3. Check Enable Content on Vanilla Rolls
4. Save Changes
5. Open an actor sheet
6. Roll a weapon attack (this should put the card in chat)
7. Click Attack (it should update the chat card as expected)
8. Click Damage (nothing happens)

**Versions**
![image](https://github.com/user-attachments/assets/8dd9b7dd-b1be-43a4-b08f-a0c27936fadd)

**Other Modules**
None

**Comment by MangoFVTT** [comment]
Issue is resolved and should be in the next release
