### ISSUE TITLE
[FEATURE] Temporarily Removal of Disabled Features

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#503]
**Is your feature request related to a problem? Please describe.**
At the moment the settings for RSR are a bit bloated by settings for features that have been disabled for over half a year. This makes the usage of the module (and by extension the [read me](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/blob/master/README.md)) a bit more clunky especially for newcomers to RSR

**Describe the solution you'd like**
Is it maybe possible to remove those features from the settings in the modules and possible from the read me till they are actually added? They are more akin to planned features at this point I feel so should be moved to the [[FEATURE] Issues List](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/issues?q=is%3Aopen+is%3Aissue+label%3Afeature)

**Describe alternatives you've considered**
the only alternative is not using this module so.......

**Additional context**
Good job on the v4 update, was not expecting it to come out for another few months or so 👏

**Comment by MangoFVTT** [comment]
Fair point, should be an easy fix

**Comment by MangoFVTT** [comment]
Issue resolved and should be in next release

**Comment by maxobremer** [comment]
It might be that for me the in foundry RSR settings feels more bloaty then it might actually be, but for the read me it really doesnt need Individual Dice Rerolling, Macro Support and String Queries. Or at least not till they actually function/say something usable.
