### ISSUE TITLE
[FEATURE] Other Activities for Versatile, Light and Thrown Weapons via Script or  Macro

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#507]
**Is your feature request related to a problem? Please describe.**
With the way the dnd5e system handles versatile weapons and the like, using a longsword two handed has become a bit of a pain

**Describe the solution you'd like**
Maybe RSR could come with a script that when an item gains/has the versatile, light or thrown property they gain extra activities that are copies of the normal attack activities but with some adjustments to the damage formula to create separate activities for Two-handed, Offhand and Thrown attacks.

- **Two-handed**: Look at system.damage.base.number, system.damage.base.denomination, system.damage.base.bonus and system.damage.base.types of the item (maybe also have a look at the attack activity for extra damage like a frostbranded weapon) and have an activity with the same values except for an increased system.damage.base.denomination (a new attack damage needs to be made on the item, and include base damage needs to be <ins>disabled</ins> and the new damage needs to have the modifier added to the damage formula)
- **Offhand**. similar as two-handed but make sure the modifier is not added
- **Thrown**. Look at the values of system.range.value and system.range.long on the item and use those

Alternatively if someone can make a macro that just fixes all items (specifically that don't already have activities named  Two-handed, Offhand or Thrown attacks) that could be shipped with RSR for those that just want to 'fix' their weapons

**Describe alternatives you've considered**
Fixing this shit manually by adding activities when it comes up.

**Additional context**

**Comment by maxobremer** [comment]
Btw this could be expanded upon by adding activities for weapon masteries, though I see that as a bit outside of the scope of this module, though if a script/macro is made for this issue, I imagine its not that much of an extra step to solve another issue

**Comment by maxobremer** [comment]
and since this might not require much of RSR code maybe @jagoe is up to it since they did mention wanting to help out? IDK just a suggestion/idea

**Comment by MangoFVTT** [comment]
Generating new activities is a bit beyond the scope of RSR as a module, though it should be not too difficult to create a macro that auto-generates activities for you for weapons that have multiple attack modes. I suspect that the attack modes workflow will be revised at some point, because right now it is, as you said, quite a pain.

**Comment by maxobremer** [comment]
tbh I am kinda surprised the dnd team decided to go for this route of putting it in the attack roll dialogue.

`I suspect that the attack modes workflow will be revised at some point`
As in from the dnd team's side of things? I hope so but do think if they are gonna take that step its gonna be with some automations like discussed on their github page which will probably take some time

**Comment by MangoFVTT** [comment]
It was definitely a strange choice. Many activities require far too much clicking to get the desired result as it stands, but that appears to be the general consensus so I'm sure it will get improved on

**Comment by jagoe** [comment]
@maxobremer Hit me up on Discord (celtsfightnude) and I'll see what I can do. I agree that something like this probably shouldn't be in a module like RSR, but I'll look into creating a macro.

**Comment by MangoFVTT** [comment]
In that case, closing this ticket as "won't do", since it should be handled outside this module 👍
