### ISSUE TITLE
[BUG] RSR does not create chat cards for Utility Activities 

### ISSUE THREAD

**Issue by asherett** [MangoFVTT/fvtt-ready-set-roll-5e#512]
**Description**
RSR does not create any chat card when rolling Utility Activities that don't have rolls.

**Steps to Reproduce**
1. Click on an item that only has a Utility Activity
2. See no chat card being created
3. If you hold down shift to bypass RSR, a chat card is created.

**Versions**
 - Module: [3.3.2]
 - dnd5e: [4.0.4]
 - Foundry: [12.331]

**Other Modules**
Issue exists with RSR as only active module

**Comment by nschoenwald** [comment]
Came here to report this. I had this issue with the Bless spell.

**Comment by MangoFVTT** [comment]
Issue resolved in next release.

**Comment by nschoenwald** [comment]
I just had my first session with dnd v4 and Ready Set Roll and I still had issues with some utility activities not outputting a chat card. This seemed to mostly occur for cards with no roll attached at all, but I can't do deeper testing right now.
Module: [3.3.4]
dnd5e: [4.0.4]
Foundry: [12.331]
@MangoFVTT

**Comment by nschoenwald** [comment]
@MangoFVTT 
<img width="470" alt="image" src="https://github.com/user-attachments/assets/3ee003f4-c74d-4293-b044-5a02cb0bf762">

**Comment by MangoFVTT** [comment]
I haven't been able to reproduce that error, but I've added an extra safety check to prevent it from ever happening. Will be in the next release

**Comment by nschoenwald** [comment]
> I haven't been able to reproduce that error, but I've added an extra safety check to prevent it from ever happening. Will be in the next release

I reproduced it with the War Caster feat, I think it's related to Acitivities without any roll data.

**Comment by nschoenwald** [comment]
@MangoFVTT The new release has fixed it, thank you so much for the quick support!
