### ISSUE TITLE
[BUG] Mastery line on weapon attack cards is not shown to player, only GM

### ISSUE THREAD

**Issue by asherett** [MangoFVTT/fvtt-ready-set-roll-5e#518]
**Description**
The small Mastery (text) line at the end of weapon attack cards generated by RSR is only shown to the GM, not to players.

**Steps to Reproduce**
1. As a player, make an attack with a weapon with Mastery
2. Look at the chat card generated
3. Compare with chat card as it appear to GM

GMs view:
![image](https://github.com/user-attachments/assets/e5f8e9a2-074a-4323-98be-c3a3b9db4cde)

Player's view:
![image](https://github.com/user-attachments/assets/52cdda90-2a83-4c1e-9d94-b9e32c10e256)

Notice "MASTERY Sap" line is missing at the end.

**Versions**
 - Module: [3.3.2]
 - dnd5e: [4.0.4]
 - Foundry: [12.331]

**Other Modules**
Appears with only RSR active

**Comment by MangoFVTT** [comment]
This is not an RSR issue. Default system rolls also don't show the mastery line for players oddly enough (see image below). I would reproduce this with a default non RSR roll and report it to the dnd5e system git instead

![image](https://github.com/user-attachments/assets/e3869d2e-6e43-4f87-b240-8f8f37e0de8a)
