### ISSUE TITLE
[BUG] item with a activity but no roll cause no card to be added to the chat

### ISSUE THREAD

**Issue by SDoehren** [MangoFVTT/fvtt-ready-set-roll-5e#522]
**Description**
Using an item with a activity but no roll cause no card to be added to the chat and the following error:

Uncaught (in promise) TypeError: formulaRolls is not iterable (cannot read property undefined)
[Detected 1 package: ready-set-roll-5e(3.3.2)] at ActivityUtility.runActivityActions (activity.js:64:27)

**Steps to Reproduce**
Use an item with a activity but no roll (example - healers kit)

**Versions**
 - Module: [3.3.2]
 - dnd5e: [4.0.4]
 - Foundry: [12.331]

**Comment by MangoFVTT** [comment]
This issue was fixed in v3.3.4 of RSR: https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/releases/tag/release-3.3.4
