### ISSUE TITLE
[FEATURE] Quick Rolls for Check Activities

### ISSUE THREAD

**Issue by Drowrin** [MangoFVTT/fvtt-ready-set-roll-5e#527]
**Is your feature request related to a problem? Please describe.**
"Check" type Activities currently display a roll button in chat, instead of performing a quick roll, even with "Enable Quick Roll for Activities" enabled. This requires an extra click, and sticks out when so many other types of rolls are rolled automatically. This can be observed by adding any tool to a character sheet and then clicking on the tool or its "Check" activity.

**Describe the solution you'd like**
I'd like for Check Activities to be automatically rolled, similar to Attack and Utility Activities.

An additional thing to consider would be including the results of the check in the original message with the check button instead of creating a separate message for the results, once again mirroring the behavior of Attack and Utility Activities.

**Describe alternatives you've considered**
I've considered trying to work with Utility Activities instead, but they lack some features compared to Check Activities. For example, a Check can include a DC to check against.

**Additional context**
This would obviously be nice for Tool Checks to make their experience a bit nicer and more in-line with other features/items. However, for that specific use-case, users could simply roll the tool proficiency as a skill. That's not my actual use-case, just an easy-to-replicate example. I'd actually love this for implementing stuff like the basic Actions like Hide or Influence with Check Activities.

**Comment by MangoFVTT** [comment]
Check activities are not intended as "the player who rolled this item rolls the check", but as REQUESTS for checks, akin to a save. To roll a check or tool for that player, one should use the skills and tools list in the first tab.

**Comment by Drowrin** [comment]
I see, thank you for the explanation. This led me to investigate a little deeper. I found that stuff like the Actor feat includes its Insight check as a Check activity, ropes include Check activities for escaping them, and so on. However, stuff like Thief Rogue's Quick Hands includes Check activities intended for the user to roll themself. It's unfortunate that the D&D system overloads this activity type with multiple use cases. You're definitely correct that quick-rolling them would not be appropriate due to that.

I'll pursue other solutions. Thanks for the great module!
