### ISSUE TITLE
[BUG] Spell heigtening issue.

### ISSUE THREAD

**Issue by roguedevjake** [MangoFVTT/fvtt-ready-set-roll-5e#528]
**Description**
There is an issue with how rolls are being processed where if you heighten a spell that does damage it will do the heightened amount of damage every time it is called afterwards, even if it is cast at a lower level

**Steps to Reproduce**
1. Clean world, RSR defaults
2. Add burning hands to a PC
3. Cast burning hands as a level 1 spell, roll damage
4. Cast burning hands as a level 2 spell, roll damage
5. Cast burning hands as a level 1 spell, roll damage (it retains the level 2 heightened damage dice)

**Versions**
 - Module: [3.3.5]
 - dnd5e: [4.0.4]
 - Foundry: [12.331]

**Other Modules**
Isolated the issue to this module, heightening works normally without any modules installed.

**Comment by MangoFVTT** [comment]
Issue is resolved and will be in the next release
