### ISSUE TITLE
[BUG] Magic Missile

### ISSUE THREAD

**Issue by DudeAndre** [MangoFVTT/fvtt-ready-set-roll-5e#540]
Right now, with 4.1, RSR does take away the damage button of dnd5e core. Instead you get the small dice icons near the damage rolled.
They doesn't seem to work correctly with Magic Missiles (and may with some other spell I have not thought of).

When you cast magic missile it rolls just 1d4+1. You are supposed, in core, to roll the damage button in the chat again for every single missile. 
With RSR when you click on the little dice it rolls 2d4+2. It should just roll 1d4+1. Because you can separate the missile and also because if you upcast you get to launch for example 4 or 6 missile and you can't get to roll 4 or 6 dice with RSR: you roll 1d4+1 and then 2d4+1 each time, so 1, 3, 5, 7 etc.

**Comment by MangoFVTT** [comment]
@DudeAndre If you disable the Aggregate Damage Fields setting and setup the activity properly with separate fields per dart, the tooltip in RSR will correctly show each dart as an individual damage (you can apply them individually too)

![image](https://github.com/user-attachments/assets/e794a06e-1ac9-4a5c-bb5b-f813437433d9)
![image](https://github.com/user-attachments/assets/2aacfd89-773c-43d6-8b47-681c7e9650d5)

For extra darts, I suggest simply making a second activity under the spell that has consume spell slot disabled, then you can just click that repeatedly to get darts without needing to disable the consume spell slot checkbox every time

![image](https://github.com/user-attachments/assets/38775c61-cfc3-4f58-84c2-bbc0fd8b6eb5)

If what you want is automatic upcasting where a new damage field is added every time, that is just not supported by the system, and there's nothing RSR can do about it. I would suggest making a feature request on the dnd5e git if you want that
