### ISSUE TITLE
Missing red/green results

### ISSUE THREAD

**Issue by godisadj2001** [MangoFVTT/fvtt-ready-set-roll-5e#541]
I may simply be misunderstanding one of the features here, but are the results meant to compare the roll result with the targeted tokens AC and specify whether the hit is a hit or a miss? - I'd love it if it showed as red or green like in the vanilla version of Foundry?

![image](https://github.com/user-attachments/assets/1a9c757f-0699-4f0e-9f60-f821560426bb)

**Comment by godisadj2001** [comment]
Oh in case you need it...
![image](https://github.com/user-attachments/assets/42b6a60d-c023-4afe-ab4b-e5bd6f704eea)

and this is using edition 3.4.1 - and same result with ALL other mods disabled

**Comment by MangoFVTT** [comment]
Attacks never show green/red results in the dice-total, they show it in the targets tray at the bottom of the card. See the images for a comparison of RSR vs Vanilla:

![image](https://github.com/user-attachments/assets/391b5a82-773c-48e3-a2c8-fdcac29d8faa)
![image](https://github.com/user-attachments/assets/f26662f4-edd1-4046-97c5-513784a5137b)

**Comment by godisadj2001** [comment]
@MangoFVTT - That's fantastic news. I like that :) - But it's not showing like that on my example above? - At the point of that screenshot, I think I'd disabled all modules except yours.

**Comment by godisadj2001** [comment]
oh wait I'm an idiot! - I see the tick now! Sorry!

**Comment by MangoFVTT** [comment]
No worries 😄 closing the ticket as completed then 👍
