### ISSUE TITLE
[BUG] When rolling an attack, the Ready-Set-Roll Chatmessage does not appear. 

### ISSUE THREAD

**Issue by Morgeth** [MangoFVTT/fvtt-ready-set-roll-5e#6]
![image](https://user-images.githubusercontent.com/13981516/188704945-bd730b9a-8f83-45b7-99d3-748dce1b8b6c.png)
![image](https://user-images.githubusercontent.com/13981516/188705119-6a1f8d41-bae8-41ce-81fd-2cbd913488b3.png)

**Description**
Once using the character sheet to activate an attack, the damage roller instead rolls using the old visual style, however automatically rolls the dice regardless. A Chat message matching the message displayed in the readme, is not present at any point. 

**Steps to Reproduce**
1. Install using the Client search function.
2. Activate on world
3. Roll basic weapon or spell attack

**Versions**
 - Module: [1.0.1]
 - dnd5e: [2.0.2]
 - Foundry: [10.284]

**Comment by Morgeth** [comment]
Ive come to realise that the roll infact have the correct appearance however it does not automatically roll for the damage of the dice, bringing up the option to choose between critical and normal hit. If the button is pressed then it proceeds as normal. Not sure if that is intended or not. If it is, then I misunderstood. :)

**Comment by MangoFVTT** [comment]
@Morgeth it seems like you may have accidentally triggered the default roll dialog in some fashion. Are you clicking the item's image to trigger the quick roll? And can you confirm if the Enable Item Quick Rolls setting is active and you are not holding alt?

![image](https://user-images.githubusercontent.com/110994627/188707793-a58f4790-90e3-4bce-ad80-0b9b3b79cced.png)

**Comment by Morgeth** [comment]
![image](https://user-images.githubusercontent.com/13981516/188708103-9cca2752-220f-4cb3-a4f7-d9e1efff6e8b.png)
Enable quick Roll for items is active. Not pressing alt, 

I am using the Tidy5e sheet and pressing the image in order to activate the item. 
![image](https://user-images.githubusercontent.com/13981516/188708270-1b4b47f8-fcdc-4aac-89e6-95f3a537b807.png)
When I do so, It automatically rolls the d20 in order to attack, and immediately gives me the standard damage roll prompt (Example below). During this time, the prompt has the default appearance. 
![image](https://user-images.githubusercontent.com/13981516/188708491-44a6aa27-f25e-4123-8cbc-22e1716a4944.png)

If I press normal or Critical, then the chat message is updated with the correct appearance 
![image](https://user-images.githubusercontent.com/13981516/188708659-a6b3cf72-8be7-4892-9547-0a3f16053a06.png)

**Comment by Morgeth** [comment]
Going by the basis of Better rolls, I presume that the damage is meant to roll automatically rather than giving me the prompt for normal or critical damage?

**Comment by MangoFVTT** [comment]
That is correct, however I haven't tested this module in conjunction with any other modules just yet, and I don't use TidySheet5e myself personally. I will investigate this to see what the issue might be

**Comment by MangoFVTT** [comment]
@Morgeth I tested this out with TidySheet and was unable to reproduce the errors you are getting. Are you still having the problem? If yes, what other modules do you have installed and do any of them interact with dice rolls? 

Further to that, if you are not having this problem with every item, exporting the items that you are having the issue on and posting them here so I can take a look at their data would be very helpful.

![TidySheet](https://user-images.githubusercontent.com/110994627/188949916-d09afa16-f2a1-43a6-a764-767b7c396c61.gif)

**Comment by Morgeth** [comment]
Hello again Mango, sorry for not replying back yesterday but I wanted to get some further research done into it myself so I could come back with more concrete information on what is causing it. 

I managed to find the issue, namely the thing causing the error was when the plugin was used in conjunction with Midi-QoL. Midi QoL has an QoL change for rolling automation that ends up conflicting with the plugin. When the option is disabled, the dice works as expected. 
![image](https://user-images.githubusercontent.com/13981516/189212331-f9b754cb-5923-4760-b3f0-4ea266f068b6.png)

![image](https://user-images.githubusercontent.com/13981516/189212419-aeaf68ea-4da9-42d0-a017-a39125caffac.png)

**Comment by MangoFVTT** [comment]
Ah that=t explains it. Midi QOL modifies the same functions as this module, so you cannot use both in conjunction (for dice automation). You have to pick one or the other. Hope that helps you solve the issue 😄
