### ISSUE TITLE
[BUG] RSR Fails to handle synthetic items

### ISSUE THREAD

**Issue by theripper93** [MangoFVTT/fvtt-ready-set-roll-5e#68]
**Description**
Modules such as Argon use Synthetic items for some of it's features. RSR throws an error when such item is rolled

**Steps to Reproduce**
The easiest test is by using Argon combat hud, so install the module
Open the HUD on a linked actor
Try to roll any of the special actions (Disengage\dash etc...)
See the console error

**Versions**
all latest but it should not matter

**Other Modules**
The error can be reproduced by using Argon, but any other module that makes use of synthetic items will generate the same issue. This problem was also present in Better Rolls and was fixed at some point.

**Comment by MangoFVTT** [comment]
Compatibility with other modules is implemented on a case by case basis. In many scenarios, the work needs to be also done from the other module, and is not trivial. I will put Argon on the list to check 🙂

**Comment by theripper93** [comment]
This is not necessarely an Argon specific issue, and again, was present and fixed in Better rolls, the issue can be reporduced by crating a new Item() and attempting to roll it, anyways the fix is extremely simple and not invasive.

roll.js line 99 - change
`await caller.update(itemUpdates);`
to
`caller.id && await caller.update(itemUpdates);`

and the issue is fixed :)

**Comment by MangoFVTT** [comment]
Ah, fantastic. I'll implement the fix you suggested asap and put it in the next release 👍

**Comment by MangoFVTT** [comment]
This issue is (hopefully) fixed in Release 1.3.6
