### ISSUE TITLE
Roll multiple dice toggle on a per person basis

### ISSUE THREAD

**Issue by maxobremer** [MangoFVTT/fvtt-ready-set-roll-5e#71]
Would it be possible to have the roll multiple dice, which rolls 2 d20 when doing a skill check or attack roll if turned on, to be on a per person basis? I myself like to have it always on, but I have players that really like to manually roll the second dice, by clicking again and keep some suspense.

Also great work so far.

**Comment by MangoFVTT** [comment]
This feature has been implemented and will be in the next release.

**Comment by MangoFVTT** [comment]
This feature is now implemented in Release 1.3.7
