### ISSUE TITLE
Consumable Items return to items on use

### ISSUE THREAD

**Issue by realkaleidio** [MangoFVTT/fvtt-ready-set-roll-5e#78]
**Description**
While this module is active, any and all items that are used, instantly appear to disappear, regardless of charges and recharge type, a copy of it is then placed in the item tab. The charge is depleted, so the item in the item tab will have 0/1, if it had 1/1 charges, or 2/3 if it had 3/3, etc.
Basically, upon using any item with charges, it is instantly put into the item tab. If copied out of a folder within the item tab, and used in a character sheet, it is returned into this folder. If used out of the compendium, it is put into the item tab outside of any folders.
Apparently it's only on consumables and it works fine, until the last charge is depleted, no matter if it has "destroy on empty or not". Once it reaches 0 charges, the item will display this behaviour from then on, infinitely returning and duplicating itself.

**Steps to Reproduce**
1. Create Consumable Item with any amount of charges
2. Use it until charges are depleted
3. Have Quantity Depletion on as well
4. The item will return into the inventory
5. Using the returned item, will instantly return it to the inventory no matter the charges

**Versions**
 - Module: [1.3.7]
 - dnd5e: [2.0.3]
 - Foundry: [10.256]

**Other Modules**
Tested with no other modules active, problem persists.

**Comment by realkaleidio** [comment]
I've also just found it will do this infinitely, creating objects which come back every time you restart a world, even if deleted, they will return.

**Comment by MangoFVTT** [comment]
This issue has now been fixed with Release 1.3.8
