### ISSUE TITLE
[FEATURE] Repeat Roll Button

### ISSUE THREAD

**Issue by megahead11** [MangoFVTT/fvtt-ready-set-roll-5e#79]
In BR, there was a button in the top right which, if you clicked it, repeated the previous roll. This repeats the roll with only the dice included (hiding the description). In addition, repeating the roll this way will re-place a template and not consume additional resources.

This feature was especially useful for spells like Scorching Ray and Magic Missile, where you don't want to use more than one spell slot and don't want to repeat the dialogue, but want to use the same roll specifications.

**Comment by MangoFVTT** [comment]
This is a pending feature, but may take some time to get in due to my currently being abroad for some time and needing to work on some stability issues first. I promise to get to it though 🙂

**Comment by Kylarfi** [comment]
Any updates on this?
