### ISSUE TITLE
[BUG] Tiny translation bug

### ISSUE THREAD

**Issue by eduardopato41** [MangoFVTT/fvtt-ready-set-roll-5e#84]
**Description**
On the second to last update I noticed that the module was in English. the /lang/pt-BR.json was there so I looked in the module.json and yep, the language option was gone. Another update and it the same. Maybe it's something with weblate? Just wanted to let you know. Thanks ✌️ 

**Versions**
 - Module: 1.3.8
 - dnd5e: 2.0.3
 - Foundry: 10.286

**Comment by MangoFVTT** [comment]
The language option just seems to have gone missing in the module at some point, likely a merge issue. It should be fixed as of Release 1.3.9
