### ISSUE TITLE
[FEATURE] Elven Accuracy support

### ISSUE THREAD

**Issue by eorea** [MangoFVTT/fvtt-ready-set-roll-5e#86]
**Is your feature request related to a problem? Please describe.**
Yes, retroactively rolling lack of support for Elven Accuracy.

**Describe the solution you'd like**
When retroactively rolling advantage take into consideration if character has the Elven Accuracy feat.

**Additional context**
Elven Accuracy feat sets `flags.dnd5e.elvenAccuracy = true` and then uses `3d20kh` as the attack roll whenever the attack roll has Advantage.

**Comment by MangoFVTT** [comment]
Good catch, the feature was already technically supported, but a bug prevented it from triggering correctly. It should be fixed with Release 1.3.10
