### ISSUE TITLE
[BUG] Spell upcasting not applying when "Always Roll Damage Manually" is on

### ISSUE THREAD

**Issue by Mac-Wright** [MangoFVTT/fvtt-ready-set-roll-5e#87]
**Description**
When upcasting a spell that rolls additional dice when upcast, the additional dice are not rolled if the "Always Roll Damage Manually" setting is on; only the base damage dice for the spell are rolled.
Additionally, any references to @item.level in the damage formula of the spell will use the base level of the spell instead of the upcast level, so it appears to be an issue with the correct level being passed through when manually rolling damage instead of not applying the "Level Scaling" field correctly.

Incorrect Output with "Always Roll Damage Manually" on:
![capture1](https://user-images.githubusercontent.com/56139530/193389546-bfd12093-c53a-4dce-986b-12b68ffe4ffb.png)

Correct Output with "Always Roll Damage Manually" off:
![capture2](https://user-images.githubusercontent.com/56139530/193389989-ae2b1435-3edc-4e4c-ab82-decdd5133f32.png)

**Steps to Reproduce**
1. Turn "Always Roll Damage Manually" on in settings
2. Upcast a spell that rolls additional dice when upcast
3. Additional dice are not applied

**Versions**
 - Module: [1.3.9]
 - dnd5e: [2.0.3]
 - Foundry: [10.286]

**Other Modules**
Issue still occurs with only Ready Set Roll and libWrapper on.

Also, thank you for all your hard work on replacing Better Rolls, it's been great so far :)

**Comment by MangoFVTT** [comment]
Good catch! This should be fixed with Release 1.3.10
