### ISSUE TITLE
[BUG] Uncaught (in promise) Error: Roll.safeEval produced a non-numeric result from expression...

### ISSUE THREAD

**Issue by Larkinabout** [MangoFVTT/fvtt-ready-set-roll-5e#9]
**Description**
Certain damage formula will produce an `Uncaught (in promise) Error: Roll.safeEval produced a non-numeric result from expression...` error.

**Steps to Reproduce**
1. Create actor with 8 Strength.
2. Add Battle Axe + 1 to the actor. Damage formula is 1d8 + @mod + 1. This resolves to 1d8 + -1 + 1.
3. Roll attack.

The bug lies in the `addFieldDamage` function, specifically at: `const partTerms = roll.terms.splice(0, tmpRoll.terms.length);`

**Versions**
 - Module: [1.0.1]
 - dnd5e: [2.0.2]
 - Foundry: [10.284]

**Other Modules**
None.

**Comment by MangoFVTT** [comment]
Fixed by PR #10.
