### ISSUE TITLE
Compatibility Issue with "Magic Items"

### ISSUE THREAD

**Issue by ZeroArcana** [MangoFVTT/fvtt-ready-set-roll-5e#91]
**Description**
Spells granted from **Magic Items** are being triggered twice; regular spells are unaffected. On the first triggering, neither the flavor text, damage type label, nor saving throw are being displayed correctly, nor is the damage being automatically rolled. 

The second triggering of the spell displays normally, although it is often delayed by a few seconds. 

**Steps to Reproduce**
Deselecting the options listed on the Quick Roll tab for the spell hides the specified fields for the second triggering of the spell, but the first triggering of the spell is unaffected. 

Disabling the "Ready Set Roll for 5e" module stops the spells from being triggered twice, and they work normally. Spells activated from a character's regular spellbook function as normal, and are not triggered twice. 

Disabling the "Magic Items" module removes the added spellbook field for Magic Items, negating testing. Spells activated from a character's regular spellbook function as normal, and are not triggered twice. 

**Versions**
 - Module: [1.3.10]
 - dnd5e: [2.0.3]
 - Foundry: [10.286]

**Other Modules**
 - Magic Items [3.0.0]
 - libWrapper [1.12.10.0]

[RSRf5e_error.log](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/files/9691425/RSRf5e_error.log)

[RSRf5e_error2.log](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/files/9691424/RSRf5e_error2.log)

![RSRf5e_BUG1](https://user-images.githubusercontent.com/46655477/193432759-7d60b7e3-ff11-47a5-98af-4aa0147cf652.PNG)

**Comment by MangoFVTT** [comment]
After investigating, it seems this is an issue from Magic Items, and not from RSR. That module force creates a chat message after calling Item.use (see image below from `magicitem.js`), even if a chat message has been created by the normal Item.use call. You should bring this to the attention of the author of that module instead 🙂 

![image](https://user-images.githubusercontent.com/110994627/195382665-1ea58092-a7e3-4d77-a5ea-d760b1f3ced4.png)

**Comment by david-simoes-93** [comment]
Reported here https://github.com/PwQt/magic-items-2/issues/38
