### ISSUE TITLE
[BUG] Concentrator feature (CUB) not functioning correctly with RSR rolls.

### ISSUE THREAD

**Issue by Tristan-82** [MangoFVTT/fvtt-ready-set-roll-5e#93]
**Description**
Concentrator function of Combat Utility Belt is not removing the concentration status automatically when that option is selected. (This works as intended when RSR is NOT enabled but ceases to function when RSR IS enabled.)

**Steps to Reproduce**
So this issue was addressed partly a few weeks back. To preface, I know nothing about coding so I could be completely off base here but yeah. 
So the concentrator functionality in CUB is as follows (if you know how it works already, skip this portion):
1) Token takes damage while concentrating on a spell.
2) Player is prompted to make a concentration (CON) check to see if concentration is maintained.
3) Player selects "yes" to roll the check.
4) Check is rolled.
5)  a) On a successful roll, nothing happens (concentration maintained).
     b) On a failure (**if this setting is enabled) the concentrator function of CUB will automatically remove the concentrating status from the token.

The issue before was occurring in step 4 (the roll was prompted to the player but selecting yes essentially did nothing (no roll was actually made). However, that issue was fixed but now an issue exists in step 5 b. On a failed concentration check, the concentrator function should auto-remove the concentrating status, as I do have that option enabled but it does nothing. The roll goes through, but nothing occurs afterward.

I have a screenshot of the log regarding this issue (although again, I have no coding experience and am unsure how much of this log info is relevant but here goes.

![image](https://user-images.githubusercontent.com/103598867/194719946-0b62786e-f811-4812-aa86-2dd976855904.png)

**Versions**
 - RSR: [1.3.10]
 - CUB [1.10.1]
 - dnd5e: [2.0.3]
 - Foundry: [10.287]

**Other Modules**
Combat Utility Belt (Concentrator function specifically)
Any dependencies for either RSR or CUB.

**Comment by MangoFVTT** [comment]
This has been fixed as part of a general refactor of how rolls are stored in chat cards. With any luck, the refactor should make all RSR chat cards compatible with modules that require the roll values from the chat message, such as CUB's concentrator in this case. The fix will be in the next release.
