### ISSUE TITLE
[FEATURE] hit and miss

### ISSUE THREAD

**Issue by stalker168** [MangoFVTT/fvtt-ready-set-roll-5e#96]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Better Rolls, with proper MIDI QOL settings, could show a message about whether the attack hit or missed, whether the saving throw was successful or not.
I would like to have either the same ability to work together, or to have my own function for displaying the result.

**Describe alternatives you've considered**
Do not participate in automation, but change the design of the chat window to your own.

**Comment by MangoFVTT** [comment]
Checking whether attacks hit/miss, or whether saving throws succeed is a Midi QOL functionality that has nothing to do with Better Rolls/Ready Set Roll. In order for this to work, Ready Set Roll would need to be compatible with Midi QOL, which is currently not the case. 

Compatibility would largely need to be implemented from the Midi QOL side, and there is a ticket open for that on their git repo: https://gitlab.com/tposney/midi-qol/-/issues/997

You can keep an eye on that ticket to track when/if this will be possible in future.

**Comment by stschoelzel** [comment]
I had the same feature request, but checked if someone had that before.
You said it's a MidiQOL feature... but/how did MARS/Moerill did it? -> 
https://github.com/Moerill/fvtt-mars-5e#hitmiss-and-successfail-gm-only

This feature, and maybe the reroll of dice, is the only thing im missing.
MidiQoL is overkill for me.
